/*=====================================================
SCRIPT DE RASTREO COMPLETO
=====================================================
Objetivo: Identificar todas las tablas afectadas por el pago de los recibos:
  - nreceipt: 12824, 12827
  - nbillnum: 306871, 306870
  - npolicy: 1505
=====================================================*/

SET HEADING ON
SET PAGESIZE 50
SET LINESIZE 200

-- ========================================
-- 1. INFORMACIÓN PRINCIPAL EN PREMIUM
-- ========================================
PROMPT
PROMPT === 1. DATOS PRINCIPALES EN TABLA PREMIUM ===
PROMPT

SELECT 
    'PREMIUM' AS TABLA,
    SCERTYPE, NBRANCH, NPRODUCT, NPOLICY, NRECEIPT, NDIGIT, NPAYNUMBE,
    NSTATUS_PRE AS ESTADO,
    DEFFECDATE AS FECHA_EFECTO,
    NPREMIUM AS MONTO,
    NCURRENCY AS MONEDA
FROM PREMIUM
WHERE NPOLICY = 1505
  AND NRECEIPT IN (12824, 12827)
ORDER BY NRECEIPT, DEFFECDATE DESC;

-- ========================================
-- 2. MOVIMIENTOS DE PAGO EN PREMIUM_MO
-- ========================================
PROMPT
PROMPT === 2. MOVIMIENTOS REGISTRADOS EN PREMIUM_MO ===
PROMPT

SELECT 
    'PREMIUM_MO' AS TABLA,
    SCERTYPE, NBRANCH, NPRODUCT, NRECEIPT, NDIGIT, NPAYNUMBE,
    NTYPE AS TIPO_MOVIMIENTO,
    NBILLNUM AS NUM_FACTURA,
    NAMOUNT AS MONTO,
    NEXCHANGE AS TIPO_CAMBIO,
    DLEDGERDAT AS FECHA_LEDGER,
    DEFFECDATE AS FECHA_EFECTO,
    NCASHNUM AS NUM_CAJA
FROM PREMIUM_MO
WHERE SCERTYPE IN (SELECT SCERTYPE FROM PREMIUM WHERE NPOLICY = 1505 AND NRECEIPT IN (12824, 12827))
  AND NBRANCH IN (SELECT NBRANCH FROM PREMIUM WHERE NPOLICY = 1505 AND NRECEIPT IN (12824, 12827))
  AND NPRODUCT IN (SELECT NPRODUCT FROM PREMIUM WHERE NPOLICY = 1505 AND NRECEIPT IN (12824, 12827))
  AND (NRECEIPT IN (12824, 12827) OR NBILLNUM IN (306871, 306870))
ORDER BY DEFFECDATE DESC;

-- ========================================
-- 3. MOVIMIENTOS DE CAJA/BANCO
-- ========================================
PROMPT
PROMPT === 3. MOVIMIENTOS DE CAJA (CASH_MOV) ===
PROMPT

SELECT 
    'CASH_MOV' AS TABLA,
    NBORDEREAUX,
    NVOUCHER AS CODIGO_TRANSACCION,
    SDOCNUMBE AS NUM_CHEQUE,
    NAMOUNT AS MONTO,
    DEFFECDATE AS FECHA_DEPOSITO,
    NSTATUS_MOV AS ESTADO
FROM CASH_MOV
WHERE NBORDEREAUX IN (
    SELECT NBORDEREAUX FROM PREMIUM_MO 
    WHERE NBILLNUM IN (306871, 306870)
      OR NRECEIPT IN (12824, 12827)
)
ORDER BY DEFFECDATE DESC;

-- ========================================
-- 4. DETALLES DE FACTURACIÓN
-- ========================================
PROMPT
PROMPT === 4. DETALLES EN BILL_DET ===
PROMPT

SELECT 
    'BILL_DET' AS TABLA,
    SCERTYPE, NBRANCH, NPRODUCT, NPOLICY,
    NBILLNUM AS NUM_FACTURA,
    NLINE_NUM,
    NAMOUNT AS MONTO,
    DEFFECDATE AS FECHA,
    NSTATUS_BILL AS ESTADO
FROM BILL_DET
WHERE NPOLICY = 1505
  AND NBILLNUM IN (306871, 306870)
ORDER BY NBILLNUM, DEFFECDATE DESC;

-- ========================================
-- 5. REGISTRO DE FACTURAS
-- ========================================
PROMPT
PROMPT === 5. DATOS EN TABLA BILLS ===
PROMPT

SELECT 
    'BILLS' AS TABLA,
    SCERTYPE, NBRANCH, NPRODUCT, NPOLICY,
    NBILLNUM AS NUM_FACTURA,
    NDUEDATE AS FECHA_VENCIMIENTO,
    DEFFECDATE AS FECHA_EMISION,
    NAMOUNT AS MONTO_TOTAL,
    NAMOUNTPAID AS MONTO_PAGADO,
    NSTATUS_BILL AS ESTADO
FROM BILLS
WHERE NPOLICY = 1505
  AND NBILLNUM IN (306871, 306870)
ORDER BY NBILLNUM, DEFFECDATE DESC;

-- ========================================
-- 6. HISTÓRICO DE FACTURAS
-- ========================================
PROMPT
PROMPT === 6. HISTÓRICO EN BILLS_HIS ===
PROMPT

SELECT 
    'BILLS_HIS' AS TABLA,
    SCERTYPE, NBRANCH, NPRODUCT, NPOLICY,
    NBILLNUM AS NUM_FACTURA,
    DCHANGEDAT AS FECHA_CAMBIO,
    NSTATUS_BILL AS ESTADO_NUEVO,
    SCOMMENT AS COMENTARIO,
    SUSER AS USUARIO
FROM BILLS_HIS
WHERE NPOLICY = 1505
  AND NBILLNUM IN (306871, 306870)
ORDER BY DCHANGEDAT DESC;

-- ========================================
-- 7. MOVIMIENTOS DE CUENTA
-- ========================================
PROMPT
PROMPT === 7. MOVIMIENTOS DE CUENTA EN MOVE_ACC ===
PROMPT

SELECT 
    'MOVE_ACC' AS TABLA,
    SCERTYPE, NBRANCH, NPRODUCT, NPOLICY,
    NRECEIPT,
    NBILLNUM,
    NAMOUNT AS MONTO,
    DEFFECDATE AS FECHA,
    NSTATUS_MOV AS ESTADO
FROM MOVE_ACC
WHERE NPOLICY = 1505
  AND (NRECEIPT IN (12824, 12827) OR NBILLNUM IN (306871, 306870))
ORDER BY DEFFECDATE DESC;

-- ========================================
-- 8. DETALLES DE PRIMA
-- ========================================
PROMPT
PROMPT === 8. DETALLES EN DETAIL_PRE ===
PROMPT

SELECT 
    'DETAIL_PRE' AS TABLA,
    SCERTYPE, NBRANCH, NPRODUCT, NPOLICY,
    NRECEIPT,
    NAMOUNT AS MONTO,
    DEFFECDATE AS FECHA,
    SCONCEPTCODE AS CONCEPTO
FROM DETAIL_PRE
WHERE NPOLICY = 1505
  AND NRECEIPT IN (12824, 12827)
ORDER BY NRECEIPT, DEFFECDATE DESC;

-- ========================================
-- 9. COBRANZAS GENERALES
-- ========================================
PROMPT
PROMPT === 9. REGISTROS EN COLLECT_GEN ===
PROMPT

SELECT 
    'COLLECT_GEN' AS TABLA,
    SCERTYPE, NBRANCH, NPRODUCT, NPOLICY,
    NBILLNUM,
    NRECEIPT,
    DEFFECDATE AS FECHA_COBRO,
    NAMOUNT AS MONTO,
    NSTATUS_BILL AS ESTADO
FROM COLLECT_GEN
WHERE NPOLICY = 1505
  AND (NBILLNUM IN (306871, 306870) OR NRECEIPT IN (12824, 12827))
ORDER BY DEFFECDATE DESC;

-- ========================================
-- 10. REGISTRO DE AUDITORIA DE CAMBIOS
-- ========================================
PROMPT
PROMPT === 10. BÚSQUEDA EN TABLA DE AUDITORIA (si existe) ===
PROMPT

SELECT 
    'AUDIT/LOGBILLS' AS TABLA,
    NBILLNUM,
    NRECEIPT,
    DCHANGEDAT AS FECHA_CAMBIO,
    SCOMMENT AS CAMBIO_REALIZADO,
    SUSER AS USUARIO_CAMBIO
FROM LOGBILLS
WHERE NBILLNUM IN (306871, 306870)
   OR NRECEIPT IN (12824, 12827)
ORDER BY DCHANGEDAT DESC;

-- ========================================
-- RESUMEN FINAL
-- ========================================
PROMPT
PROMPT === RESUMEN: TABLAS AFECTADAS ===
PROMPT

SELECT 
    'RESUMEN DE TABLAS IMPACTADAS' AS RESULTADO,
    COUNT(DISTINCT CASE WHEN TABLA = 'PREMIUM' THEN 1 END) AS PREMIUM_RECS,
    COUNT(DISTINCT CASE WHEN TABLA = 'PREMIUM_MO' THEN 1 END) AS PREMIUM_MO_RECS,
    COUNT(DISTINCT CASE WHEN TABLA = 'CASH_MOV' THEN 1 END) AS CASH_MOV_RECS,
    COUNT(DISTINCT CASE WHEN TABLA = 'BILLS' THEN 1 END) AS BILLS_RECS,
    COUNT(DISTINCT CASE WHEN TABLA = 'MOVE_ACC' THEN 1 END) AS MOVE_ACC_RECS
FROM (
    SELECT 'PREMIUM' AS TABLA FROM PREMIUM WHERE NPOLICY = 1505 AND NRECEIPT IN (12824, 12827)
    UNION ALL
    SELECT 'PREMIUM_MO' FROM PREMIUM_MO WHERE NRECEIPT IN (12824, 12827) OR NBILLNUM IN (306871, 306870)
    UNION ALL
    SELECT 'CASH_MOV' FROM CASH_MOV WHERE NBORDEREAUX IN (SELECT NBORDEREAUX FROM PREMIUM_MO WHERE NBILLNUM IN (306871, 306870) OR NRECEIPT IN (12824, 12827))
    UNION ALL
    SELECT 'BILLS' FROM BILLS WHERE NPOLICY = 1505 AND NBILLNUM IN (306871, 306870)
    UNION ALL
    SELECT 'MOVE_ACC' FROM MOVE_ACC WHERE NPOLICY = 1505 AND (NRECEIPT IN (12824, 12827) OR NBILLNUM IN (306871, 306870))
);

PROMPT
PROMPT ========== FIN DEL REPORTE DE RASTREO ==========
