BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TIMETMP.TMP_INT513 CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
CREATE TABLE TIMETMP.TMP_INT513 (
  SKEY                                       VARCHAR2(20 CHAR) NOT NULL,
  NCODRAMO                                   NUMBER(5) NULL, -- NBRANCH
  SCOD_TIPO_CERTIFICADO                      VARCHAR2(1 CHAR) NULL, -- SCERTYPE
  NNRO_TOTAL_ASEGURADO                       NUMBER(20) NULL,
  NNRO_TOTAL_ASEGURADOXCUENTA                NUMBER(20) NULL,
  NCOD_PRODUCTO                              NUMBER(20) NULL, -- COD. PRODUCTO
  SPRODUCTO                                  VARCHAR2(200 CHAR) NULL, -- NOMBRE PRODUCTO
  SDESCRIPCION_ABREVIADA                     VARCHAR2(200 CHAR) NULL, -- DESCRIPCION ABREVIADA DEL PRODUCTO
  SPLAN                                      VARCHAR2(200 CHAR) NULL, -- PLAN
  STIPO_POLIZA                               VARCHAR2(100 CHAR) NULL, -- TIPO DE POLIZA
  STIPO_FACT_COLECTIVO                       VARCHAR2(200 CHAR) NULL, -- FACT. COLECTIVO
  STIPO_DISTRIBUCION                        VARCHAR2(200 CHAR) NULL, -- TIPO DE DISTRIBUCION
  NNRO_POLIZA                                NUMBER(20) NULL, -- NRO. POLIZA
  NCOD_MONEDA_POL                           NUMBER(20) NULL, -- COD. MONEDA POLIZA
  SMONEDA_POL                               VARCHAR2(20 CHAR) NULL, -- MONEDA DE POLIZA
  DFEC_EMISION_POL                          DATE NULL, -- FEC. EMISION POLIZA
  DFEC_INIVIGENCIA_POL                      DATE NULL, -- FEC. INIVIGENCIA POLIZA
  DFEC_FINVIGENCIA_POL                      DATE NULL, -- FEC. FINVIGENCIA POLIZA
  NCOD_ESTADO_POL                           NUMBER(10) NULL, -- COD. ESTADO POLIZA
  SESTADO_POL                               VARCHAR(200 CHAR) NULL, -- ESTADO DE POLIZA
  NCOD_REGIONAL_POL                         NUMBER(10) NULL, -- COD. REGIONAL POLIZA
  SREGIONAL_POL                             VARCHAR(200 CHAR) NULL, -- REGIONAL DE POLIZA
  NCOD_TIPO_INTERMEDIARIO                   NUMBER(20) NULL, -- COD. TIPO INTERMEDIARIO
  STIPO_INTERMEDIARIO                       VARCHAR2(100 CHAR) NULL, -- TIPO DE INTERMEDIARIO
  NCOD_INTERMEDIARIO                        NUMBER(15) NULL, -- COD. INTERMEDIARIO
  SINTERMEDIARIO                            VARCHAR2(300 CHAR) NULL, -- NOMBRE DE INTERMEDIARIO
  NCAPITAL_ASEGURADO_BS                      NUMBER(20) NULL, -- CAPITAL. ASEGURADO, PARA POLIZAS EN MONEDA BOLIVIANOS
  NCAPITAL_ASEGURADO_SUS                      NUMBER(20) NULL, -- CAPITAL. ASEGURADO, PARA POLIZAS EN MONEDA DOLARES
  NDEDUCIBLE_BS                              VARCHAR2(30 CHAR) NULL, -- DEDUCIBLE BS
  NDEDUCIBLE_SUS                              VARCHAR2(30 CHAR) NULL, -- DEDUCIBLE SUS
  SAMBITO_GEOGRAFICO                         VARCHAR2(200 CHAR) NULL, -- AMBITO DE POLIZA
  STIPO_RED_MEDICA                           VARCHAR2(300 CHAR) NULL, -- RED. MEDICA
  SCONTRATANTE                               VARCHAR2(500 CHAR) NULL, -- NOMBRE DE CONTRATANTE
  NNRO_CERTIFICADO                           NUMBER(5) NULL, -- NRO. CERTIFICADO
  NCOD_ASEGURADO                             VARCHAR2(50 CHAR) NULL, -- COD. DE ASEGURADO
  SNOMBRE_ASEG                          VARCHAR2(850 CHAR) NULL, -- NOMBRE DE ASEGURADO
  SAPELLIDO_PATERNO_ASEG                        VARCHAR2(850 CHAR) NULL, -- APELLIDO DE ASEGURADO
  SAPELLIDO_MATERNO_ASEG                        VARCHAR2(850 CHAR) NULL, -- APELLIDO DE ASEGURADO
  SAPELLIDO_CASADA_ASEG                        VARCHAR2(850 CHAR) NULL, -- APELLIDO DE ASEGURADO
  SESTADO_ASEG                          VARCHAR2(200 CHAR) NULL, -- ESTADO DE ASEGURADO
  SGENERO_ASEG                               VARCHAR2(100 CHAR) NULL, -- GENERO DE ASEGURADO
  SRELACION_ASEG                             VARCHAR2(100 CHAR) NULL, -- RELACION DE ASEGURADO
  STIPO_PERSONA_ASEG                         VARCHAR2(200 CHAR) NULL, -- TIPO PERSONA ASEGURADO
  STIPO_DOCUMENTO_ASEG                       VARCHAR2(200 CHAR) NULL, -- TIPO DOCUMENTO ASEGURADO
  SNRO_DOCUMENTO_ASEG                        VARCHAR2(100 CHAR) NULL, -- DOCUMENTO ASEGURADO
  SNRO_COMPLEMENTO_ASEG                         VARCHAR(10 CHAR) NULL, -- COMPLEMENTO
  DFEC_NAC_ASEG                                 DATE NULL, -- FECHA NACIMIENTO ASEGURADO
  NEDAD_ASEG                                    NUMBER(3) NULL, -- EDAD ASEGURADO
  SCIUDAD_RESIDENCIA_ASEG                       VARCHAR2(200 CHAR) NULL, -- RESIDENCIA ASEGURADO
  DFEC_INGRESO_ASEG                             DATE NULL, -- FECHA INGRESO ASEGURADO
  DFEC_ANTIGUEDAD_ASEG                          DATE NULL, -- FECHA ANTIG�EDAD
  NCAPITAL_ANTIGUEDAD_ASEG                      NUMBER(10) NULL, -- CAPITAL ANTIG�EDAD ASEGURADO
  DFEC_INCLUSION_ASEG                           DATE NULL, -- FECHA INCLUSION ASEGURADO
  DFEC_EXCLUSION_ASEG                           DATE NULL, -- FECHA EXCLUSION ASEGURADO
  SCORREO_ASEG                                  VARCHAR2(300 CHAR) NULL, -- CORREO ASEGURADO
  SEXCLUSIONES_PARTICULARES                     VARCHAR2(1000 CHAR) NULL, -- EXCLUSIONES PARTICULARES DEL ASEGURADO
  SCARENCIAS_PARTICULARES                       VARCHAR2(1000 CHAR) NULL,
  SINFO_ESPECIAL                                VARCHAR2(800 CHAR) NULL,
  SOTRO_SEGURO                               VARCHAR2(200 CHAR) NULL, -- OTRO SEGURO
  SCOB_MATERNIDAD                            VARCHAR2(200 CHAR) NULL, -- TIENE MATERNIDAD ASEGURADO
  SCOB_PORC_AMBULATORIA                      VARCHAR2(20 CHAR) NULL, -- PORC. AMBULATORIA
  SCOB_PORC_HOSPITALARIA                     VARCHAR2(20 CHAR) NULL, -- PORC. HOSPITALARIA
  SCOB_PORC_MED_AMBULATORIOS                 VARCHAR2(20 CHAR) NULL, -- PORC_MED. AMBULATORIOS
  SCOB_ADICIONAL_ODONTOLOGICA                VARCHAR2(20 CHAR) NULL, -- ADICIONAL. ODONTOLOGICA
  SCOA_ODONTOLOGICO                          VARCHAR2(500 CHAR) NULL, -- COASEGURO ODONTOLOGICO
  SCLINICA_ODONTOLOGICA                      VARCHAR2(500 CHAR) NULL, -- CLINICA ODONTOLOGICA
  SSEGURO_VIAJERO                            VARCHAR2(20 CHAR) NULL, -- SEGURO AL VIAJERO
  STIENE_EMERGENCIA_MEDICA                    VARCHAR2(20 CHAR) NULL, -- EMERGENCIA DE POLIZA
  SPROVEEDOR_EMERGENCIA_MEDICA                VARCHAR2(500 CHAR) NULL, -- EMERGENCIA DE POLIZA
  SMUERTE_ACCIDENTAL                         VARCHAR2(20 CHAR) NULL, -- MUERTE ACCIDENTAL
  SSEPELIO                                   VARCHAR2(20 CHAR) NULL, -- SEPELIO DE POLIZA
  DFECHAFIN_CREDENCIAL                       DATE NULL, -- FECHAFIN. CREDENCIAL
  SCONDICIONES_COASEGURO_CONSULTA            VARCHAR2(500 CHAR) NULL, -- COASEGURO. CONSULTA
  SOBSERVACIONES                             VARCHAR2(500 CHAR) NULL, -- OBSERVACIONES
  NTIPO_CAMBIO                               NUMBER(18,6) NULL, -- TIPO DE CAMIBIO SEGUN LA FECHA ACTUAL Y EN BASE A LA MONEDA ORIGEN
  SESTADO_CERTIFICADO                        VARCHAR2(500 CHAR) NULL, -- DESCRIPCION DEL ESTADO ACTUAL DEL CERTIFICADO
  STIPO_PERSONA_CONT                         VARCHAR2(200 CHAR) NULL, -- TIPO PERSONA CONTRATANTE
  SLUGAR_NAC_PERS                            VARCHAR2(200 CHAR) NULL -- LUGAR DE NACIMIENTO DE LA PERSONA
);
CREATE OR REPLACE PUBLIC SYNONYM TMP_INT513 FOR TIMETMP.TMP_INT513;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT513 TO INSUDB;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT513 TO INSUDBGEN;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT513 TO VTAPPS;
