BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TIMETMP.TMP_INT514 CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
CREATE TABLE TIMETMP.TMP_INT514 (
  SKEY VARCHAR2(20 CHAR) NOT NULL, -- VALOR DE LLAVE POR LO GENERAL, ES EL NUMERO DE LA TABLA DESDPUES DEL INT. EJEM 514
  SCOD_GRUPO VARCHAR2(20 CHAR) NOT NULL, -- CODIGO GRUPO DE LA PRESTACION.
  SGRUPO VARCHAR2(500 CHAR) NULL, -- DESCRIPCION DEL GRUPO DE LA PRESTACION. EJM. 10 - CONSULTAS
  SCOD_SUBGRUPO VARCHAR2(20 CHAR) NOT NULL, -- CODIGO SUBGRUPO DE LA PRESTACION
  SSUBGRUPO VARCHAR2(300 CHAR) NULL, -- DESCRIPCION DEL SUBGRUPO DE LA PRESTACION. EJM. 1010 - CONSULTAS
  SCOD_PRESTACION VARCHAR2(20 CHAR) NOT NULL, -- CODIGO DE LA PRESTACION
  SPRESTACION VARCHAR2(800 CHAR) NULL, -- DESCRIPCION DE LA PRESTACION. EJM. CONS ALERGOLOGIA
  NVALOR_MO NUMBER(18,6) NULL, -- VALOR O COSTO PARAMETRIZADO PARA EL ARANCEL Y EN LA REGIONAL INDICADA
  NVALOR_LO NUMBER(18,6) NULL, -- SI LA MONEDA ORIGEN ES DOLARES : SVALOR_MO * TIPO_CAMBIO; SI ES MONEDA ORIGEN BOLIVIANOS : SVALOR_MO
  SCIUDAD VARCHAR2(30 CHAR) NULL, -- CIUDAD PARA LA CUAL SE PARAMETRIZO EL ARANCEL
  STIPO VARCHAR2(30 CHAR) NULL, -- POR LO GENERAL, TEXTO "BASE"
  SCOD_MONEDAORIGEN VARCHAR2(20 CHAR) NULL, -- CODIGO DE LA MONEDA CON LA CUAL SE CONFIGURAR EL ARANCEL
  SMONEDA_ORIGEN VARCHAR2(30 CHAR) NULL, -- NOMBRE MONEDA ORIGEN
  NTIPO_CAMBIO NUMBER(18,6) NULL, -- TIPO DE CAMIBIO SEGUN LA FECHA ACTUAL Y EN BASE A LA MONEDA ORIGEN
  SDESCRIPCION_AMV VARCHAR2(200 CHAR) NULL -- DESCRIPCION DEL ARANCEL

);

CREATE OR REPLACE PUBLIC SYNONYM TMP_INT514 FOR TIMETMP.TMP_INT514;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT514 TO INSUDB;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT514 TO INSUDBGEN;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT514 TO VTAPPS;
