BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TIMETMP.TMP_INT526 CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
CREATE TABLE TIMETMP.TMP_INT526 (
  SKEY VARCHAR2(20 CHAR) NOT NULL, 
  SCERTYPE VARCHAR2(1 CHAR),
  NBRANCH  NUMBER(5), 
  NPRODUCT NUMBER(10), 
  NRECEIPT  VARCHAR2(2000 CHAR),
  SRAMO   VARCHAR2(30 CHAR), 
  SPRODUCTO VARCHAR2(100 CHAR),  
  SLINEANEGOCIO VARCHAR2(30 CHAR), 
  NCODREGIONAPOLIZA   NUMBER(5), 
  SREGIONALPOLIZA   VARCHAR2(30 CHAR), 
  DFECHACOBRO   DATE, 
  SCLIENTE  VARCHAR2(100 CHAR),
  NPOLICY  VARCHAR2(30 CHAR),  
  NNROCUOTA  VARCHAR2(500 CHAR),
  STIPOCUOTA  VARCHAR2(100 CHAR),
  NNROFACTURA   VARCHAR2(800 CHAR),
  SPERIODICIDAD  VARCHAR2(30 CHAR),
  SMONEDAPOLIZA		VARCHAR2(30 CHAR),
  NIMPORTEPORCOBRAR_MO  NUMBER(18,6),
  NIMPORTERECIBIDO_MO	NUMBER(18,6),
  NCODOFERENTE   NUMBER(15),
  SNOMBREOFERENTE   VARCHAR2(800 CHAR),
  NPORCENTAJECOMISION NUMBER(18,6),
  NCOMISION    NUMBER(18,6),
  SMOVIMIENTO  VARCHAR2(100 CHAR)
);

CREATE OR REPLACE PUBLIC SYNONYM TMP_INT526 FOR TIMETMP.TMP_INT526;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT526 TO INSUDB;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT526 TO INSUDBGEN;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT526 TO VTAPPS;
