SELECT * FROM PRODMASTER MPRO WHERE NPRODUCT=710
SELECT * FROM PRODUCT MPRO WHERE NPRODUCT=710 AND DNULLDATE IS NULL
SELECT * FROM LIFE_COVER WHERE NBRANCH=5 AND NPRODUCT=710 AND DNULLDATE IS NULL
SELECT * FROM TAB_LIFCOV WHERE NCOVERGEN IN (SELECT LCOV.NCOVERGEN FROM LIFE_COVER LCOV WHERE LCOV.NBRANCH=5 AND LCOV.NPRODUCT=710 AND LCOV.DNULLDATE IS NULL)               
SELECT * FROM TAB_LIFCOV WHERE NCOVERGEN = 92000
SELECT * FROM TAB_MODUL               
               
SELECT  MPRO.NPRODUCT AS COD_PRODUCTO
        , MPRO.SDESCRIPT AS NOMBRE_PRODUCTO
        , LCOV.NCOVER AS COD_COBERTURA
        , MODU.SDESCRIPT AS MODULO_COBERTURA
        , TLCOV.SDESCRIPT AS NOMBRE_COBERTURA
        , TLCOV.NCOVERGEN AS COD_COBERTURA_GENERICA
        , PROD.SPOLITYPE AS TIPO_POLIZA
FROM PRODMASTER MPRO
INNER JOIN PRODUCT PROD ON  MPRO.NBRANCH= PROD.NBRANCH AND MPRO.NPRODUCT=PROD.NPRODUCT AND PROD.DNULLDATE IS NULL
INNER JOIN LIFE_COVER LCOV ON PROD.NBRANCH= LCOV.NBRANCH AND PROD.NPRODUCT= LCOV.NPRODUCT AND LCOV.DNULLDATE IS NULL
INNER JOIN TAB_LIFCOV TLCOV ON LCOV.NCOVERGEN= TLCOV.NCOVERGEN
INNER JOIN TAB_MODUL MODU ON  LCOV.NBRANCH= MODU.NBRANCH AND LCOV.NPRODUCT= MODU.NPRODUCT
                            AND LCOV.NMODULEC= MODU.NMODULEC
                            AND MODU.DNULLDATE IS NULL
WHERE MPRO.NPRODUCT=710 
        --AND LCOV.NCOVER=5 
ORDER BY  MPRO.NPRODUCT,LCOV.NCOVER
      


