SELECT * FROM COVER WHERE NPOLICY=1152 AND NCERTIF=1 
                            AND SCLIENT='00000005399864' AND NCOVER=5

-- TABLA COBERTURA PRODUCTO
SELECT * FROM LIFE_COVER WHERE NPRODUCT=710 AND NCOVER IN (5)
-- TABLA COBERTURA BASE O GENERICA
select * from TAB_LIFCOV where NCOVERGEN IN (SELECT NCOVERGEN FROM LIFE_COVER WHERE NPRODUCT=710 )

-- TABLA DE BENEFICIOS -- RELACIONADA A COBERTARA
SELECT * FROM TAB_MEDBENEFITS WHERE NPOLICY=1152 AND NCERTIF=1 AND NMODULEC=30 
                                    AND NCOVER=5  AND SCLIENT='00000005399864' AND NBENEFCATEG IN (11)

SELECT * FROM TAB_MEDBENEFITS WHERE SBENEFCATEG_CODE = 'TA0002' AND NPOLICY=1152
SELECT * FROM TABLE9222
SELECT * FROM BENEFITS_CATEGORY WHERE NBENEFCATEG=11 -- TIPO DE ATENCION
SELECT * FROM TABLE8604 --- TABLE8604.
SELECT * FROM MEDBENEFITS_PROD WHERE SBENEFCATEG_CODE = 'TA0002' AND NPRODUCT=710 -- TABLA DE BENEFICIOS PARA PROD. DE SALUD
---  MEDICALBENEFITS.SBENEFIT= TAB_MEDBENEFITS.SBENEFCATEG_CODE


SELECT * FROM LEND_AGREE_PRES WHERE NPOLICY=1152 AND NCERTIF=3  AND SCLIENT='00000003437359' AND NMODULEC=20 
SELECT * FROM AGREEMENT WHERE NCOD_AGREE IN (111,1000,1010,1020,1050,30000)


select * from SYS.ALL_SOURCE where upper(TEXT) like '%ODON%'
SELECT * FROM BENEFITS_GROUP WHERE TRIM(SBENEFITGROUP)='TA0001'
SELECT * FROM MEDICALBENEFITS WHERE TRIM(SBENEFIT)='2310101'
SELECT * FROM TAB_AM_ILL WHERE TRIM(SILLNESS)='TA0001'

---  POLIZAS Y SUS COBERTURAS
SELECT  
          COB.NCERTIF AS NRO_CERTIFICADO
        , CASEG.SCLIENT AS COD_CLIENTE
        , CASEG.SFIRSTNAME AS NOMBRE_ASEGURADO
        , CASEG.SLASTNAME AS APELLIDO_ASEGURADO
        , COB.NCOVER AS COD_COBERTURA
        , MODU.SDESCRIPT AS MODULO_COBERTURA
        , TLCOB.SDESCRIPT AS NOMBRE_COBERTURA
        , TLCOB.NCOVERGEN AS COD_COBERTURA_GENERICA
        , BENEF.NPERCEN_HOSPITAL
        , BENEF.NPERCEN_AMBULATORY
        , BENEF.NBENEFCATEG AS COD_CATEGORIA
        , BCAT.SDESCRIPT AS TIPO_CATEGORIA
        , BENEF.SBENEFCATEG_CODE
FROM COVER COB
INNER JOIN LIFE_COVER LCOB ON COB.NBRANCH= LCOB.NBRANCH AND COB.NPRODUCT= LCOB.NPRODUCT
                              AND COB.NCOVER= LCOB.NCOVER AND COB.NMODULEC= LCOB.NMODULEC
                              AND LCOB.DNULLDATE IS NULL
INNER JOIN TAB_LIFCOV TLCOB ON LCOB.NCOVERGEN= TLCOB.NCOVERGEN
INNER JOIN TAB_MODUL MODU ON  LCOB.NBRANCH= MODU.NBRANCH AND LCOB.NPRODUCT= MODU.NPRODUCT
                              AND LCOB.NMODULEC= MODU.NMODULEC
                              AND MODU.DNULLDATE IS NULL                              

INNER JOIN TAB_MEDBENEFITS BENEF ON  COB.NBRANCH= BENEF.NBRANCH AND COB.NPRODUCT= BENEF.NPRODUCT
                                AND COB.NPOLICY= BENEF.NPOLICY  AND COB.NCERTIF=BENEF.NCERTIF
                                AND COB.NMODULEC= BENEF.NMODULEC AND COB.NCOVER= BENEF.NCOVER                                 
                                AND COB.SCLIENT= BENEF.SCLIENT                                 
                                AND BENEF.DNULLDATE IS NULL
INNER JOIN CLIENT CASEG On COB.SCLIENT= CASEG.SCLIENT
INNER JOIN BENEFITS_CATEGORY BCAT ON  BENEF.NBENEFCATEG =BCAT.NBENEFCATEG                        
WHERE COB.NPOLICY= 1152
AND COB.SCLIENT='00000005399864'
--AND COB.NCOVER=5 AND BENEF.NBENEFCATEG=11 -- TIPO DE ATENCION
--AND UPPER(TLCOB.SDESCRIPT) LIKE '%ODONT%'
ORDER BY COB.NCERTIF,COB.sclient,COB.NCOVER