SET DEFINE OFF;
DECLARE
  v_count NUMBER;
BEGIN
  FOR ns IN 511..515 LOOP
    SELECT COUNT(*) INTO v_count FROM INSUDB.FIELDSHEET WHERE NSHEET = ns;
    IF v_count > 0 THEN
      DELETE FROM INSUDB.FIELDSHEET WHERE NSHEET = ns;
    END IF;
  END LOOP;
END;
/
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (511, 6, TO_DATE('29/01/2026 15:31:16', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'CAJERO', 'NCASHNUM', 6, 'TABUSERCASHNUM', 
    10, 3, 'CAJERO', '2', '2', 
    5);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, SVALUE, NFIELDORDER, 
    NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, NDATATYPE)
 Values
   (511, 2, TO_DATE('15/04/2026 15:23:29', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'FECHA FIN', 'DENDDATE', 'SYSDATE', 2, 
    4, 'FECHA FIN', '1', '2', 3);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (511, 4, TO_DATE('29/01/2026 15:23:03', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'TIPO DE INTERMEDIARIO', 'NINTERTYP', 4, 'INTERM_TYPE', 
    5, 3, 'TIPO DE INTERMEDIARIO', '2', '2', 
    5);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (511, 3, TO_DATE('29/01/2026 15:22:48', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'REGIONAL COBRO', 'NOFFICE', 3, 'TABLE9', 
    3, 3, 'REGIONAL COBRO', '2', '2', 
    5);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (511, 5, TO_DATE('29/01/2026 15:23:38', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'INTERMEDIARIO', 'NINTERMED', 5, 'TABINTERMEDIA_I', 
    10, 3, 'INTERMEDIARIO', '2', '2', 
    5);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, SVALUE, NFIELDORDER, 
    NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, NDATATYPE)
 Values
   (511, 1, TO_DATE('15/04/2026 15:23:02', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'FECHA INICIO', 'DINIDATE', 'SYSDATE', 1, 
    4, 'FECHA INICIO', '1', '2', 3);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, NOBJTYPE, 
    SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, NDATATYPE)
 Values
   (512, 2, TO_DATE('20/02/2026 14:17:31', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'FECHA HASTA', 'DENDDATE', 2, 4, 
    'FECHA HASTA', '1', '2', 3);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, NOBJTYPE, 
    SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, NDATATYPE)
 Values
   (512, 1, TO_DATE('20/02/2026 14:16:41', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'FECHA DESDE', 'DINIDATE', 1, 4, 
    'FECHA DESDE', '1', '2', 3);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (512, 3, TO_DATE('20/02/2026 14:20:29', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'REGIONAL POLIZA', 'NOFFICE', 3, 'TABLE9', 
    3, 3, 'REGIONA POLIZA', '2', '2', 
    5);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, NFIELDLARGE, 
    NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, NDATATYPE)
 Values
   (513, 3, TO_DATE('11/03/2026 10:17:45', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'PRODUCTO', 'NCOD_PRODUCTO', 4, 5, 
    6, 'PRODUCTO', '2', '2', 4);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (513, 2, TO_DATE('11/03/2026 09:54:54', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'REGIONAL POLIZA', 'NCOD_REGIONALPOLIZA', 2, 'TABLE9', 
    5, 3, 'REGIONAL POLIZA', '2', '2', 
    4);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, NOBJTYPE, 
    SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, NDATATYPE)
 Values
   (513, 1, TO_DATE('05/03/2026 16:31:39', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'FECHA HASTA', 'DFECHA_HASTA', 1, 4, 
    'FECHA HASTA', '1', '2', 3);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, NFIELDLARGE, 
    NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, NDATATYPE)
 Values
   (513, 6, TO_DATE('11/03/2026 10:18:25', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'RAMO', 'NCOD_RAMO', 3, 5, 
    5, 'RAMO', '2', '2', 4);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (513, 4, TO_DATE('11/03/2026 10:17:17', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'TIPO DE INTERMEDIARIO', 'NCOD_TIPOINTERMEDIARIO', 5, 'INTERM_TYPE', 
    5, 3, 'TIPO DE INTERMEDIARIO', '2', '2', 
    4);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (513, 5, TO_DATE('11/03/2026 10:17:09', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'INTERMEDIARIO', 'NCOD_INTERMEDIARIO', 6, 'TABINTERMEDIA_I', 
    10, 3, 'INTERMEDIARIO', '2', '2', 
    4);
Insert into INSUDB.FIELDSHEET
   (NSHEET, NFIELD, DCOMPDATE, NFIELDTYPE, STABLE, 
    NUSERCODE, SFIELDDESC, SCOLUMNNAME, NFIELDORDER, SVALUESLIST, 
    NFIELDLARGE, NOBJTYPE, SFIELDCOMMEN, SOBLIGATORY, SLASTMOVE, 
    NDATATYPE)
 Values
   (515, 1, TO_DATE('01/04/2026 09:38:07', 'DD/MM/YYYY HH24:MI:SS'), 3, '0', 
    1782, 'REGIONAL', 'NCOD_REGIONAL', 1, 'TABLE9', 
    5, 3, 'REGIONAL', '2', '2', 
    5);
COMMIT;
