SET DEFINE OFF;
DECLARE
  v_count NUMBER;
BEGIN
  FOR ns IN 511..515 LOOP
    SELECT COUNT(*) INTO v_count FROM INSUDB.WINDOWS WHERE SCODISPL = 'INT' || ns || '  ';
    IF v_count > 0 THEN
      DELETE FROM INSUDB.WINDOWS WHERE SCODISPL = 'INT' || ns || '  ';
    END IF;
  END LOOP;
END;
/
Insert into INSUDB.WINDOWS
   (SCODISPL, NAMELEVEL, SCODISP, NIMG_INDEX, SCODMEN, 
    DCOMPDATE, SDESCRIPT, SDIRECTGO, NINQLEVEL, NMODULES, 
    SPSEUDO, NSEQUENCE, SSHORT_DES, SSTATREGT, NUSERCODE, 
    NWINDOWTY, NHEIGHT, SAUTOREP, NTYPE_REPORT, NLENGTH_NOTES)
 Values
   ('INT511  ', 5, 'GI1402_K', 4, 'MENCTROL', 
    TO_DATE('26/01/2026 16:00:59', 'DD/MM/YYYY HH24:MI:SS'), 'REPORTE DE CONTROL DE INGRESO', '1', 5, 503, 
    'CTRL INGRESO', 60, 'CTRL ING    ', '1', 1782, 
    2, 0, '2', 0, 0);
Insert into INSUDB.WINDOWS
   (SCODISPL, NAMELEVEL, SCODISP, NIMG_INDEX, SCODMEN, 
    DCOMPDATE, SDESCRIPT, SDIRECTGO, NINQLEVEL, NMODULES, 
    SPSEUDO, NSEQUENCE, SSHORT_DES, SSTATREGT, NUSERCODE, 
    NWINDOWTY, NHEIGHT, SAUTOREP, NTYPE_REPORT, NLENGTH_NOTES)
 Values
   ('INT512  ', 5, 'GI1402_K', 4, 'MENCTROL', 
    TO_DATE('20/02/2026 15:13:06', 'DD/MM/YYYY HH24:MI:SS'), 'REPORTE DE ASEGURADOS TODOS', '1', 5, 503, 
    'REPASEGTODOS', 110, 'REPASEGTODOS', '1', 1782, 
    1, 0, '2', 0, 0);
Insert into INSUDB.WINDOWS
   (SCODISPL, NAMELEVEL, SCODISP, NIMG_INDEX, SCODMEN, 
    DCOMPDATE, SDESCRIPT, SDIRECTGO, NINQLEVEL, NMODULES, 
    SPSEUDO, NSEQUENCE, SSHORT_DES, SSTATREGT, NUSERCODE, 
    NWINDOWTY, NHEIGHT, SAUTOREP, NTYPE_REPORT, NLENGTH_NOTES)
 Values
   ('INT513  ', 5, 'GI1402_K', 4, 'MENCTROL', 
    TO_DATE('12/03/2026 15:23:25', 'DD/MM/YYYY HH24:MI:SS'), 'REPORTE DE POLIZAS CON ASEGURADOS VIGENT', '1', 5, 503, 
    'REP_ASEGVIG ', 103, 'ASEG VIG    ', '1', 1782, 
    2, 0, '2', 0, 0);
Insert into INSUDB.WINDOWS
   (SCODISPL, NAMELEVEL, SCODISP, NIMG_INDEX, SCODMEN, 
    DCOMPDATE, SDESCRIPT, SDIRECTGO, NINQLEVEL, NMODULES, 
    SPSEUDO, NSEQUENCE, SSHORT_DES, SSTATREGT, NUSERCODE, 
    NWINDOWTY, NHEIGHT, SAUTOREP, NTYPE_REPORT, NLENGTH_NOTES)
 Values
   ('INT514  ', 5, 'GI1402_K', 4, 'MENCTROL', 
    TO_DATE('31/03/2026 11:40:00', 'DD/MM/YYYY HH24:MI:SS'), 'LISTADO DE AMV', '1', 5, 503, 
    'REPAMV      ', 104, 'LISTAMV     ', '1', 1782, 
    2, 0, '2', 0, 0);
Insert into INSUDB.WINDOWS
   (SCODISPL, NAMELEVEL, SCODISP, NIMG_INDEX, SCODMEN, 
    DCOMPDATE, SDESCRIPT, SDIRECTGO, NINQLEVEL, NMODULES, 
    SPSEUDO, NSEQUENCE, SSHORT_DES, SSTATREGT, NUSERCODE, 
    NWINDOWTY, NHEIGHT, SAUTOREP, NTYPE_REPORT, NLENGTH_NOTES)
 Values
   ('INT515  ', 5, 'GI1402_K', 4, 'MENCTROL', 
    TO_DATE('31/03/2026 11:40:15', 'DD/MM/YYYY HH24:MI:SS'), 'LISTADO DE REDES MEDICAS', '1', 5, 503, 
    'REDMED      ', 105, 'REDMEDICA   ', '1', 1782, 
    2, 0, '2', 0, 0);
COMMIT;
