SELECT
    Finan.namount as MontoCuota,
    Finan.nstat_draft,
    TRIM(estcuot.sdescript) EstadoCuota,
    Finan.namount_net MontoCuotaSinInteres,
    Finan.nclaim,
    cla.nclaim IdSiniestro,
    Finan.ncommission MontoComisionCuota,
    Finan.dcompdate FechaRegistro,
    Finan.ncontrat,
    Finan.ndraft NroCuota,    
    Finan.nintammou MontoInteresCuota,
    Finan.nstatprint IdEstadoImpresion,
    TRIM(estimp.sdescript) EstadoImpresion,
    Finan.nintermed,
    Finan.dstat_date,
    Finan.nusercode,
    Finan.nbulletins,
    Finan.namo_afec,
    Finan.namo_exen,
    Finan.niva,
    Finan.ncom_afec,
    Finan.ncom_exen,
    Finan.dexpirdat FechaVencimiento,
    Finan.dlimitdate FechaLimitePago,
    Finan.nbordereaux,
    Finan.sindcheque,
    Finan.dcollsus_ini,
    Finan.dcollsus_end,
    Finan.nsus_reason,
    Finan.ssus_origi,
    Finan.ncollector,
    Finan.nbillnum,
    Finan.sbilltype,
    Finan.nway_pay IdViaDePago,
    TRIM(viapago.sdescript) ViaDePago,
    Finan.sdocnumbe,
    Finan.nretentiontaxcode,
    Finan.nretentioncode,
    Finan.nretentionseries,
    Finan.dautorizationdate,
    Finan.dendingdate,
    Finan.nretention,
    Finan.ntaxretention,
    Finan.nretentionbase,
    Finan.nautorizationnumber,
    Finan.nemisright,
    Finan.niva_ssc,
    Finan.niva_sbk,
    Finan.niva_other,
    Finan.niva_other_desc,
    Finan.niva_other_descompen,
    Finan.niva_percent
FROM
    financ_dra Finan
INNER JOIN TABLE253 EstCuot On finan.nstat_draft= EstCuot.nstat_draft
LEFT JOIN CLAIM cla ON finan.nclaim= cla.nclaim
INNER JOIN TABLE5002 ViaPago ON finan.nway_pay= viapago.nway_pay 
INNER JOIN TABLE282 EstImp ON finan.nstatprint= estimp.nstatprint
WHERE 
    Finan.ncontrat=206