SELECT
    deta.nproduct,
    deta.nreceipt,
    deta.nbranch,
    deta.scertype,
    deta.ndigit,
    deta.npaynumbe,
    deta.nid_bill,
    deta.saddsuini,
    deta.stype_detai,
    deta.ndet_code,
    deta.dcompdate,
    deta.ncapital,
    deta.ncommi_rate,
    deta.ncommision,
    deta.npremium,
    deta.ntax,
    deta.nbill_item,
    CFact.sdescript ConceptoFacturacion,
    deta.nbranch_est,
    deta.nbranch_led,
    deta.nbranch_rei,
    deta.nusercode,
    deta.npremanual,
    deta.saddtax,
    deta.ncomanual,
    deta.npremiuma,
    deta.npremiume,
    deta.ntaxamount,
    deta.nrecamount,
    deta.ndescamount,
    deta.nrel_idbill,
    deta.sclient,
    deta.nrel_idcode,
    deta.nstipend_amount,
    deta.nstipend_annual,
    deta.ntaxrate,
    deta.ndissur_type,
    deta.ncom_super,
    deta.ncomanual_super
FROM
    detail_pre deta
INNER JOIN TAB_BILL_I CFact on deta.nbill_item= cfact.nbill_item and deta.nbranch= cfact.nbranch and deta.nproduct= cfact.nproduct
WHERE 
deta.nreceipt=22722 and deta.scertype=2  and deta.nbranch=5 and deta.nproduct=700