SELECT
    mov.ntyp_acco,
    TipCtaCte.sdescript TipoCuentaCorriente,
    mov.stype_acc,
    mov.sclient,
    mov.ncurrency,
    mov.doperdate,
    mov.nidconsec,
    mov.nintermed,
    mov.namount,
    mov.nbankext,
    mov.nbranch,
    mov.ncertif,
    mov.scheque,
    mov.nclaim,
    mov.ncredit,
    mov.ndebit,
    mov.sdescript,
    mov.smanualmov,
    mov.npaynumbe,
    mov.npolicy,
    mov.nreceipt,
    mov.sstatregt,
    mov.ntransac,
    mov.ntransactio,
    mov.ntype_move,
    TipMov.sdescript TipoMovimiento,
    mov.ntype_pay,
    mov.ntype_tran,
    mov.nusercode,
    mov.nprovince,
    mov.dcompdate,
    mov.niddocument,
    mov.nrequest_nu,
    mov.nbordereaux,
    mov.sprocess,
    mov.snumform,
    mov.norigcurr,
    mov.nexchange,
    mov.sautoriza,
    mov.dvaluedate,
    mov.nproduct,
    mov.snull_recor,
    mov.ncashnum,
    mov.namoafect,
    mov.namoexen,
    mov.npay_comm,
    mov.ncurr_acc,
    mov.dposted,
    mov.sprocess_ind,
    mov.nproponum,
    mov.nbulletins,
    mov.nnotenum,
    mov.nid,
    mov.namountdec,
    mov.nobligation,
    mov.nserv_order,
    mov.ntypesupport,
    mov.ndocument,
    mov.namount_loc,
    mov.nbalance,
    mov.sclient_rel,
    mov.spay_form,
    mov.ncod_agree,
    mov.nbillnum,
    mov.sdep_number,
    mov.ntodaysdeposit,
    mov.nretentiontaxcode,
    mov.nretentioncode,
    mov.nretentionseries,
    mov.dendingdate,
    mov.nretention,
    mov.ntaxretention,
    mov.nretentionbase,
    mov.nautorizationnumber,
    mov.dautorizationdate,
    mov.dctb_date,
    mov.spostedsequence,
    mov.nori_amount,
    mov.sscab,
    mov.ddate_scab,
    mov.nseq
FROM
    move_acc mov
INNER JOIN TABLE400 TipCtaCte on mov.ntyp_acco=tipctacte.ntyp_acco
INNER JOIN TABLE401 TipMov on mov.ntype_move = tipmov.ntype_move
WHERE mov.NBordereaux= 1647 



--select * from TABLE400