SELECT
    cob.scertype,
    cob.nbranch,
    cob.nproduct,
    cob.npolicy,
    cob.ncertif,
    cob.ngroup_insu,
    cob.nmodulec,
    cob.ncover,
    tablcov.sdescript NombreCobertura,
    cob.deffecdate,
    cob.sclient,
    cob.nrole,
    cob.ncapital CapitalCobertura,
    cob.ncapitali CapitalInicialCobertura,
    cob.schange,
    cob.dcompdate,
    cob.sfrandedi,
    cob.ncurrency,
    cob.ndiscount,
    cob.nfixamount,
    cob.nmaxamount,
    cob.sfree_premi,
    cob.nminamount,
    cob.dnulldate,
    cob.npremium PrimaTotal_Anual,
    cob.nrate,
    cob.nwait_quan,
    cob.nratecove,
    cob.nusercode,
    cob.swait_type,
    cob.sfrancapl,
    cob.ndisc_amoun,
    cob.ntypdurins,
    cob.ndurinsur,
    cob.nageminins,
    cob.nagemaxins,
    cob.nagemaxper,
    cob.ntypdurpay,
    cob.ndurpay,
    cob.ncauseupd,
    cob.ncapital_wait,
    cob.nagelimit,
    cob.nage_per,
    cob.daniversary,
    cob.dseektar,
    cob.dfer,
    cob.NBranch_Rei,
    cob.nretarif,
    cob.ncapital_o,
    cob.npremium_o,
    cob.nratecove_o,
    cob.ntaxamount IVA_Anual,
    cob.nrecamount Recargo_Anual,
    cob.ndescamount Descuento_Anual,
    cob.ncommi_an,
    cob.nratecove_b,
    cob.ncapital_req,
    cob.nratecla,
    cob.nfixamocla,
    cob.nminamocla,
    cob.nmaxamocla,
    cob.ndisccla,
    cob.ndisc_amocla,
    cob.nfrancdays,
    cob.nfreqmaxeven,
    cob.sroutmax_even,
    cob.nfrequen,
    cob.nmaxeven_quan,
    cob.sreduccapital,
    cob.nreducapage,
    cob.nagelimitcap,
    cob.nperccoas,
    cob.dfree_prem_in,
    cob.dfree_prem_lim,
    cob.dantidate,
    cob.nanti_amount,
    cob.nclaimrat
FROM
    cover cob
INNER JOIN life_cover lcov on cob.ncover=lcov.ncover and cob.nbranch=lcov.nbranch and cob.nproduct=lcov.nproduct and cob.nmodulec=lcov.nmodulec
INNER JOIN TAB_LIFCOV tablcov on lcov.ncovergen= tablcov.ncovergen
WHERE cob.npolicy=1504 and cob.scertype=2  and cob.nbranch=5 and cob.nproduct=700