SELECT
    pol.scertype,
    TipoCert.sdescript TipoCertificado,
    pol.nbranch,
    Ramo.sdescript RAmo,
    pol.nproduct,
    Prod.sdescript Producto,
    pol.Dnulldate FechaAnulacion,
    pol.npolicy,
    pol.sclient,
    cli.scliename NombreCliente,
    pol.saccounti,
    pol.sbussityp,
    pol.scoinsuri,
    pol.scolinvot,
    pol.scolreint,
    pol.scoltimre,
    pol.scommityp,
    pol.sdeclari,
    pol.sdirdebit,
    pol.sindextyp,
    pol.sleadinvo,
    pol.sleadnoti,
    pol.sleadpoli,
    pol.spolitype,
    pol.spropo_cert,
    pol.srenewal,
    pol.srevalapl,
    pol.sstatus_pol,
    EstPol.sdescript EstadoPoliza,
    pol.ssubstiti,
    pol.styp_clause,
    pol.styp_discxp,
    pol.styp_module,
    pol.snonull,
    pol.sconcoll,
    pol.snumform,
    pol.dchangdat FechaUltimaModificacion,
    pol.dcompdate FechaRegistro,
    pol.ddat_no_con,
    pol.ddate_origi InicioVigenciaOriginal,
    pol.dstartdate InicioVigenciaActual,
    pol.dexpirdat TerminoVigencia,
    pol.dissuedat FechaEmision,
    pol.dmaximum_da,
    pol.dnulldate,
    pol.dpropodat,
    pol.dnextreceip,
    pol.namoucomm MontoComision,
    pol.ncapital CapitalAsegurado,
    pol.ncolcladi,
    pol.ncommissi PorcentajeComision,
    pol.nindexfac,
    pol.nleadcomi,
    pol.nleadexpe,
    pol.nleadshare,
    pol.nparticip,
    pol.npremium PrimaAnualPolza,
    pol.nshare,
    pol.npayfreq,
    fpago.sdescript FrecuenciaPago,
    pol.nintermed,
    CInter.scliename Intermediario,
    pol.nlast_certi,
    pol.nnote_adend,
    pol.nnote_benef,
    pol.nnote_comme,
    pol.nnote_condi,
    pol.nnote_cover,
    pol.nproponum  As NroPropuesta,
    pol.nq_certif,
    pol.ntransactio,
    pol.nmov_histor,
    pol.noficial_p,
    pol.ncopies,
    pol.nleadcomp,
    pol.nno_convers,
    pol.nnotice,
    pol.nnullcode,
    pol.noffice,
    Suc.sdescript Sucursal,
    pol.noffice_own,
    pol.ntariff,
    pol.nuser_amend,
    pol.nusercode,
    Usr.scliename UsuarioCreacionModificacion,
    pol.nquota,
    pol.stype_prop,
    pol.sprorshort,
    pol.ndaysfq,
    pol.ndayssq,
    pol.ncompany,
    pol.nofficeins,
    pol.soriginal,
    pol.ncod_agree,
    pol.stypenom,
    pol.snopayroll,
    pol.sinsubank,
    pol.nlegamount,
    pol.sleg,
    pol.nagency,
    Agen.sdescript Agencia,
    pol.nofficeagen,
    pol.scoltpres,
    pol.sind_comm,
    pol.scurracc,
    pol.nrepinsured,
    pol.nlocal,
    pol.ddaterenova,
    pol.nclaim_notice,
    pol.smassive,
    pol.srepprintcov,
    pol.sreceipt_ind,
    pol.sdocutyp,
    pol.nterm_grace,
    pol.nprodclas,
    pol.nagreement,
    pol.sacchsend_ind,
    pol.ntypeaccount,
    pol.dprevius_expirdate,
    pol.nspecialbusiness,
    pol.nleadym,
    pol.dexpirdatant,
    pol.stypcalc_flatprem,
    pol.stypdis_paypercen,
    pol.nparticip_polemp,
    pol.nparticip_polco,
    pol.sprevpolnum
FROM   policy pol
INNER JOIN Table5632 TipoCert on Pol.Scertype= TipoCert.Scertype
INNER JOIN Table10 Ramo on Pol.Nbranch  = ramo.nbranch
INNER JOIN Table36 Fpago on pol.npayfreq = fpago.npayfreq
INNER JOIN PRODMaster Prod on pol.nproduct= prod.nproduct
INNER JOIN Table9 Suc on pol.noffice = suc.noffice
INNER JOIN Table5555 Agen on pol.nagency= agen.nagency
INNER JOIN Table181 EstPol on pol.sstatus_pol= estpol.sstatusva
LEFT JOIN CLIENT cli on pol.sclient= cli.sclient
LEFT JOIN INTERMEDIA Inter on pol.nintermed= inter.nintermed
LEFT JOIN Client     CInter on inter.sclient = Cinter.sclient
LEFT JOIN CLIENT     Usr on pol.nusercode= Usr.sclient
WHERE  pol.npolicy=1593
 --pol.sstatus_pol=5 --Vigente
 and pol.scertype=2  and pol.nbranch=5 and pol.nproduct=700
ORDER BY pol.dissuedat desc