SELECT
    cert.scertype,
    TipoCert.sdescript TipoCertificado,
    cert.nbranch,
    Ramo.sdescript RAmo,
    cert.nproduct,
    Prod.sdescript Producto,
    cert.npolicy,
    cert.ncertif,
    cert.sclient,
    cli.scliename NombreCliente,
    cert.ncapital,
    cert.dcompdate as FechaRegistro,
    cert.scumul_code,
    cert.ddat_no_con,
    cert.ddate_origi FechaInicioVigencia,
    cert.dchangdat AS FechaUltimaModificacion,
    cert.dexpirdat AS FechaVencimiento,
    cert.ngroup,
    cert.dissuedat As FechaEmision,
    cert.dmaximum_da,
    cert.nno_convers,
    cert.nnote_benef,
    cert.nnote_drisk,
    cert.nnullcode,
    cert.dnulldate FechaAnulacion,
    cert.npayfreq,
    fpago.sdescript FrecuenciaPago,
    cert.npremium,
    cert.dpropodat,
    cert.srenewal,
    cert.nsituation,
    cert.dstartdate,
    cert.sstatusva,
    EstPol.sdescript EstadoPoliza,
    cert.nuser_amend,
    cert.nusercode,
    Usr.scliename UsuarioCreacionModificacion,
    cert.nsus_branch,
    cert.nwait_code,
    cert.nsus_product,
    cert.nsus_policy,
    cert.nsus_certif,
    cert.dnextreceip,
    cert.nproponum As NroPropuesta,
    cert.nquota As NroCuotasPoliza,
    cert.ndaysfq,
    cert.sprorshort,
    cert.ndayssq,
    cert.snumform,
    cert.sreinsura,
    cert.sclaimind,
    cert.sexception,
    cert.nexccause,
    cert.sproperuse,
    cert.sexemption,
    cert.nimagenum,
    cert.sdirind,
    cert.nway_pay,
    VPago.sdescript ViaPago,
    cert.nbill_day DiaPago,
    cert.nsendaddr,
    cert.saut_guarval,
    cert.nsellchannel,
    CVent.sdescript CanalVenta,
    cert.dcollsus_ini,
    cert.dfer,
    cert.dcollsus_end,
    cert.ndays_quot,
    cert.nsus_reason,
    cert.npol_quot,
    cert.ssus_origi,
    cert.ddate_accept,
    cert.sanulletter,
    cert.sbill_ind,
    cert.srefundprem,
    cert.nstatquota,
    cert.spendinfo,
    cert.nrenewalnum,
    cert.ndigit,
    cert.nprop_reg,
    cert.nday_pay,
    cert.nduration as CantMesesPoliza,
    cert.nafp_commiss,
    cert.nafp_comm_curr,
    cert.norigin,
    cert.ncollector,
    cert.sfracreceip,
    cert.ngroup_agree,
    cert.nmailingpref,
    cert.sretarif,
    cert.dlast_tarif,
    cert.soperation,
    cert.dtariffdate,
    cert.drecepint,
    cert.drecepint_comp,
    cert.drecepinsu,
    cert.drecepinsu_comp,
    cert.sapplycostfp,
    cert.sdetailed_entry_printed,
    cert.dsald_date,
    cert.nrate_base,
    cert.nfolio,
    cert.sfacultativ,
    cert.sofficialpol,
    cert.sofficialcer,
    cert.nsus_office,
    cert.ncod_agree,
    cert.ntypeexc,
    cert.sfilenumber,
    cert.nsystem,
    cert.ncoveragecertificate,
    cert.nstatuscoveragecertificate,
    cert.driskaccepted,
    cert.srectype,
    cert.sind_multiannual,
    cert.ndepreciationtable,
    cert.npromissory_note,
    cert.nphoneid,
    cert.naddressid,
    cert.sind_ifi,
    cert.nextraday,
    cert.npolicy_transfer,
    cert.ncertif_transfer,
    cert.scodbranch_transfer,
    cert.nformpay,
    cert.scontrol,
    cert.dprevius_expirdate,
    cert.sindqsamevalue,
    cert.ncertif_associated,
    cert.npolicy_associated,
    cert.noffice_associated,
    cert.nofficeagen_associated,
    cert.nagency_associated,
    cert.nbranch_associated,
    cert.nproduct_associated,
    cert.nnotcancelday,
    cert.sclientsponsor,
    cert.scomerproduct,
    cert.ncombpolicy,
    cert.ncamp_release,
    cert.ncampaign,
    cert.sexcep_random,
    cert.nspeci_random,
    cert.dsuggestedstart,
    cert.sisugstart,
    cert.sprevpolnum
FROM
    certificat cert
INNER JOIN Table5632 TipoCert on cert.Scertype= TipoCert.Scertype
INNER JOIN Table10 Ramo on cert.Nbranch  = ramo.nbranch
INNER JOIN Table36 Fpago on cert.npayfreq = fpago.npayfreq
INNER JOIN PRODMaster Prod on cert.nproduct= prod.nproduct
INNER JOIN Table181 EstPol on cert.sstatusva= estpol.sstatusva
INNER JOIN Table5002  VPago on cert.nway_pay= VPago.nway_pay
INNER JOIN Table5532 CVent on cert.nsellchannel= cvent.nsellchannel
LEFT JOIN CLIENT cli on cert.sclient= cli.sclient
LEFT JOIN CLIENT Usr on cert.nusercode= Usr.sclient
WHERE cert.npolicy=1485 and cert.scertype=2  and cert.nbranch=5 and cert.nproduct=700