SELECT 
  UCASH.NUSER AS COD_USUARIO
  ,UCASH.NCASHNUM AS NRO_CAJA
  ,US.SCLIENT AS COD_CLIENTE
  ,CAJ.SCLIENAME AS CAJERO
  ,SUP.SCLIENAME  AS SUPERVISOR
  , TRIM(TCAJ.SDESCRIPT) AS TIPO_CAJA
  , CASE WHEN UCASH.SSTATUS = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END ESTADO
  , TRIM(AGEN.SDESCRIPT) AS AGENCIA
  , CASE CACC.NACC_CASH
        WHEN  9999 THEN 'CHEQUES'
        WHEN  9997 THEN 'CHEQUES A FECHA'
        WHEN  9998 THEN 'EFECTIVO'
        WHEN  9996 THEN 'TARJETA CREDITO/DEBITO'
        WHEN  9995 THEN 'OTRAS FORMA DE PAGO'       
        ELSE NULL
    END CUENTA
  , TRIM(MON.SDESCRIPT) MONEDA_CUENTA
  , TRIM(TCTA.SDESCRIPT) TIPO_CAJA_CUENTA 
  , TRIM(OFI.SDESCRIPT) OFICINA_CUENTA     
FROM USER_CASHNUM UCASH
INNER JOIN USERS US ON UCASH.NUSER = US.NUSERCODE
INNER JOIN CLIENT CAJ ON US.SCLIENT = CAJ.SCLIENT
LEFT JOIN USERS USUP ON UCASH.NCASHSUP = USUP.NUSERCODE
LEFT JOIN CLIENT SUP ON USUP.SCLIENT = SUP.SCLIENT
LEFT JOIN TABLE179 TCAJ ON UCASH.NTYPECASH = TCAJ.NTYPECASH
LEFT JOIN TABLE5556 AGEN ON UCASH.NOFFICEAGEN = AGEN.NOFFICEAGEN
LEFT JOIN CASH_ACC CACC ON UCASH.NCASHNUM = CACC.NCASHNUM
LEFT JOIN TABLE11 MON ON CACC.NCURRENCY = MON.NCODIGINT
LEFT JOIN TABLE179 TCTA ON CACC.NTYPECASH = TCTA.NTYPECASH
LEFT JOIN TABLE9 OFI ON CACC.NOFFICE = OFI.NOFFICE
ORDER BY UCASH.NUSER, UCASH.NCASHNUM 