CREATE OR REPLACE PROCEDURE INSUDB.REA_TMPS_UPONSOFT (
	SPROCESS		VARCHAR2,
	SKEY			TMP_CAL503.SKEY%TYPE,
    RC1            	OUT SYS_REFCURSOR ) AUTHID CURRENT_USER AS

    NIT_EMPRESA     CLIDOCUMENTS.SCLINUMDOCU%TYPE;
    RUT_EMPRESA     CLIENT.SCLIENT%TYPE;
    SSELEMPRESA     VARCHAR2(32767);
    SSEL            VARCHAR2(32767) := 'SELECT TRIM(UPPER(SQUERY)) FROM MASTERSHEET WHERE NSHEET = ';
    SSEL_CAL503     VARCHAR2(32767) := 'T.SKEY,T.ID_REGISTRO,T.NBRANCH COD_RAMO_CIA,T.SDESC_BRANCH RAMO_CIA,T.NACCCRITERION COD_PRODUCCION,T.SDESC_TYPE_HIST PRODUCCION,T.NOFFICE COD_REGIONAL,T.SDESCOFFICE REGIONAL,T.NCODLINEBUSI COD_LINEA_NEGOCIO,T.SDESC_LINEBUSI LINEA_NEGOCIO,T.NSELLCHANNEL COD_CANAL,T.SDESCSELLCHANNEL CANAL,CASE WHEN T.NTYPE_HIST IN (26, 44, 45) THEN ''SI'' ELSE ''NO'' END RENOVACION,T.NMONRENEW NRO_RENOV_MENSUAL,T.SNAMEHOLDER CONTRATANTE,T.NPAYFREQ COD_TIPO_POLIZA,T.SDESC_PAYFREQ TIPO_POLIZA,T.NPOLICY POLIZA,T.NNUMINSUR CANTIDAD_DE_ASEGURADOS,T.NCURRENCY COD_MONEDA_ORIGEN,T.SDESCCURRENCY MONEDA_ORIGEN,T.NCURRENCY_LOC COD_MONEDA_LOCAL,T.SDESCCURR_LOC MONEDA_LOCAL,T.NEXCHANGE TIPO_DE_CAMBIO,T.NNULLCODE COD_TIPO_DE_ANULACION,T.SDESC_NULLCODE TIPO_DE_ANULACION,T.NCAPITAL_MO CAPITAL_ASEGURADO_MO,T.NCAPITAL_LO CAPITAL_ASEGURADO_LO,T.SUSERNAME USUARIO_DE_EMISION,T.DISSUEDAT FECHA_EMISION,T.DSTARTDATE INICIO_VIGENCIA,T.DEXPIRDAT TERMINO_VIGENCIA,T.NPREMIUMA_MO PRIMA_NETA_MO,T.NPREMIUMA PRIMA_NETA_LO,T.NPREMIUMIVA_MO IVA_MO,T.NPREMIUMIVA IVA_LO,T.NMONTIT_MO IT_MO,T.NMONTIT_LO IT_LO,T.NMONTAPS_MO APS_MO,T.NMONTAPS_LO APS_LO,T.NRECARAD_MO RECARGOS_ADICIONALES_MO,T.NRECARAD_LO RECARGOS_ADICIONALES_LO,T.NSERVSUB_MO SERVICIOS_SUB_CONTRATADOS_MO,T.NSERVSUB_LO SERVICIOS_SUB_CONTRATADOS_LO,T.NADDPREMIUM_MO PRIMA_ADICIONAL_MO,T.NADDPREMIUM_LO PRIMA_ADICIONAL_LO,T.NDEFERREDPREM_MO PRIMA_NETA_DIFERIDA_MO,T.NDEFERREDPREM_LO PRIMA_NETA_DIFERIDA_LO,T.NADDDEFERPREM_MO PRIMA_ADICIONAL_DIFERIDA_MO,T.NADDDEFERPREM_LO PRIMA_ADICIONAL_DIFERIDA_LO,CASE WHEN NVL(T.NINTFINAN_MO, 0) = 0 THEN T.NPREMIUM_MO ELSE 0 END PRIMA_CONTADO_MO,CASE WHEN NVL(T.NINTFINAN_MO, 0) = 0 THEN T.NPREMIUM ELSE 0 END PRIMA_CONTADO_LO,T.NWAYPAY COD_FORMA_DE_PAGO,T.SDESC_WAY_PAY FORMA_DE_PAGO,T.NINTFINAN_MO INTERES_FINANCIERO_MO,T.NINTFINAN_LO INTERES_FINANCIERO_LO,T.NPREMIUM_MO PRIMA_TOTAL_MO,T.NPREMIUM PRIMA_TOTAL_LO,CASE WHEN T.NTYPE_TRAN IN (7, 8) THEN T.NPREMIUM_MO ELSE 0 END PRIMA_DEVOLVER_COBRAR_MO,' || 
                                       'CASE WHEN T.NTYPE_TRAN IN (7, 8) THEN T.NPREMIUM ELSE 0 END PRIMA_DEVOLVER_COBRAR_LO,T.NINTERTYP COD_TIPO_INTERMEDIARIO,T.SDESC_INTERTYP TIPO_INTERMEDIARIO,T.SCLIENT_AGEN COD_AGENTE_BROKER,T.SCLIENAME_AGE NOMBRE_AGENTE_BROKER,T.NINTCOMMPERC PORCENTAJE_COMISION_INTERM,T.NCOMAMOU_MO VALOR_COMISION_INTERM_MO,T.NCOMAMOU_PES VALOR_COMISION_INTERM_LO,T.SCLIENT_SUPER CODIGO_SUPERVISOR,T.SCLIENAME_SUPER NOMBRE_SUPERVISOR,T.NSUPCOMMPERC PORCENTAJE_COMISION_SUPER,T.NCOMAMOUSUP_MO VALOR_COMISION_SUPER_MO, T.NCOMAMOUSUP_LO VALOR_COMISION_SUPER_LO, T.DERPDATE FECHA_CONTABILIZACION_ERP,T.NTRANSACTIONERP NUM_ASIENTO_CONTABLE,T.SMESSAGEERP MENSAJE_ERP ' ||
                                       'FROM TMP_CAL503 T WHERE T.SKEY = ''' || REA_TMPS_UPONSOFT.SKEY || '''' || ' ORDER BY T.ID_REGISTRO';
    SSEL_GIL9209    VARCHAR2(32767) := 'ID_REGISTRO ID,NINSUR_AREA COD_TIPO_SEGURO,NMES MES_PROD,SDESINSUR_AREA TIPO_SEGURO,BRANCH_LED COD_RAMO_CONTABLE,SDESCBRANCH_LED RAMO_CONTABLE,NBRANCH COD_RAMO,SDESBRANCH RAMO,SCLIENAME_ASEG NOMBRE_CONTRATANTE,NMONTCEDE_MO CEDENTE_MO,NMONTCEDE_ML CEDENTE_LO,NPARTRIES_MO PARTICIPACION_RIESGO,NCOVER COD_COBERTURA,SDESCOVER COBERTURA,NSPECIALITY COD_ACTIVIDAD,SDESSPECIALITY ACTIVIDAD,NTAXRIES TASA_DE_RIESGO,SINSUREDMATTER MATERIA_ASEGURADA,SUBICRIES UBICACION_RIESGO,SCLIENT_ASEG NUMERO_DOCUMENTO,NPRODUCT COD_PRODUCTO,SDESPRODUCT PRODUCTO,NPOLICY NRO_POLIZA,NCAPITAL_MO CAPITAL_ASEGURADO_MO,NCAPITAL_ML CAPITAL_ASEGURADO_LO,DISSUEDAT FECHA_EMISION,DSTARTDATE INI_VIGENCIA,DEXPIRDAT FIN_VIGENCIA,NPREMNET_MO PRIMA_NETA_MO,NPREMNET_ML PRIMA_NETA_LO,NPREMSRV_MO PRIMA_SRV_MO,NPREMSRV_ML PRIMA_SRV_LO,NASISTENCIA_MO ASIST_VEHI_MO,NASISTENCIA_ML ASIST_VEHI_LO,NPARTES_MO PARTES_PIEZAS_MO,NPARTES_ML PARTES_PIEZAS_LO,NGESTIONCOB_MO GESTION_COBRANZA_MO,NGESTIONCOB_ML GESTION_COBRANZA_LO,NASESORIA_MO ASESORIA_MO,NASESORIA_ML ASESORIA_LO,NTOTSERCONTR_MO TOT_SERVICIOS_SUBCONTRA_MO,NTOTSERCONTR_ML TOT_SERVICIOS_SUBCONTRA_LO,NTOTSERADIC_MO TOT_SERVICIOS_ADIC_MO,NTOTSERADIC_ML TOT_SERVICIOS_ADIC_LO,NPREMMINDEP_MO PRIMA_MIN_DEPOSITO_MO,NPREMMINDEP_ML PRIMA_MIN_DEPOSITO_LO,NPREMDIFE_MO PRIMA_DIF_MO,NPREMDIFE_ML PRIMA_DIF_LO,NADDDEFERPREM_MO ADIC_DIF_MO,NADDDEFERPREM_ML ADIC_DIF_LO,NMONTIVA_MO IVA_MO,NMONTIVA_ML IVA_LO,NPREMCONT_MO PRIMA_CONTADO_MO,NPREMCONT_ML PRIMA_CONTADO_LO,NWAYPAY COD_FORMA_PAGO,SDESWAY_PAY FORMA_PAGO,NINTFINAN_MO INTERES_FINANC_MO,NINTFINAN_ML INTERES_FINANC_LO,NPREMTOT_MO PRIMA_TOT_MO,NPREMTOT_ML PRIMA_TOT_LO,SCLIENAME_INTER INTERMEDIARIO,NPORCOMIS PORC_COMISION,NMONTCOMIS_MO VALOR_COMISION_MO,NMONTCOMIS_ML VALOR_COMISION_LO,NSUMARET_MO SUM_RETENIDA_MO,NSUMARET_ML SUM_RETENIDA_LO,NSUMACEDCP_MO SUM_CED_CP_MO,NSUMACEDCP_ML SUM_CED_CP_LO,NSUMACEDEX_MO SUM_CED_EXCEDENTE_MO,NSUMACEDEX_ML SUM_CED_EXCEDENTE_LO,NSUMACED_MO TOT_SUMA_CED_MO, ' ||
                                       'NSUMACED_ML TOT_SUMA_CED_LO,NSUMAFACUL_MO SUM_FAC_MO,NSUMAFACUL_ML SUM_FAC_LO,NPORCRETEN_MO PORC_RETEN,NPORCEDCP_MO PORC_CED_CP,NPORCEDEXE_MO PORC_CED_EXCEDENTE,NPORCFACUL_MO PORC_FAC,NPREMRET_MO PRIMA_RET_MO,NPREMRET_ML PRIMA_RET_LO,NPREMCEDCP_MO PRIMA_CED_CP_MO,NPREMCEDCP_ML PRIMA_CED_CP_LO,NPREMCEDEXE_MO PRIMA_CED_EXCEDENTE_MO,NPREMCEDEXE_ML PRIMA_CED_EXCEDENTE_LO,NPRIMACEDREASEG_MO TOT_PRIMA_CED_MO,NPRIMACEDREASEG_ML TOT_PRIMA_CED_LO,NPREMFACUL_MO PRIMA_FAC_MO,NPREMFACUL_ML PRIMA_FAC_LO,NCOMCEDCP_MO COMISION_CED_CP_MO,NCOMCEDCP_ML COMISION_CED_CP_LO,NCOMCEDEXC_MO COMISION_CED_EXCEDENTE_MO,NCOMCEDEXC_ML COMISION_CED_EXCEDENTE_LO,NCOMIREASEG_MO TOT_COMISION_MO,NCOMIREASEG_ML TOT_COMISION_LO,NCOMFACUL_MO COMISION_FAC_MO,NCOMFACUL_ML COMISION_FAC_LO,NMONTIURE_MO IURE_MO,NMONTIURE_ML IURE_LO,SNAME_CONTRATO NOMBRE_CONTRATO,NOFFICE COD_SUCURSAL,SDESCOFFICE SUCURSAL,DCONTDATE INI_VIGENCIA_CONTRATO,DFINGESTDATE FIN_VIGENCIA_CONTRATO,NTRANSACTIO NUM_ANEXO,NPAYFREQ COD_TIPO,SDESPAYFREQ TIPO,'' '' VERIFICAR,NMONTIUREFAC_MO IURE_FAC_MO,NMONTIUREFAC_ML IURE_FAC_LO,SCLIENAME_ASEG NOMBRE_ASEGURADO,SCLIENAME_BENEF NOMBRE_BENEFICIARIO,NOFFICE COD_REGIONAL,SDESCOFFICE REGIONAL,NEXCHANGE TIPO_CAMBIO,NCODLINEBUSI COD_LINEA_NEGOCIO,SDESLINEBUSI LINEA_NEGOCIO,NCODREASEG COD_REASEGURADOR,SCLIENAME_REASEG REASEGURADOR,SNATIONALIND NACIONAL_EXTRANJERO,NSALDREASEG_MO SALDO_REASEGURADOR_MO,NSALDREASEG_ML SALDO_REASEGURADOR_LO,NSELLCHANNEL COD_CANAL,SDESCSELLCHANNEL CANAL,NCOMPANY NIT_EMPRESA,SCOMPANY EMPRESA,NID ID_REGISTRO,NCODTYPREASEG COD_TIPO_REASEGURO,SDESTYPREASEG TIPO_REASEGURO,SCLIENAME_REASEG NOMBRE_REASEGURADOR,NPRIMACEDREASEG_MO PRIMA_CEDIDA_MO,NPRIMACEDREASEG_ML PRIMA_CEDIDA_LO,NCOMIREASEG_MO COMISION_MO,NCOMIREASEG_ML COMISION_LO,NIURETREASEG_MO IURET_MO,NIURETREASEG_ML IURET_LO,NSALDOREASEG_MO SALDO_MO,NSALDOREASEG_ML SALDO_LO,'' '' DATOS_PB,TRUNC(DCOMPDATE) FECHA_PROCESO,NCURRENCY_ORI COD_MONEDA_ORIGEN,SDESCCURR_ORI MONEDA_ORIGEN' || 
                                       'FROM TMP_GIL9209 WHERE SKEY = ''' || REA_TMPS_UPONSOFT.SKEY || '''' || ' ORDER BY ID_REGISTRO';
    NSHEET          MASTERSHEET.NSHEET%TYPE;
    SQUERY          VARCHAR2(32767);
    SGRPORD         VARCHAR2(32767):= ' ';
    NERROR			T_ERR_INTERFACE.NERROR%TYPE;
    SERRORDESC		VARCHAR2(1024);
    L_CURSOR        SYS_REFCURSOR;

BEGIN

    BEGIN
        SELECT NVL(MAX(TRIM(CD.SCLINUMDOCU)), '1028483024'), 
               NVL(MAX(TRIM(CD.SCLIENT)), '00000000000116')
        INTO NIT_EMPRESA,
             RUT_EMPRESA
        FROM COMPANY CM,
             CLIDOCUMENTS CD
        WHERE CM.NCOMPANY = REAGENERALPKG.REAOPT_SYSTEM_COMPANY
        AND CM.SCLIENT = CD.SCLIENT;
    EXCEPTION
        WHEN OTHERS THEN
            NIT_EMPRESA := '1028483024';
            RUT_EMPRESA := '00000000000116';
    END;
    SSELEMPRESA := 'SELECT ''' || TRIM(NIT_EMPRESA) || ''' NIT_EMPRESA,''' || REAGENERALPKG.REANAMECLI(RUT_EMPRESA) || ''' NOM_EMPRESA,'; 

    CASE TRIM(SPROCESS)
        WHEN 'CAL503' THEN
            -- LIBRO PRODUCCIÓN
            SQUERY := SSELEMPRESA || SSEL_CAL503;
		WHEN 'CAL504' THEN 
            -- LIBRO RECAUDACIÓN
            NSHEET := 9306;
		WHEN 'CAL505' THEN 
            -- LIBRO DE CAJA EGRESOS
            NSHEET := 9457;
		WHEN 'CAL506' THEN 
            -- LIBRO DE CUENTA CORRIENTE CLIENTE
            NSHEET := 9314;
		WHEN 'GIL9202' THEN 
            -- REPORTE DE RESERVAS DE RIESGOS EN CURSO
            NSHEET := 9311;
		WHEN 'GIL9207' THEN 
            -- REPORTE DE PRIMAS POR COBRAR Y RESERVAS
            NSHEET := 9310;
		WHEN 'GIL9209' THEN 
            -- REPORTE DE RIESGOS ASEGURADOS GENERALES Y VIDA
            -- NSHEET := 9313;
            SQUERY := SSELEMPRESA || SSEL_GIL9209;
		WHEN 'GIL9216' THEN 
            -- REPORTE DE SINIESTROS
            NSHEET := 9216;
		WHEN 'SIL704' THEN 
            -- LIBRO SINIESTROS PENDIENTES
            NSHEET := 8234;
		WHEN 'SIL705' THEN 
            -- LIBRO SINIESTROS LIQUIDADOS
            NSHEET := 8235;
		ELSE NSHEET := NULL;
	END CASE;
    SSEL := SSEL || NSHEET;
    
    IF TRIM(SPROCESS) NOT IN ('CAL503', 'GIL9209') THEN

        OPEN L_CURSOR FOR SSEL;
        FETCH L_CURSOR INTO SQUERY;
        CLOSE L_CURSOR;
    
        SQUERY := REPLACE(SQUERY, '"SELECT', 'SELECT');
        IF TRIM(SPROCESS) = 'GIL9207' or TRIM(SPROCESS) = 'GIL9202' THEN
            SQUERY := REPLACE(SQUERY, 'SELECT', SSELEMPRESA);
        END IF;
        IF INSTR(SQUERY, ' GROUP ', 1) > 0 THEN
            SGRPORD := REPLACE(SUBSTR(SQUERY, INSTR(SQUERY, ' GROUP ', 1), LENGTH(SQUERY)), '"', ' ');
        ELSIF INSTR(SQUERY, ' ORDER ', 1) > 0 THEN    
            SGRPORD := REPLACE(SUBSTR(SQUERY, INSTR(SQUERY, ' ORDER ', 1), LENGTH(SQUERY)), '"', ' ');
        END IF;
        IF TRIM(SPROCESS) = 'GIL9202' THEN
            SQUERY := SUBSTR(SQUERY, 0, INSTR(SQUERY, 'WHERE', 1) + 5) || ' T.SKEY = ''' || SKEY || '''' || SGRPORD;
        ELSE
            SQUERY := SUBSTR(SQUERY, 0, INSTR(SQUERY, 'WHERE', 1) + 5) || ' SKEY = ''' || SKEY || '''' || SGRPORD;
        END IF;
    END IF;

    

    OPEN RC1 FOR SQUERY;

EXCEPTION
	WHEN OTHERS THEN
        NERROR      := SQLCODE;
        SERRORDESC  := SQLERRM || ' - ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
 CRETRACE2('REA_TMPS_UPONSOFT', 1318, SQUERY);
END REA_TMPS_UPONSOFT;
/