SELECT
   TRIM(TMED.SDESCRIPT) AS ID_ARANCEL
  ,TRIM(OFI.SDESCRIPT) AS REGIONAL
  ,TRIM(MNDA.SDESCRIPT) AS MONEDA
  ,TRIM(MF.SBENEFITCODE) AS PRESTACION
  ,TRIM(MB.SDESCRIPT) AS DESCRIPCION
  ,CAST(MF.NVALUE AS NUMBER(18,6)) AS VALOR
  ,MF.SHOMOLOG_BENEFIT AS CODIGO_HOMOLOGACION
FROM MEDICALFEES MF
INNER JOIN MEDICALBENEFITS MB ON MF.SBENEFITCODE = MB.SBENEFIT
INNER JOIN TAB_MEDICALFEES TMED ON MF.NIDMEDICALFEE = TMED.NIDMEDICALFEE
LEFT JOIN TABLE11 MNDA ON MF.ncurrency = MNDA.ncodigint
INNER JOIN TABLE9 OFI ON TMED.NOFFICE = OFI.NOFFICE  
WHERE TMED.SDESCRIPT LIKE '%AMV%'  
  AND MF.DEFFECDATE <= SYSDATE
  AND (MF.DNULLDATE IS NULL OR MF.DNULLDATE > SYSDATE)  
ORDER BY  MF.NIDMEDICALFEE , TMED.NOFFICE , MF.SBENEFITCODE