WITH cteDocCliente AS (
        SELECT
            cliDoc.SCLIENT,
            cliDoc.ntypclientdoc AS CODTIPODOCUMENTO,
            cliDoc.sclinumdocu AS NRODOCUMENTO,
            tdoc.sshort_des AS TIPODOCUMENTO,
            cliDoc.sidcompl AS COMPLEMENTO,
            ROW_NUMBER() OVER(PARTITION BY cliDoc.sclient ORDER BY clidoc.ntypclientdoc) as rn
        FROM CLIDOCUMENTS cliDoc
        INNER JOIN FORMATVALUES tdoc ON cliDoc.ntypclientdoc = tdoc.ntypclientdoc
        WHERE tdoc.NCLASSTYPDOC=2
    )
SELECT
   TMED.NIDMEDICALFEE
  ,TRIM(TMED.SDESCRIPT) AS ID_ARANCEL
  ,TRIM(OFI.SDESCRIPT) AS REGIONAL
  ,CPROV.SCLIENT AS COD_CLIENTE
  ,cteDoc.TIPODOCUMENTO
  ,cteDoc.NRODOCUMENTO
  ,TMED.NPROVIDER AS COD_PROVEEDOR 
  ,TRIM(CPROV.SCLIENAME) AS NOMBRE_PROVEEDOR 
  ,TRIM(MNDA.SDESCRIPT) AS MONEDA
  ,TRIM(MF.SBENEFITCODE) AS PRESTACION
  ,TRIM(MB.SDESCRIPT) AS DESCRIPCION
  ,CAST(MF.NVALUE AS NUMBER(18,6)) AS VALOR
  ,MF.SHOMOLOG_BENEFIT AS CODIGO_HOMOLOGACION    
  ,TRIM(T7027.SDESCRIPT) AS TIPO_PROVEEDOR  
  ,CASE  WHEN PROV.NJOINED = 1 THEN 'SI' ELSE 'NO' END AS ADSCRITO
FROM MEDICALFEES MF
INNER JOIN MEDICALBENEFITS MB ON MF.SBENEFITCODE = MB.SBENEFIT
INNER JOIN TAB_MEDICALFEES TMED ON MF.NIDMEDICALFEE = TMED.NIDMEDICALFEE
INNER JOIN TABLE9 OFI ON TMED.NOFFICE = OFI.NOFFICE
LEFT JOIN TAB_PROVIDER PROV ON TMED.NPROVIDER = PROV.NPROVIDER
LEFT JOIN TABLE7027 T7027 ON PROV.NTYPEPROV = T7027.NTYPEPROV
LEFT JOIN CLIENT CPROV ON PROV.SCLIENT = CPROV.SCLIENT
LEFT JOIN cteDocCliente cteDoc ON CPROV.SCLIENT = cteDoc.SCLIENT AND cteDoc.rn = 1
LEFT JOIN TABLE11 MNDA ON MF.ncurrency = MNDA.ncodigint
WHERE TMED.SDESCRIPT NOT LIKE '%AMV%'  
  AND PROV.NTYPEPROV IN (1,5) --INSTITUCIONES, MEDICO
  AND MF.DEFFECDATE <= SYSDATE
  AND (MF.DNULLDATE IS NULL OR MF.DNULLDATE > SYSDATE)  
ORDER BY  MF.NIDMEDICALFEE,TMED.NOFFICE  , MF.SBENEFITCODE