WITH cteDocCliente AS (
    SELECT
        cliDoc.SCLIENT,
        cliDoc.ntypclientdoc AS CODTIPODOCUMENTO,
        cliDoc.sclinumdocu AS NRODOCUMENTO,
        tdoc.sshort_des AS TIPODOCUMENTO,
        cliDoc.sidcompl AS COMPLEMENTO,
        ROW_NUMBER() OVER(PARTITION BY cliDoc.sclient ORDER BY clidoc.ntypclientdoc) as rn
    FROM CLIDOCUMENTS cliDoc
    INNER JOIN FORMATVALUES tdoc ON cliDoc.ntypclientdoc = tdoc.ntypclientdoc
    WHERE tdoc.NCLASSTYPDOC=2
), CTE_PROV_GRUPO AS (
SELECT PGR.NPROVIDER, TRIM(T642.SDESCRIPT)  ASOCIAR_GRUPO
 ,ROW_NUMBER() OVER(PARTITION BY PGR.NPROVIDER ORDER BY PGR.NPROVIDER DESC) as rn
FROM TAB_PROV_GROUP PGR
INNER JOIN TABLE642 T642 ON PGR.NPROV_GROUP = T642.NPROV_GROUP)
, CTE_PROV_ZONA AS (
SELECT PZN.NPROVIDER, TRIM(T9.SDESCRIPT)  ASOCIAR_CIUDAD
 ,ROW_NUMBER() OVER(PARTITION BY PZN.NPROVIDER ORDER BY PZN.NPROVIDER DESC) as rn
FROM TAB_PROV_ZONE PZN
INNER JOIN TABLE9 T9 ON PZN.NZONE = T9.NOFFICE)
, CTE_PROV_RAMO AS(
SELECT PBR.NPROVIDER, TRIM(T10.SDESCRIPT)  ASOCIAR_RAMO
 ,ROW_NUMBER() OVER(PARTITION BY PBR.NPROVIDER ORDER BY PBR.NPROVIDER DESC) as rn
FROM PROV_BRANCH PBR
INNER JOIN TABLE10 T10 ON PBR.NBRANCH = T10.NBRANCH)
SELECT
   CPROV.SCLIENT AS COD_CLIENTE
   ,TRIM(CPROV.SCLIENAME) AS NOMBRE_CLIENTE
   ,TMED.NPROVIDER AS COD_PROVEEDOR 
   ,TRIM(TMED.SDESCRIPT) AS NOMBRE_PROVEEDOR 
   ,TRIM(T9259.SDESCRIPT) AS CATEGORIA_PROVEEDOR
   ,TRIM(T7027.SDESCRIPT) AS TIPO_PROVEEDOR 
   ,TRIM(TSUB.SDESCRIPT) AS SUBTIPO_PROVEEDOR
   ,CASE  WHEN PROV.NJOINED = 1 THEN 'SI' ELSE 'NO' END AS ADSCRITO
   ,TRIM(T9252.SDESCRIPT) AS FORMA_PAGO
   ,PROV.DREGDATE AS FECHA_REGISTRO
   ,PROV.DINPDATE AS FECHA_INGRESO   
   ,CTEZ.ASOCIAR_CIUDAD 
   ,CTER.ASOCIAR_RAMO 
   ,CTEG.ASOCIAR_GRUPO   
   ,CASE WHEN PROV.SSTATREGT = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END ESTADO    
FROM TAB_PROVIDER PROV  
INNER JOIN TAB_MEDICALFEES TMED ON PROV.NPROVIDER = TMED.NPROVIDER
INNER JOIN TABLE9 OFI ON TMED.NOFFICE = OFI.NOFFICE
LEFT JOIN TABLE9259 T9259 ON PROV.NCATEG_PROV = T9259.NCATEG_PROV
LEFT JOIN TABLE7027 T7027 ON PROV.NTYPEPROV = T7027.NTYPEPROV
LEFT JOIN TAB_PROV_SUBTYPES TSUB ON PROV.NTYPEPROV = TSUB.NTYPEPROV AND PROV.NSUBTYPEPROV = TSUB.NSUBTYPEPROV
LEFT JOIN TABLE9252 T9252 ON PROV.NPAYMENT_METHOD = T9252.NPAYMENT_METHOD
LEFT JOIN CLIENT CPROV ON PROV.SCLIENT = CPROV.SCLIENT
LEFT JOIN cteDocCliente cteDoc ON CPROV.SCLIENT = cteDoc.SCLIENT AND cteDoc.rn = 1
LEFT JOIN CTE_PROV_GRUPO CTEG ON PROV.NPROVIDER= CTEG.NPROVIDER AND CTEG.RN=1
LEFT JOIN CTE_PROV_ZONA CTEZ ON PROV.NPROVIDER= CTEZ.NPROVIDER AND CTEZ.RN=1
LEFT JOIN CTE_PROV_RAMO CTER ON PROV.NPROVIDER= CTER.NPROVIDER AND CTER.RN=1
WHERE TMED.SDESCRIPT NOT LIKE '%AMV%'  
  AND PROV.NTYPEPROV IN (1,5) --INSTITUCIONES, MEDICO
ORDER BY TMED.NPROVIDER