SELECT
    TMED.NPROVIDER AS COD_PROVEEDOR 
   ,TRIM(CPROV.SCLIENAME) AS NOMBRE_PROVEEDOR
   ,TRIM(TMED.SDESCRIPT) AS NOMBRE_PROVEEDOR2 
   ,CASE  WHEN PROV.NJOINED = 1 THEN 'SI' ELSE 'NO' END AS ADSCRITO
   ,PROV.DREGDATE AS FECHA_REGISTRO
   ,PROV.DINPDATE AS FECHA_INGRESO     
   ,CASE WHEN PROV.SSTATREGT = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END ESTADO  
   ,PSFF.NPROVIDER_REL  
   ,(T9258.SDESCRIPT) AS ESTRUCTURA_SERVICIO
   ,CASE WHEN NVL(PSTAFF.SCLIENT,'')= '' THEN '' ELSE CSTAFF.SCLIENT || ' - ' || TRIM(CSTAFF.SCLIENAME) END AS CLIENTE
   ,CASE WHEN NVL(PSTAFF.SCLIENT,'')= '' THEN '' ELSE PSFF.NPROVIDER_REL || ' - ' || TRIM(CSTAFF.SCLIENAME) END AS PROVEEDOR_RELACIONADO
   ,PSTAFF.DINPDATE AS FECHA_INGRESO_STAFF  
FROM TAB_PROVIDER PROV  
INNER JOIN TAB_MEDICALFEES TMED ON PROV.NPROVIDER = TMED.NPROVIDER
LEFT JOIN CLIENT CPROV ON PROV.SCLIENT = CPROV.SCLIENT
LEFT JOIN TAB_PROV_STAFF PSFF ON PROV.NPROVIDER = PSFF.NPROVIDER
LEFT JOIN TAB_PROVIDER PSTAFF ON PSFF.NPROVIDER_REL = PSTAFF.NPROVIDER
LEFT JOIN TAB_MEDICALFEES MSTAFF ON PSTAFF.NPROVIDER = MSTAFF.NPROVIDER
LEFT JOIN CLIENT CSTAFF ON PSTAFF.SCLIENT = CSTAFF.SCLIENT
LEFT JOIN TABLE9258 T9258 ON PSFF.NSERV_ESTRUCT = T9258.NSERV_ESTRUCT
WHERE TMED.SDESCRIPT NOT LIKE '%AMV%'  
  AND PROV.NTYPEPROV IN (1,5) --INSTITUCIONES, MEDICO
  AND PSFF.NSERV_ESTRUCT = 1 -- EMERGENCISTAS
  --AND TMED.NPROVIDER= 3001
ORDER BY TMED.NPROVIDER