SELECT
CPROV.SCLIENT AS COD_CLIENTE
,TRIM(CPROV.SCLIENAME) AS NOMBRE_CLIENTE
,TMED.NPROVIDER AS COD_PROVEEDOR 
,TRIM(TMED.SDESCRIPT) AS NOMBRE_PROVEEDOR 
,TRIM(T9259.SDESCRIPT) AS CATEGORIA_PROVEEDOR
,TRIM(T7027.SDESCRIPT) AS TIPO_PROVEEDOR 
,TRIM(T9252.SDESCRIPT) AS FORMA_PAGO   
,TRIM(T7.SDESCRIPT) BANCO
,CLEANSTRING(EXTENCRYPTION.DECRYPTDATA(CTA.SACCOUNT)) NRO_CUENTA
,TRIM(T190.SDESCRIPT) TIPO_CUENTA    
,CASE WHEN CTA.SSTATREGT = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END ESTADO_CUENTA
,TRIM(T11.SDESCRIPT) MONEDA_CUENTA
,CASE WHEN CTA.SDEPOSIT = 1 THEN 'SI' ELSE 'NO' END DEPOSITO
,CASE WHEN NVL(CTIT.SCLIENT,'')= '' THEN '' ELSE  CTIT.SCLIENT ||'-'|| TRIM(CTIT.SCLIENAME)END AS TITULAR_BANCA
FROM TAB_PROVIDER PROV  
INNER JOIN TAB_MEDICALFEES TMED ON PROV.NPROVIDER = TMED.NPROVIDER
INNER JOIN TABLE9 OFI ON TMED.NOFFICE = OFI.NOFFICE
LEFT JOIN TABLE9259 T9259 ON PROV.NCATEG_PROV = T9259.NCATEG_PROV
LEFT JOIN TABLE7027 T7027 ON PROV.NTYPEPROV = T7027.NTYPEPROV
LEFT JOIN TABLE9252 T9252 ON PROV.NPAYMENT_METHOD = T9252.NPAYMENT_METHOD
LEFT JOIN CLIENT CPROV ON PROV.SCLIENT = CPROV.SCLIENT
LEFT JOIN TAB_PROV_BKACCOUNT CTA ON PROV.NPROVIDER = CTA.NPROVIDER
LEFT JOIN TABLE7 T7 ON CTA.NBANKEXT = T7.NBANK_CODE
LEFT JOIN TABLE190 T190 ON CTA.NTYP_ACC = T190.NACC_TYPE
LEFT JOIN TABLE11 T11 ON CTA.NCURRENCY = T11.NCODIGINT
LEFT JOIN CLIENT CTIT ON CTA.SCLIENTR = CTIT.SCLIENT
WHERE TMED.SDESCRIPT NOT LIKE '%AMV%'  
AND PROV.NTYPEPROV IN (1,5) --INSTITUCIONES, MEDICO
--  AND TMED.NPROVIDER =3001
ORDER BY TMED.NPROVIDER