WITH CTE_DOCUMENTO AS (
SELECT DOC.SCLIENT  
, DOC.SCLINUMDOCU AS NRO_DOCUMENTO
, TRIM(TDOC.SDESCRIPT) AS TIPO_DOCUMENTO
FROM CLIDOCUMENTS DOC
INNER JOIN FORMATVALUES TDOC ON DOC.NTYPCLIENTDOC= TDOC.NTYPCLIENTDOC AND DOC.NCLASSTYPDOC= TDOC.NCLASSTYPDOC
)
,CTE_DIRECCIONPARTICULAR AS (
SELECT  
 DIRPAR.SCLIENT
,TRIM(T66.SDESCRIPT) AS PAIS
, TRIM(DPTO.SDESCRIPT) AS DEPARTAMENTO
, TRIM(PROV.SDESCRIPT) AS PROVINCIA
, TRIM(MUN.SDESCRIPT) AS MUNICIPIO
, DIRPAR.SE_MAIL AS EMAIL
, TRIM(T564.SDESCRIPT) AS TIPO_TELEFONO
,TEL.SPHONE AS NUMERO
FROM ADDRESS DIRPAR
LEFT JOIN TABLE66 T66 ON DIRPAR.NCOUNTRY = T66.NCOUNTRY -- PAIS
LEFT JOIN PROVINCE DPTO ON DIRPAR.NPROVINCE = DPTO.NPROVINCE -- DEPARTAMENTO
LEFT JOIN TAB_LOCAT PROV ON DIRPAR.NLOCAL = PROV.NLOCAL -- PROVINCIA
LEFT JOIN MUNICIPALITY MUN ON DIRPAR.NMUNICIPALITY = MUN.NMUNICIPALITY -- MUNICIPIO
LEFT JOIN PHONES TEL ON DIRPAR.SKEYADDRESS = TEL.SKEYADDRESS
LEFT JOIN TABLE564 T564 ON TEL.NPHONE_TYPE = T564.NPHONE_TYPE
WHERE DIRPAR.SRECTYPE = 2 -- direccion particular
AND DIRPAR.SCERTYPE IS NULL -- NO ESTA RELACIONADA CON POLIZA, PROPIA DEL CLIENTE
)
SELECT  
 CL.sclient COD_CLIENTE
, TPer.sdescript TIPO_PERSONA  
, INITCAP(LOWER(RTRIM(CL.sCliename))) AS NOMBRE_COMPLETO 
, TRIM(DOC.TIPO_DOCUMENTO) AS TIPO_DOCUMENTO
, DOC.NRO_DOCUMENTO AS NRO_DOCUMENTO
, CL.dinpdate As FECHA_INGRESO
, DPART.PAIS
, DPART.DEPARTAMENTO
, DPART.PROVINCIA
, DPART.MUNICIPIO
, DPART.EMAIL
, DPART.TIPO_TELEFONO
, DPART.NUMERO
, CL.dcompdate As FechaModificacion
, clicre.scliename As UsuarioModificacion
FROM CLIENT CL 
LEFT JOIN Table5006 TPer On CL.nperson_typ= tper.nperson_typ
LEFT JOIN CTE_DIRECCIONPARTICULAR DPART ON CL.SCLIENT = DPART.SCLIENT
LEFT JOIN CTE_DOCUMENTO DOC ON CL.SCLIENT = DOC.SCLIENT
LEFT JOIN USERS usrCre ON CL.NUSERCODE= usrCre.NUSERCODE
LEFT JOIN CLIENT cliCre On usrCre.SClient= cliCre.SClient  
--WHERE CL.SCLIENT=  '00000000000010' --'00000000027988'
ORDER BY CL.SCLIENT