SELECT
  MB.STYPEBENEFIT AS GRUPO_PRESTACION
  ,TRIM(GAMV.STYPEBENEFIT) || '-'|| TRIM(GAMV.SDESCRIPT) AS TITULO_PRESTACION
  ,MB.SBENEFITCLAS AS SCOD_SUBGRUPO
  ,TRIM(GSUB.SDESCRIPT) AS SSUBGRUPO  
  , MB.SBENEFIT
  ,TRIM(MB.SDESCRIPT) AS PRESTACION
  ,TRIM(MB.SSHORT_DES) AS DESCRIPCION_BREVE
  , CASE WHEN MB.SSTATREGT = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END ESTADO
FROM MEDICALBENEFITS MB 
--INNER JOIN MEDICALFEES MF ON MB.SBENEFIT = MF.SBENEFITCODE
INNER JOIN TABLE8600 GAMV ON MB.STYPEBENEFIT = GAMV.STYPEBENEFIT 
INNER JOIN TABLE8601 GSUB ON MB.SBENEFITCLAS = GSUB.SBENEFITCLAS
--WHERE MB.SBENEFITCLAS = '1010'
ORDER BY MB.STYPEBENEFIT, MB.SBENEFIT