SELECT
 SILL_OMS AS CODIGO_OMS
, UPPER(TRIM(REAGENERALPKG.REACODIGINT('TABLE8602', 'SGROUP_ILL', NULL, SILL_OMS))) GRUPO_OMS 
, SILLNESS COD_PATOLOGIA
, UPPER(TRIM(SDESCRIPT)) DESCRIPCION_PATOLOGIA
, CASE WHEN SSTATREGT = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS ESTADO
, CASE WHEN NVL(SIND_SEVERITY, '2') = 1 THEN 'SI' ELSE 'NO' END AS SIND_SEVERITY
, CASE WHEN NVL(SIND_FRECUENCY, '2') = 1 THEN 'SI' ELSE 'NO' END AS SIND_FRECUENCY 
FROM TAB_AM_ILL
--WHERE SILL_OMS = 'L83'
ORDER BY SILL_OMS