DROP TABLE TIMETMP.TMP_INT511TIMETMP.TMP_INT511 CASCADE CONSTRAINTS;

CREATE TABLE TIMETMP.TMP_INT511
(
  SKEY                       VARCHAR2(20 CHAR)		,
  SCERTYPE            		 VARCHAR2(1 CHAR)		,
  NBRANCH                    NUMBER(5)				,     	--- COD. RAMO
  NPRODUCT                   NUMBER(10)				,    	--- COD. PRODUCTO
  NPOLICY                    NUMBER(10)				,    	--- NRO. POLIZA
  SDESPAYFREQ                VARCHAR2(50 CHAR)		, 		--- DESC. FRECUENCIA DE PAGO
  NRECEIPT                   VARCHAR2(500 CHAR)     ,
  SDESCOMPANY                VARCHAR2(60 CHAR)		, 		--- NOMBRE COMPAÑIA
  SDESNITCOMPANY             VARCHAR2(30 CHAR)		, 		--- NIT COMPAÑIA
  SDESBRANCHT                VARCHAR2(30 CHAR)		, 		--- LINEA DE NEGOCIO
  NSELLCHANNEL               NUMBER(5)				,     	--- COD CANAL VENTA
  SDESSELLCHANNEL            VARCHAR2(30 CHAR)		, 		--- DESC. CANAL VENTA
  SDESBRANCH                 VARCHAR2(30 CHAR)		, 		--- RAMO
  SDESPRODUCT                VARCHAR2(100 CHAR)		, 		--- DESC. PRODUCTO  
  SDESWAY_PAY                VARCHAR2(100 CHAR)		,		--- DESC. CANAL COBRO ASIGNADO  
  NOFFICE                    NUMBER(5)				,     	--- COD. REGIONAL POLIZA
  SDESOFFICE                 VARCHAR2(30 CHAR)		, 		--- DESC. REGIONAL POLIZA
  NOFFICE_TRAN               NUMBER(5)				,     	--- COD. REGIONAL COBRO
  SDESOFFICE_TRAN            VARCHAR2(30 CHAR)		, 		--- DESC. REGIONAL DE COBRO
  SCLIENT_C                  VARCHAR2(20 CHAR)		, 		--- COD. CAJERO
  SCLIENAME_C                VARCHAR2(100 CHAR)		, 		--- NOMBRE CAJERO
  SDESSPAY_FORM              VARCHAR2(100 CHAR)		, 		--- DESC. FORMA COBRO REALIZADO
  DCOLLECT                   DATE					,   	--- FECHA DE COBRO
  SCLIENT_BILL               VARCHAR2(100 CHAR)		, 		--- CLIENTE
  SDESTRATYPEI               VARCHAR2(100 CHAR)		,		--- DESC. TIPO DE CUOTA
  NPERIOD           		 VARCHAR2(500 CHAR)		,		--- NRO. CUOTA
  DLIMITDATE 				 DATE					,		--- FECHA VENCIMIENTO
  SDECBILLNUM				 VARCHAR2(30 CHAR)		, 		--- DESC. TIPO DE DOCUMENTO
  NBILLNUM                   NUMBER(20)				,		--- NRO. FACTURA O RECIBO
  SDESMOVTYPE				 VARCHAR2(100 CHAR)		,		--- DESC. FORMA DE COBRO REALIZADO
  NBORDEREAUX                NUMBER(20)				,		--- NRO. RELACION 
  SDESCONCEPT				 VARCHAR2(100 CHAR)		,		--- CONCEPTO
  SDESPAYFREQ_AUX            VARCHAR2(30 CHAR)		, 		--- PERIODICIDAD
  SDESBANK				 	 VARCHAR2(100 CHAR)		,		--- DESC. BANCO
  SACC_NUMBER				 VARCHAR2(100 CHAR)		,		--- NRO. CUENTA
  SDEP_NUMBER                VARCHAR2(50 CHAR)		,		--- COD. TRANSACCION
  SDOCNUMBE					 VARCHAR2(30 CHAR)		,		--- NRO. DE CHEQUE
  DDOC_DATE					 DATE					,
  SDESCARDADMIN				 VARCHAR2(100 CHAR)		,		--- DESC. ADMINISTRADORA DE TARJETA
  SCARD						 VARCHAR2(30 CHAR),	--- NRO. DE TARJETA
  SCURRENCY					 VARCHAR2(30 CHAR), -- MONEDA POLIZA
  NPREMIUM_MO                NUMBER(18,6),  -- IMPORTE POR COBRAR MONEDA ORIGEN
  NPREMIUM_LO                NUMBER(18,6),  -- IMPORTE POR COBRAR MONEDA LOCAL
  NAMOUNT_MO				 NUMBER(18,6),  -- IMPORTE RECIBIDO MONEDA ORIGEN
  NAMOUNT_LO                 NUMBER(18,6),  -- IMPORTE RECIBIDO MONEDA LOCAL
  NBALANCE_MO				 NUMBER(18,6),  -- SALDO A FAVOR MONEDA ORIGEN
  NBALANCE_LO				 NUMBER(18,6),  -- SALDO A FAVOR MONEDA LOCAL
  NBALANCE_AUX_MO			 NUMBER(18,6),  -- REGULARIZACION DE SALDO MONEDA ORIGEN
  NBALANCE_AUX_LO			 NUMBER(18,6),  -- REGULARIZACION DE SALDO MONEDA LOCAL
  NEXCHANGE					 NUMBER(18,6),	--- TIPO DE CAMBIO
  NINTERTYP					 NUMBER(5),		--- COD. TIPO INTERMEDIARIO
  SDESINTERTYP			     VARCHAR2(30 CHAR),	--- DESC. TIPO INTERMEDIARIO
  NINTERMED					 NUMBER(15),		--- COD.  INTERMEDIARIO
  SDESINTERMED				 VARCHAR2(100 CHAR),	--- NOMBRE INTERMEDIARIO
  NTYPE         			 NUMBER(5),		--- NTYPE
  NCURRENCY_TRA				 NUMBER(10),     --- COD. MONEDA TRANSACCION
  SCURRENCY_TRA				 VARCHAR2(40 CHAR), --- MONEDA TRANSACCION
  SDESSTATUS_PRE             VARCHAR2(100 CHAR), --- ESTADO DE RECIBO
  DBILLDATE				     DATE, 			--- FECHA FACTURA RECIBO
  NBILLNUM_OLD               NUMBER(20),	--- NRO. FACTURA ANTERIOR
  SCURRENCY_OLD				 VARCHAR2(40 CHAR), --- MONEDA TRANSACCION ANTERIOR
  DNULLDATE                  DATE, 
  SPECIAL_IDENT              VARCHAR2(50 CHAR),
  NCERTIF                    NUMBER(5),             --- NRO. DE CERTIFICADO
  SBILLTYP                   VARCHAR2(30 CHAR),          
  SCOLINVOT                  VARCHAR2(100 CHAR),	--- TIPO FACTURA COLECTIVO
  STYPDIS_PAYPERCEN          VARCHAR2(100 CHAR)	     --- TIPO DISTRIBUCION
)
TABLESPACE DATA1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE TIMETMP.TMP_INT511 IS 'Tabla temporal para almacenar los datos requeridos para la exportación de inforamción referente al Control de Ingreso de cobranzas';

COMMENT ON COLUMN TIMETMP.TMP_INT511.SPECIAL_IDENT IS 'Indicador de gestion interna. // Internal management indicator..';

COMMENT ON COLUMN TIMETMP.TMP_INT511.NCERTIF IS 'Número de certificado';

COMMENT ON COLUMN TIMETMP.TMP_INT511.DNULLDATE IS 'Fecha de anulación';

COMMENT ON COLUMN TIMETMP.TMP_INT511.SBILLTYP IS 'Tipo de factura (F: Factura; FA: Factura anticipada;CF:Cambio de factura)';


CREATE OR REPLACE PUBLIC SYNONYM TMP_INT511 FOR TIMETMP.TMP_INT511;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON TIMETMP.TMP_INT511 TO INSUDB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON TIMETMP.TMP_INT511 TO INSUDBGEN;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON TIMETMP.TMP_INT511 TO VTAPPS;
