-- Script para insertar en TIMETMP.TMP_INT515
-- Basado en inferencias de comentarios y patrón de INSERT_TMP_INT514.sql
-- Usando TAB_PROVIDER como tabla origen principal, unida con TAB_PROV_MEDSPEC, TAB_PROV_GROUP, TABLE9
-- Nota: TAB_PROVIDER no tiene DEFFECDATE ni DNULLDATE según consultas_existentes.md; se usa DOUTDATE como fecha de nulidad
-- Descripciones obtenidas vía REAGENERALPKG.REACODIGINT según consultas_existentes.md

INSERT INTO TIMETMP.TMP_INT515 (
  SKEY,
  SCOR_TIPO_PROVEEDOR,
  STIPO_PROVEEDOR,
  SNOMBRE_PROVEEDOR,
  SESPECIALIDAD_CATEGORIA,
  SCLIENT,
  SNIT,
  SREGIONAL,
  SCIUDAD,
  SESTADO,
  SGRUPO,
  NTARIFA,
  NFACTOR_DESCUENTO,
  NFACTOR_INCREMENTO,
  NVALOR_UMA_LO,
  NPLAN_HABILITADO,
  SSUSCRIPTOR,
  SMODALIDAD_PAGO,
  SEXCEPCIONES
)
WITH TBLDOCUMENTO AS (
    SELECT  CDOC.SCLIENT AS SCLIENT,
        T6023.sdescript AS TIPO_DOCUMENTO,
        FVAL.sdescript AS SUBTIPO_DOCUMENTO,
        CDOC.SCLINUMDOCU AS NRO_DOCUMENTO,
        ROW_NUMBER() OVER(PARTITION BY CDOC.SCLIENT ORDER BY CDOC.DCOMPDATE DESC)  as rn   
    FROM CLIDOCUMENTS CDOC 
    INNER JOIN TABLE6023 T6023 ON CDOC.NCLASSTYPDOC = T6023.NCLASSTYPDOC
    INNER JOIN FORMATVALUES FVAL ON CDOC.NTYPCLIENTDOC = FVAL.NTYPCLIENTDOC 
    WHERE CDOC.NCLASSTYPDOC IN (2) AND CDOC.NTYPCLIENTDOC IN (3) 
),
TBLPRESTACIONES AS (
    SELECT TMED.NPROVIDER,
         LISTAGG(DISTINCT  TRIM(GAMV.STYPEBENEFIT) || ' ' || TRIM(GAMV.SDESCRIPT), ', ') 
            WITHIN GROUP (ORDER BY GAMV.STYPEBENEFIT ) 
            AS GRUPOS_ASIGNADOS
    FROM MEDICALFEES MF
    INNER JOIN MEDICALBENEFITS MB ON MF.SBENEFITCODE = MB.SBENEFIT
    INNER JOIN TAB_MEDICALFEES TMED ON MF.NIDMEDICALFEE = TMED.NIDMEDICALFEE 
    INNER JOIN TABLE8600 GAMV ON MB.STYPEBENEFIT = GAMV.STYPEBENEFIT 
    --WHERE TMED.SDESCRIPT LIKE '%AMV%'  
    GROUP BY TMED.NPROVIDER
)
WITH TBLDOCUMENTO AS (
    SELECT  CDOC.SCLIENT AS SCLIENT,
        T6023.sdescript AS TIPO_DOCUMENTO,
        FVAL.sdescript AS SUBTIPO_DOCUMENTO,
        CDOC.SCLINUMDOCU AS NRO_DOCUMENTO,
        ROW_NUMBER() OVER(PARTITION BY CDOC.SCLIENT ORDER BY CDOC.DCOMPDATE DESC)  as rn   
    FROM CLIDOCUMENTS CDOC 
    INNER JOIN TABLE6023 T6023 ON CDOC.NCLASSTYPDOC = T6023.NCLASSTYPDOC
    INNER JOIN FORMATVALUES FVAL ON CDOC.NTYPCLIENTDOC = FVAL.NTYPCLIENTDOC 
    WHERE CDOC.NCLASSTYPDOC IN (2) AND CDOC.NTYPCLIENTDOC IN (3) 
),
TBLPRESTACIONES AS (
    SELECT TMED.NPROVIDER,
         LISTAGG(DISTINCT  TRIM(GAMV.STYPEBENEFIT) || ' ' || TRIM(GAMV.SDESCRIPT), ', ') 
            WITHIN GROUP (ORDER BY GAMV.STYPEBENEFIT ) 
            AS GRUPOS_ASIGNADOS
    FROM MEDICALFEES MF
    INNER JOIN MEDICALBENEFITS MB ON MF.SBENEFITCODE = MB.SBENEFIT
    INNER JOIN TAB_MEDICALFEES TMED ON MF.NIDMEDICALFEE = TMED.NIDMEDICALFEE 
    INNER JOIN TABLE8600 GAMV ON MB.STYPEBENEFIT = GAMV.STYPEBENEFIT 
    --WHERE TMED.SDESCRIPT LIKE '%AMV%'  
    GROUP BY TMED.NPROVIDER
)
SELECT
  '515' AS SKEY,
  TP.NTYPEPROV AS SCOR_TIPO_PROVEEDOR,
  T7027.SDESCRIPT AS STIPO_PROVEEDOR,
  TRIM(C.SCLIENAME) AS SNOMBRE_PROVEEDOR ,
  CASE TP.NTYPEPROV
  WHEN 1 THEN TPS.SDESCRIPT
  ELSE T8603.SDESCRIPT     
  END AS SESPECIALIDAD_CATEGORIA,  
  TP.SCLIENT AS SCLIENT,                                              
  TBLD.NRO_DOCUMENTO AS SNIT,
  T9.SDESCRIPT AS SREGIONAL,
  T9.SDESCRIPT AS SCIUDAD,
  CASE WHEN (TP.DOUTDATE IS NOT NULL) THEN 'ACTIVO' ELSE 'INACTIVO' END  AS SESTADO,
  TBP.GRUPOS_ASIGNADOS AS SGRUPO,
  0 AS NTARIFA,
  0 AS NFACTOR_DESCUENTO,
  0 AS NFACTOR_INCREMENTO,
  0 AS NVALOR_UMA_LO,
  T642.SDESCRIPT AS NPLAN_HABILITADO,
  USCLI.USCLI.SCLIENAME AS SSUSCRIPTOR,
  T9252.SDESCRIPT AS SMODALIDAD_PAGO,
  'NO' AS SEXCEPCIONES
FROM TAB_PROVIDER TP
INNER JOIN CLIENT C ON TP.SCLIENT = C.SCLIENT
LEFT JOIN TAB_PROV_MEDSPEC TPM ON TP.NPROVIDER = TPM.NPROVIDER
LEFT JOIN TABLE8603 T8603 ON TPM.SMEDSPECIALIALTY = T8603.SMEDSPECIALIALTY
LEFT JOIN TAB_PROV_SUBTYPES TPS ON TP.NTYPEPROV = TPS.NTYPEPROV AND TP.NSUBTYPEPROV = TPS.NSUBTYPEPROV
INNER JOIN TBLDOCUMENTO TBLD ON C.SCLIENT = TBLD.SCLIENT AND TBLD.rn = 1
LEFT JOIN TBLPRESTACIONES TBP ON TP.NPROVIDER = TBP.NPROVIDER

LEFT JOIN TAB_PROV_GROUP TPG ON TP.NPROVIDER = TPG.NPROVIDER
LEFT JOIN TABLE9 T9 ON TP.NOFFICE = T9.NOFFICE
LEFT JOIN TABLE7027 T7027 ON TP.NTYPEPROV = T7027.NTYPEPROV
LEFT JOIN TABLE642 T642 ON TPG.NPROV_GROUP = T642.NPROV_GROUP
LEFT JOIN TABLE9252 T9252 ON TP.NPAYMENT_METHOD = T9252.NPAYMENT_METHOD 

LEFT JOIN USERS US ON TP.NUSERCODE = US.NUSERCODE
LEFT JOIN CLIENT USCLI ON US.SCLIENT = USCLI.SCLIENT 

WHERE (TP.DOUTDATE IS NULL OR TP.DOUTDATE > SYSDATE)
AND TP.SSTATREGT = 1-- REGISTRO ACTIVO
--and TP.NTYPEPROV in (5)
--AND TP.SCLIENT= '00000000006660'
ORDER BY TP.NPROVIDER;