DROP TABLE TIMETMP.TMP_INT515 CASCADE CONSTRAINTS;
CREATE TABLE TIMETMP.TMP_INT515 (
  SKEY VARCHAR2(20 CHAR) NOT NULL, -- VALOR DE LLAVE POR LO GENERAL, ES EL NUMERO DE LA TABLA DESDPUES DEL INT. EJEM 515
  SCOD_TIPO_PROVEEDOR VARCHAR2(20 CHAR) NOT NULL, -- CODIGO TIPO PROVEEDOR
  STIPO_PROVEEDOR VARCHAR2(300 CHAR) NULL, -- DESCRIPCION TIPO PROVEEDOR. EJM INSTITUCIONES.
  NCOD_PROVEEDOR NUMBER(5) NOT NULL, -- CODIGO DEL PROVEEDOR
  SNOMBRE_PROVEEDOR VARCHAR2(800 CHAR) NULL, -- NOMBRE DEL PROVEEDOR
  SESPECIALIDAD_CATEGORIA VARCHAR2(800 CHAR) NULL, -- DESCRIPCION ESPECIALIDAD O TIPO. EJM. ESPECIALIDAD: PEDIATRIA; TIPOSERVICIO: LABORATORIO
  SCLIENT VARCHAR2(30) NULL, -- CODIGO DE CLIENTE DEL PROVEEDOR
  SNIT VARCHAR2(30 CHAR) NULL, -- NIT DEL PROVEEDOR
  SREGIONAL VARCHAR2(50 CHAR) NULL, -- REGIONAL DE ATENCION DEL PROVEEDOR
  SCIUDAD VARCHAR2(50 CHAR) NULL, -- CIUDAD DE ATENCION DEL PROVEEDOR
  SESTADO VARCHAR2(20 CHAR) NULL, -- ESTADO ACTUAL DEL PROVEEDOR
  SGRUPO VARCHAR2(500 CHAR) NULL, -- DESCRIPCION DEL GRUPO DE LA PRESTACION. EJM. 10 - CONSULTAS
  NTARIFA NUMBER(10,5) NULL, -- VALOR CERO
  NFACTOR_DESCUENTO NUMBER(18,5) NULL, -- VALOR CERO
  NFACTOR_INCREMENTO NUMBER(18,5) NULL, -- VALOR CERO
  NVALOR_UMA_LO NUMBER(18,5) NULL, -- VALOR CERO
  NPLAN_HABILITADO VARCHAR2(200 CHAR) NULL, -- PLAN HABILITADO PARA EL PROVEEDOR. EJM. PRIMERA RED
  SSUSCRIPTOR VARCHAR2(200 CHAR) NULL, -- NOMBRE USUARIO QUE CREO AL PROVEEDOR
  SMODALIDAD_PAGO VARCHAR2(200 CHAR) NULL, -- MODALIDAD DE PAGO SELECCIONADA DEL PROVEEDOR
  SEXCEPCIONES VARCHAR2(20 CHAR) NULL -- SI O NO, SI TIENE CONFIGURADA ALGUNA EXCEPCION COLOCAR "SI" CASO CONTRARIO "NO"

);

CREATE OR REPLACE PUBLIC SYNONYM TMP_INT515 FOR TIMETMP.TMP_INT515;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT515 TO INSUDB;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT515 TO INSUDBGEN;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TIMETMP.TMP_INT515 TO VTAPPS;
