BEGIN

    DELETE MEDBENEFITS_PROD WHERE NPRODUCT = 4 AND NMODULEC <> 10;


    INSERT INTO MEDBENEFITS_PROD (NBRANCH, NPRODUCT, NMODULEC, DEFFECDATE, NCOVER, NROLE, NDED_TYPE, NQUANTITY, NAMOUNT_BENE, NPERCEN_HOSPITAL, NPERCEN_AMBULATORY, SCHANALLO, DNULLDATE, DCOMPDATE, NUSERCODE, SCAREN_TYPE, NCAREN_QUANT, NOFFICE_PROD, NAMOUNT_COPAY, NFRANCFIX, NAGESTART, NAGEEND, SSEXCLIEN, NPROVIDER, NATTENSYSTEM, NTYPEEXHAUS, SILLNESS, SCLARIFICACT, NINDPRINT, NBENEFCATEG, NIDMEDBENEF, SBENEFCATEG_CODE, SPRINT_DES, NORDER)
    SELECT NBRANCH, NPRODUCT, 20 AS NMODULEC, DEFFECDATE, NCOVER, NROLE, NDED_TYPE, NQUANTITY, NAMOUNT_BENE, NPERCEN_HOSPITAL, NPERCEN_AMBULATORY, SCHANALLO, DNULLDATE, SYSDATE AS DCOMPDATE, 1 AS NUSERCODE, SCAREN_TYPE, NCAREN_QUANT, NOFFICE_PROD, NAMOUNT_COPAY, NFRANCFIX, NAGESTART, NAGEEND, SSEXCLIEN, NPROVIDER, NATTENSYSTEM, NTYPEEXHAUS, SILLNESS, SCLARIFICACT, NINDPRINT, NBENEFCATEG, NIDMEDBENEF, SBENEFCATEG_CODE, SPRINT_DES, NORDER 
    FROM MEDBENEFITS_PROD 
    WHERE NPRODUCT = 4 AND NMODULEC = 10
    UNION
    SELECT NBRANCH, NPRODUCT, 30 AS NMODULEC, DEFFECDATE, NCOVER, NROLE, NDED_TYPE, NQUANTITY, NAMOUNT_BENE, NPERCEN_HOSPITAL, NPERCEN_AMBULATORY, SCHANALLO, DNULLDATE, SYSDATE AS DCOMPDATE, 1 AS NUSERCODE, SCAREN_TYPE, NCAREN_QUANT, NOFFICE_PROD, NAMOUNT_COPAY, NFRANCFIX, NAGESTART, NAGEEND, SSEXCLIEN, NPROVIDER, NATTENSYSTEM, NTYPEEXHAUS, SILLNESS, SCLARIFICACT, NINDPRINT, NBENEFCATEG, NIDMEDBENEF, SBENEFCATEG_CODE, SPRINT_DES, NORDER 
    FROM MEDBENEFITS_PROD 
    WHERE NPRODUCT = 4 AND NMODULEC = 10
    UNION
    SELECT NBRANCH, NPRODUCT, 40 AS NMODULEC, DEFFECDATE, NCOVER, NROLE, NDED_TYPE, NQUANTITY, NAMOUNT_BENE, NPERCEN_HOSPITAL, NPERCEN_AMBULATORY, SCHANALLO, DNULLDATE, SYSDATE AS DCOMPDATE, 1 AS NUSERCODE, SCAREN_TYPE, NCAREN_QUANT, NOFFICE_PROD, NAMOUNT_COPAY, NFRANCFIX, NAGESTART, NAGEEND, SSEXCLIEN, NPROVIDER, NATTENSYSTEM, NTYPEEXHAUS, SILLNESS, SCLARIFICACT, NINDPRINT, NBENEFCATEG, NIDMEDBENEF, SBENEFCATEG_CODE, SPRINT_DES, NORDER 
    FROM MEDBENEFITS_PROD 
    WHERE NPRODUCT = 4 AND NMODULEC = 10
    UNION
    SELECT NBRANCH, NPRODUCT, 60 AS NMODULEC, DEFFECDATE, NCOVER, NROLE, NDED_TYPE, NQUANTITY, NAMOUNT_BENE, NPERCEN_HOSPITAL, NPERCEN_AMBULATORY, SCHANALLO, DNULLDATE, SYSDATE AS DCOMPDATE, 1 AS NUSERCODE, SCAREN_TYPE, NCAREN_QUANT, NOFFICE_PROD, NAMOUNT_COPAY, NFRANCFIX, NAGESTART, NAGEEND, SSEXCLIEN, NPROVIDER, NATTENSYSTEM, NTYPEEXHAUS, SILLNESS, SCLARIFICACT, NINDPRINT, NBENEFCATEG, NIDMEDBENEF, SBENEFCATEG_CODE, SPRINT_DES, NORDER 
    FROM MEDBENEFITS_PROD 
    WHERE NPRODUCT = 4 AND NMODULEC = 10
    UNION
    SELECT NBRANCH, NPRODUCT, 70 AS NMODULEC, DEFFECDATE, NCOVER, NROLE, NDED_TYPE, NQUANTITY, NAMOUNT_BENE, NPERCEN_HOSPITAL, NPERCEN_AMBULATORY, SCHANALLO, DNULLDATE, SYSDATE AS DCOMPDATE, 1 AS NUSERCODE, SCAREN_TYPE, NCAREN_QUANT, NOFFICE_PROD, NAMOUNT_COPAY, NFRANCFIX, NAGESTART, NAGEEND, SSEXCLIEN, NPROVIDER, NATTENSYSTEM, NTYPEEXHAUS, SILLNESS, SCLARIFICACT, NINDPRINT, NBENEFCATEG, NIDMEDBENEF, SBENEFCATEG_CODE, SPRINT_DES, NORDER 
    FROM MEDBENEFITS_PROD 
    WHERE NPRODUCT = 4 AND NMODULEC = 10
    UNION
    SELECT NBRANCH, NPRODUCT, 80 AS NMODULEC, DEFFECDATE, NCOVER, NROLE, NDED_TYPE, NQUANTITY, NAMOUNT_BENE, NPERCEN_HOSPITAL, NPERCEN_AMBULATORY, SCHANALLO, DNULLDATE, SYSDATE AS DCOMPDATE, 1 AS NUSERCODE, SCAREN_TYPE, NCAREN_QUANT, NOFFICE_PROD, NAMOUNT_COPAY, NFRANCFIX, NAGESTART, NAGEEND, SSEXCLIEN, NPROVIDER, NATTENSYSTEM, NTYPEEXHAUS, SILLNESS, SCLARIFICACT, NINDPRINT, NBENEFCATEG, NIDMEDBENEF, SBENEFCATEG_CODE, SPRINT_DES, NORDER 
    FROM MEDBENEFITS_PROD 
    WHERE NPRODUCT = 4 AND NMODULEC = 10;
COMMIT;

END;