SELECT * FROM TABLE8602 ORDER BY DCOMPDATE DESC

--Insert into INSUDB.TABLE8602
--   (SGROUP_ILL, DCOMPDATE, SDESCRIPT, SSHORT_DES, SSTATREGT, 
--    NUSERCODE)
-- Values
--   ('NP35', TO_DATE('21/05/2026 19:18:49', 'DD/MM/YYYY HH24:MI:SS'), 'COMPLICACIONES POR CIRUGIA DECLARADAS DE APENDICITIS   ', 'CC DE APENDICITIS ', '1',1);
--
--Insert into INSUDB.TABLE8602
--   (SGROUP_ILL, DCOMPDATE, SDESCRIPT, SSHORT_DES, SSTATREGT, 
--    NUSERCODE)
-- Values
--   ('NP36', TO_DATE('21/05/2026 19:18:49', 'DD/MM/YYYY HH24:MI:SS'), 'COMPLICACIONES POR CIRUGIA DECLARADAS DE CESAREA ', 'CC DE CESAREA ', '1',1);
--COMMIT;