DECLARE
DEFFECDATE_AUX DATE;
BEGIN
    DEFFECDATE_AUX  := TO_DATE('31/12/2025', 'DD/MM/YYYY');

UPDATE CTROL_DATE CT -- TABLE526
   SET CT.DEFFECDATE        =   DEFFECDATE_AUX,
       CT.DCOMPDATE         =   SYSDATE
 WHERE CT.NTYPE_PROCE       IN(3, 201,211, 254);
         
         
UPDATE PREMIUM_MO PM
  SET SPROCESS_IND = '2',
      DPOSTED      = NULL,
      SINTERMEI     = '2';
              
                  
UPDATE UL_MOVE_ACC_POL 
  SET DPOSTED = NULL;
              
DELETE
FROM TMP_INT9529;                                

UPDATE DRAFT_HIST 
SET DPOSTED      = NULL,
   SINTERMEI    = '2';

 UPDATE MOVE_ACC
SET SPROCESS_IND = '2',
    DPOSTED      = NULL,
    SSCAB       = NULL,
    DDATE_SCAB  = NULL;

DELETE
FROM SCABCOMISIONES;

DELETE
FROM TMP_LRECAUDACION;

DELETE
FROM INSUDB.BATCH_PARAM_VALUE
WHERE SKEY IN (SELECT SKEY
                FROM INSUDB.BATCH_JOB
                WHERE NBATCH = 129);
    
DELETE
FROM INSUDB.BATCH_JOB
WHERE NBATCH = 129;

COMMIT;
END;    