DECLARE 
NSHEET_AUX NUMBER(10);
I NUMBER(10);

BEGIN

    FOR I IN 501..99999 LOOP
        NSHEET_AUX :=0;
			BEGIN
				SELECT I
				INTO NSHEET_AUX
				FROM DUAL
				WHERE NOT EXISTS ( SELECT 1
									FROM MASTERSHEET
									WHERE NSHEET= I);
			EXCEPTION
					WHEN NO_DATA_FOUND THEN
						NULL;
						CRETRACE2('NOT', 593, SQLERRM);
					WHEN OTHERS THEN
						NSHEET_AUX := 0;
						CRETRACE2('OTH', 593, SQLERRM);
			END;
			IF NSHEET_AUX > 0 THEN
				DELETE FROM TRACE WHERE NUSERCODE = 593;
				COMMIT;
				CRETRACE2('NSHEET_AUX', 593, NSHEET_AUX);
				EXIT;
			END IF;
    END LOOP;
    COMMIT;
 END;
 
 /*
  SELECT * FROM TRACE WHERE NUSERCODE = 593;
 */