SELECT
   
     M.NPRODUCT
    ,LC.NCOVERGEN
    ,TRIM(TL.SDESCRIPT) AS NOMBRE_COBERTURA
    , M.NMODULEC
    ,TRIM(TM.SDESCRIPT) AS MODULO_PLAN
    ,M.NATTENSYSTEM
    ,TRIM(T9215.SDESCRIPT) AS SISTEMA_ATENCION 
    , TRIM(BC.SDESCRIPT) AS CATEGORIA_BENEFICIO  
    , TRIM(GETDESCBENEFITS(M.nbranch,M.nproduct,M.nmodulec,M.deffecdate,M.NBENEFCATEG,M.SBENEFCATEG_CODE)) AS NOMBRE_BENEFICIO
    ,TRIM(M.SCLARIFICACT) AS "Aclaraciones"
    ,COALESCE(M.NAMOUNT_BENE, M.NQUANTITY) AS "Limite Hasta"
    ,CASE WHEN NVL(M.NDED_TYPE,0) <> 0 THEN (TRIM(T269.SDESCRIPT) || ' - '|| NVL(TO_CHAR(M.NFRANCFIX), '')  )
       ELSE 'NO'
    END AS DEDUCIBLE
    ,M.NPERCEN_HOSPITAL AS "Hospitalaria"
    ,M.NPERCEN_AMBULATORY AS "Ambulatoria"
    ,CASE
        WHEN M.SCAREN_TYPE IS NOT NULL THEN NVL(TO_CHAR(M.NCAREN_QUANT), '') || ' ' || TRIM(T52.SDESCRIPT)
        ELSE NULL
    END AS "Carencia"
    ,M.NBENEFCATEG
    ,M.SBENEFCATEG_CODE
    , M.*
FROM MEDBENEFITS_PROD M
INNER JOIN BENEFITS_CATEGORY BC ON M.NBENEFCATEG=BC.NBENEFCATEG
INNER JOIN LIFE_COVER LC ON M.NBRANCH= LC.NBRANCH AND M.NCOVER = LC.NCOVER AND M.NPRODUCT = LC.NPRODUCT AND M.NMODULEC= LC.NMODULEC
INNER JOIN TAB_LIFCOV TL ON LC.NCOVERGEN = TL.NCOVERGEN
LEFT JOIN TABLE269 T269 ON M.NDED_TYPE= T269.NDED_TYPE
LEFT JOIN TABLE52 T52 ON M.SCAREN_TYPE = T52.SCAREN_TYPE
LEFT JOIN TABLE9215 T9215 ON M.NATTENSYSTEM = T9215.NATTENSYSTEM
INNER JOIN TAB_MODUL TM ON M.NBRANCH = TM.NBRANCH AND M.NPRODUCT = TM.NPRODUCT AND M.NMODULEC = TM.NMODULEC
WHERE M.NPRODUCT = 1
 AND M.DNULLDATE IS NULL
 --AND LC.NCOVERGEN IN ,92190, 92191)
 AND M.SBENEFCATEG_CODE = '1010'
ORDER BY M.NMODULEC,LC.NCOVERGEN,6;