SELECT  
        COV.NPRODUCT,COV.NPOLICY,COV.NMODULEC        
        ,COV.NCOVER AS COD_COBERTURA
        ,TRIM(TL.SDESCRIPT) AS NOMBRE_COBERTURA
        ,COV.NROLE
        , TRIM(T12.SDESCRIPT) ROL
        ,COV.SCLIENT
        ,COV.DEFFECDATE, COV.NCAPITAL, COV.NRATECOVE
        , COV.NPREMIUM 
        , 'TARIFA' TITULO
        , TH.NAGE_INIT	EDAD
        , TH.DEFFECDATE, TH.NAMOUNTF, TH.NAMOUNTM
FROM COVER COV
INNER JOIN POLICY P ON COV.NPRODUCT= P.NPRODUCT AND COV.NPOLICY= P.NPOLICY 
INNER JOIN LIFE_COVER LC ON COV.NBRANCH= LC.NBRANCH AND COV.NPRODUCT= LC.NPRODUCT
                              AND COV.NCOVER= LC.NCOVER AND COV.NMODULEC= LC.NMODULEC
                              AND LC.DNULLDATE IS NULL
INNER JOIN TAB_LIFCOV TL ON LC.NCOVERGEN = TL.NCOVERGEN
INNER JOIN MODULES MD ON COV.NPRODUCT= MD.NPRODUCT AND COV.NPOLICY= MD.NPOLICY 
                            AND COV.NMODULEC=MD.NMODULEC
INNER JOIN TAR_HEALT_PREM TH ON COV.NPRODUCT= TH.NPRODUCT 
                                 AND COV.NCOVER= TH.NCOVER AND COV.NMODULEC= TH.NMODULEC
                                 AND COV.NROLE= TH.NROLE AND P.NOFFICE = TH.NOFFICE
INNER JOIN TABLE12 T12 ON COV.NROLE= T12.NROLE
WHERE P.SCERTYPE=2
AND COV.NPOLICY= 5
--AND COV.NCOVER = 5
--AND NVL(COV.NPREMIUM,0) > 0 
--AND     COV.SCERTYPE=3 
AND TH.NPOLICY_YEAR_INIT=1
AND TH.NAGE_INIT>= 42
AND TH.NAGE_END<=42
order by COV.NCOVER; 

