SELECT INT.NINTERMED COD_INTERMEDIARIO ,CLI.SCLIENT COD_CLIENTE, CLI.SCLIENAME
, TRIM(TIPO.SDESCRIPT) TIPO_INTERMEDIARIO
,TRIM(T200.SDESCRIPT) ESTADO
, INT.SCODAGENT_SCAB COD_SCAB
,TRIM(REG.SDESCRIPT) REGIONAL
, INT.DINPDATE FECHAEFECTO
, INT.DDATE_LIBRET
, CASE WHEN INT.SVALID = 1 THEN 'VALIDO' ELSE 'INACTIVO' END VALIDO 
--, INT.* 
FROM INTERMEDIA INT
INNER JOIN CLIENT CLI ON INT.SCLIENT = CLI.SCLIENT
LEFT JOIN TABLE200 T200 ON INT.NINT_STATUS = T200.NINT_STATUS
LEFT JOIN INTERM_TYP TIPO ON INT.NINTERTYP = TIPO.NINTERTYP
LEFT JOIN TABLE9 REG ON INT.NOFFICE= REG.NOFFICE
