SELECT
   -- GETDESCBENEFITS(M.nbranch,M.nproduct,M.nmodulec,M.deffecdate,M.NBENEFCATEG,M.SBENEFCATEG_CODE) AS BENEFICIO,
     M.NPRODUCT, M.NPOLICY, M.NCERTIF, M.SCLIENT
    ,LC.NCOVERGEN
    ,TRIM(TL.SDESCRIPT) AS NOMBRE_COBERTURA
    , M.NMODULEC
    ,TM.SDESCRIPT AS MODULO_PLAN
    ,M.NBENEFCATEG
    ,M.SBENEFCATEG_CODE
    , TRIM(BC.SDESCRIPT) AS CATEGORIA_BENEFICIO  
    ,M.NID
    ,TRIM(GETBENEFITDESCRIPTION(M.NID,0, M.NBRANCH , M.NPRODUCT, M.NMODULEC, M.NPOLICY, M.NCERTIF, M.SCLIENT, M.DEFFECDATE)) as NOMBRE_BENEFICIO
    , TRIM(GETDESCBENEFITS(M.nbranch,M.nproduct,M.nmodulec,M.deffecdate,M.NBENEFCATEG,M.SBENEFCATEG_CODE)) AS NOMBRE_BENEFICIO2
    ,TRIM(M.SCLARIFICACT) AS "Aclaraciones"
    ,COALESCE(M.NAMOUNT_BENE, M.NQUANTITY) AS "Limite Hasta"
    ,CASE WHEN NVL(M.NDED_TYPE,0) <> 0 THEN (TRIM(T269.SDESCRIPT) || ' - '|| NVL(TO_CHAR(M.NFRANCFIX), '')  )
       ELSE 'NO'
    END AS DEDUCIBLE
    ,M.NPERCEN_HOSPITAL AS "Hospitalaria"
    ,M.NPERCEN_AMBULATORY AS "Ambulatoria"
    ,CASE
        WHEN M.SCAREN_TYPE IS NOT NULL THEN NVL(TO_CHAR(M.NCAREN_QUANT), '') || ' ' || TRIM(T52.SDESCRIPT)
        ELSE NULL
    END AS "Carencia"
    ,m.*
   
FROM TAB_MEDBENEFITS M
INNER JOIN BENEFITS_CATEGORY BC ON M.NBENEFCATEG=BC.NBENEFCATEG
INNER JOIN LIFE_COVER LC ON M.NBRANCH= LC.NBRANCH AND M.NCOVER = LC.NCOVER AND M.NPRODUCT = LC.NPRODUCT AND M.NMODULEC= LC.NMODULEC
INNER JOIN TAB_LIFCOV TL ON LC.NCOVERGEN = TL.NCOVERGEN
LEFT JOIN TABLE269 T269 ON M.NDED_TYPE= T269.NDED_TYPE
LEFT JOIN TABLE52 T52 ON M.SCAREN_TYPE = T52.SCAREN_TYPE
INNER JOIN TAB_MODUL TM ON M.NBRANCH = TM.NBRANCH AND M.NPRODUCT = TM.NPRODUCT AND M.NMODULEC = TM.NMODULEC
WHERE M.NPOLICY = 1399
  AND M.SCERTYPE = 2
  --AND TL.NCOVERGEN IN (92000,)
  --AND M.SBENEFCATEG_CODE = '1010'
--  AND TL.NCOVERGEN IN (92250, 92000, 92190, 92191, 92200, 92180, 92220, 92230)
--  AND M.NBRANCH = :nbranch
--  AND M.NCERTIF = :ncertif
  AND M.DNULLDATE IS NULL
ORDER BY M.NCERTIF,LC.NCOVERGEN,14;