SELECT LAP.NBRANCH
  ,LAP.NPRODUCT
  ,LAP.NPOLICY
  ,LAP.NCERTIF
  ,LAP.NGROUP
  ,LAP.NMODULEC
  ,TM.SDESCRIPT AS MODULO_PLAN
  ,LC.NCOVERGEN
  , TRIM(TL.SDESCRIPT) AS NOMBRE_COBERTURA
  ,LAP.NCOVER
  ,LAP.SCLIENT AS SCLIENT_ASEGURADO
  ,LAP.NPRESTAC
  ,LAP.NCOD_AGREE
  ,CL.SCLIENAME AS NOMBRE_PROVEEDOR
  ,AG.NTYPEAGREE
  ,T5529.SDESCRIPT AS TIPO_PROVEEDOR
  ,LAP.NCITY_RESIDENCE
  ,LAP.DEFFECDATE
  ,LAP.DNULLDATE
  ,LAP.NUSERCODE
  ,LAP.DCOMPDATE
  ,LAP.NAMOUNT
  ,LAP.NCURRENCY
  ,LAP.NMOVEMENT  
FROM LEND_AGREE_PRES LAP 
INNER JOIN AGREEMENT AG ON LAP.NCOD_AGREE= AG.NCOD_AGREE
LEFT JOIN  TABLE5529 T5529 ON AG.NTYPEAGREE = T5529.NTYPEAGREE
INNER JOIN CLIENT CL ON AG.SCLIENT= CL.SCLIENT
INNER JOIN LIFE_COVER LC ON LAP.NBRANCH= LC.NBRANCH AND LAP.NCOVER = LC.NCOVER AND LAP.NPRODUCT = LC.NPRODUCT AND LAP.NMODULEC= LC.NMODULEC
INNER JOIN TAB_LIFCOV TL ON LC.NCOVERGEN = TL.NCOVERGEN
INNER JOIN TAB_MODUL TM ON LAP.NBRANCH = TM.NBRANCH AND LAP.NPRODUCT = TM.NPRODUCT AND LAP.NMODULEC = TM.NMODULEC 
WHERE LAP.NPOLICY=1152
AND LAP.SCERTYPE=2
ORDER BY LAP.NCERTIF