
--############### LOG ERRORES POR PROCEDIMIENTO ALMACENADOS  ###############
select * from TRACE where proc like '%TMP_INT51%'
--############### TABLAS PARA REPORTES POR INTERFAZ  ###############
SELECT * FROM MASTERSHEET Where Nsheet IN ('511','512','513','514','515')
SELECT * FROM FIELDSHEET Where Nsheet IN ('511','512','513','514','515')
SELECT * FROM WINDOWS WHERE SCODISPL IN ('INT511','INT512','INT513','INT514','INT515')

--############### PROVEEDORES  ###############
-- SSTATREGT --> ESTADOS DE PROVEEDORES
SELECT * FROM TABLE26
-- NTYPEPROV --> TIPOS DE PROVEEDORES
SELECT * FROM TABLE7027

--############### POLIZAS  ###############
--NCODIGINT --> MONEDAS
SELECT * FROM TABLE11
--ROLES.nrole= TABLE12.nrole --> ROLES DE UNA POLIZA
SELECT * FROM TABLE12
--POLICY.spolitype = TABLE17.ncodigint --> TIPOS DE POLIZAS
SELECT * FROM TABLE17 
--POLICY.Sstatus_Pol = TABLE181.Sstatusva --> ESTADOS DE POLIZAS Y DE LOS CERTIFICADOS
SELECT * FROM TABLE181
-- TAB_MEDBENEFITS.SBENEFCATEG_CODE = TABLE8604.STYPECARE --> AMBULATORIA/HOSPITALARIA
SELECT * FROM TABLE8604
