
SELECT  TRIM(TL.SDESCRIPT) AS NOMBRE_COBERTURA
        ,COV.NCOVER AS COD_COBERTURA
        ,COV.NPREMIUM_O AS PRIMAANUALORIGINAL
        ,COV.NRECAMOUNT AS MONTOANUALRECARGO
        ,COV.NDESCAMOUNT AS MONTOANUALDESCUENTO
        , COV.NPREMIUM AS PRIMAANUAL
FROM COVER COV
INNER JOIN LIFE_COVER LC ON COV.NBRANCH= LC.NBRANCH AND COV.NPRODUCT= LC.NPRODUCT
                              AND COV.NCOVER= LC.NCOVER AND COV.NMODULEC= LC.NMODULEC
                              AND LC.DNULLDATE IS NULL
INNER JOIN TAB_LIFCOV TL ON LC.NCOVERGEN = TL.NCOVERGEN
WHERE COV.NPOLICY= 1166
AND NVL(COV.NPREMIUM,0) > 0 
AND     COV.SCERTYPE=3 
order by COV.NCOVER; 
---- COV.SCERTYPE=3 cotizacion anual, cov.SCERTYPE=2 polizas
select * from SYS.ALL_SOURCE where upper(TEXT) like '%aranceles%%' 
