/*-------------------------------------------------------------------------------------*/
/* NOMBRE    : INSTMP_CAL503_V3                                                        */
/* OBJETIVO  : CREA UN REGISTRO EN LA TABLA TEMPORAL DEL LIBRO DE PRODUCCION           */
/* VERSION   : 3.0 - SELECT unico con CTEs minimos, sin cursores                       */
/*                                                                                     */
/* DISENO:                                                                             */
/*   - 1 CTE principal (DATOS_RECIBO) que une PREMIUM+CERTIFICAT+POLICY+PREMIUM_MO    */
/*   - 1 CTE auxiliar (INTERMEDIA_DATA) para datos del supervisor                      */
/*   - Todo lo demas como subconsultas escalares o expresiones CASE/NVL en el SELECT   */
/*   - Sin pasaje de parametros entre CTEs, sin variables locales                      */
/*   - Compatible Oracle 11g+                                                          */
/*-------------------------------------------------------------------------------------*/

CREATE OR REPLACE PROCEDURE INSUDB.INSTMP_CAL503_V3 (
    NCOMPANY       INTEGER,
    NINSUR_AREA    INTEGER,
    DDATE_INI      DATE,
    DDATE_END      DATE,
    NPRODUCT       PREMIUM.NPRODUCT%TYPE,
    NOFFICEAGEN    POLICY.NOFFICEAGEN%TYPE,
    NPOLICY        POLICY.NPOLICY%TYPE,
    NPROPONUM      POLICY.NPROPONUM%TYPE,
    DSTARTDATE     POLICY.DSTARTDATE%TYPE,
    DEXPIRDAT      POLICY.DEXPIRDAT%TYPE,
    DLEDGERDAT     PREMIUM_MO.DLEDGERDAT%TYPE,
    NCURRENCY      PREMIUM.NCURRENCY%TYPE,
    NP_EXENTA_MO   PREMIUM.NPREMIUM%TYPE,
    NP_NETA_MO     PREMIUM.NPREMIUM%TYPE,
    NP_IVA_MO      PREMIUM.NPREMIUM%TYPE,
    NP_TOTAL_MO    PREMIUM.NPREMIUM%TYPE,
    NC_DEV_MO      PREMIUM.NPREMIUM%TYPE,
    NCERTIF        CERTIFICAT.NCERTIF%TYPE,
    SKEY           VARCHAR2,
    NRECEIPT       PREMIUM.NRECEIPT%TYPE,
    NTRATYPEI      PREMIUM.NTRATYPEI%TYPE,
    NTYPE          PREMIUM.NTYPE%TYPE,
    NBORDEREAUX    PREMIUM_MO.NBORDEREAUX%TYPE,
    NBRANCH        PREMIUM.NBRANCH%TYPE,
    NINTERMED      POLICY.NINTERMED%TYPE,
    NBRANCH_LED    DETAIL_PRE.NBRANCH_LED%TYPE,
    SCLIENT        POLICY.SCLIENT%TYPE,
    NEXCHANGE      EXCHANGE.NEXCHANGE%TYPE,
    DEFFECDATE     PREMIUM.DEFFECDATE%TYPE,
    DEXPIRDAT_PRE  PREMIUM.DEXPIRDAT%TYPE,
    NTRANSAC       PREMIUM_MO.NTRANSAC%TYPE,
    NPRODCLAS      PRODUCT_LI.NPRODCLAS%TYPE DEFAULT NULL,
    NCONTRAT       FINANC_DRA.NCONTRAT%TYPE DEFAULT 0,
    NDRAFT         FINANC_DRA.NDRAFT%TYPE DEFAULT 0,
    NEXECUTE       INTEGER,
    NUSERCODE      NUMBER,
    DPOSTED        DATE,
    NTYPE_PREM     NUMBER DEFAULT NULL,
    DSTATDATE      PREMIUM_MO.DSTATDATE%TYPE DEFAULT NULL,
    NRECARAD_MO    PREMIUM.NPREMIUM%TYPE DEFAULT 0,
    NTYPE_MANTCTA_AUX NUMBER DEFAULT NULL
) AUTHID CURRENT_USER AS
BEGIN

    /* =================================================================
       INSERT UNICO: CTE DATOS_RECIBO + subconsultas escalares
       ================================================================= */
    INSERT INTO TIMETMP.TMP_CAL503 (
        NCOMPANY, NINSUR_AREA, DSTARTDATE_REP, DEXPIRDATE_REP,
        SDESCBRANCH_FECU, SDESC_BRANCH, NPRODUCT, SDESCPRODUCT,
        NOFFICE, SDESCOFFICE, NPOLICY, NPROPONUM,
        DSTARTDATE, DEXPIRDAT, DEFFECDATE_Q, DEXPIRDAT_Q, DDATE_ACCEPT,
        SCLIENT_ASEG, SCLIENAME_ASEG, SCLIENT_AGEN, SCLIENAME_AGE,
        NCURRENCY, SDESCCURRENCY,
        NPREMIUME_MO, NPREMIUMA_MO, NPREMIUMIVA_MO, NPREMIUM_MO,
        NCOMAMOU_MO, NPREMIUME, NPREMIUMA, NPREMIUMIVA, NPREMIUM,
        NCOMAMOU_PES, NCERTIF, SKEY, DPOSTED, NBRANCH_LED,
        SCLIENTSPONSOR, NRECEIPT, NTYPE_TRAN, ID_REGISTRO,
        NTYPE_HIST, NCODLINEBUSI, NSELLCHANNEL, SDESCSELLCHANNEL,
        NCURRENCY_LOC, SDESCCURR_LOC, NEXCHANGE, NNULLCODE, NINTERTYP,
        SCLIENT_SUPER, SCLIENAME_SUPER, SDESC_TYPE_HIST, SDESC_LINEBUSI,
        NMONRENEW, SNAMEHOLDER, NPAYFREQ, SDESC_PAYFREQ, NNUMINSUR,
        SDESC_NULLCODE, NCAPITAL_MO, NCAPITAL_LO, SUSERNAME, DISSUEDAT,
        NADDPREMIUM_MO, NADDPREMIUM_LO, NDEFERREDPREM_MO, NDEFERREDPREM_LO,
        NADDDEFERPREM_MO, NADDDEFERPREM_LO, SDESC_INTERTYP,
        NINTCOMMPERC, NSUPCOMMPERC, SDESC_WAY_PAY, NWAYPAY,
        NMONTIT_MO, NMONTIT_ML, NMONTAPS_MO, NMONTAPS_ML,
        NRECARAD_MO, NRECARAD_ML, NBRANCH,
        NCOMAMOUSUP_MO, NCOMAMOUSUP_ML, NINTFINAN_MO, NINTFINAN_ML,
        NACCCRITERION
    )
    WITH
    /* =================================================================
       CTE principal: une las 4 tablas base del recibo
       ================================================================= */
    DATOS_RECIBO AS (
        SELECT PR.DISSUEDAT, PR.NWAY_PAY, PR.DEFFECDATE, PR.NPERIOD,
               PR.NCURRENCY, PR.NPOLICY, PR.NCERTIF, PR.NRECEIPT,
               CERT.SCLIENTSPONSOR, CERT.NSELLCHANNEL, CERT.NNULLCODE,
               CERT.NPAYFREQ, CERT.DDATE_ORIGI, CERT.SSTATUSVA,
               CERT.NCAPITAL AS CERT_CAPITAL,
               TO_NUMBER(POL.SPOLITYPE) AS SPOLITYPE,
               POL.SSTATUS_POL, POL.NINTERMED,
               REAGENERALPKG.REACODIGINT('TABLE5002','NWAY_PAY', PR.NWAY_PAY) AS SDESC_WAY_PAY,
               REAGENERALPKG.REACODIGINT('TABLE17','NCODIGINT', POL.SPOLITYPE) AS SDESC_LINEBUSI,
               REAGENERALPKG.REACLIENTCONT('2', PR.NBRANCH, PR.NPRODUCT, PR.NPOLICY, 0, PR.DEFFECDATE, 1) AS SNAMEHOLDER,
               REAGENERALPKG.REACODIGINT('TABLE36','NPAYFREQ', CERT.NPAYFREQ) AS SDESC_PAYFREQ,
               REAGENERALPKG.REACODIGINT('TABLE13','NNULLCODE', CERT.NNULLCODE) AS SDESC_NULLCODE,
               REAGENERALPKG.REACODIGINTSH('TABLE5532','NSELLCHANNEL', CERT.NSELLCHANNEL) AS SDESCSELLCHANNEL,
               REAGENERALPKG.GETCAPITALCOVER('2', PR.NBRANCH, PR.NPRODUCT, PR.NPOLICY,
                   PR.NCERTIF, NVL(POL.SCLIENT, SCLIENT), NVL(DSTATDATE, SYSDATE)) AS NCAPITAL_MO,
               GETBOOKPREMIUMS('2', PR.NBRANCH, PR.NPRODUCT, PR.NPOLICY, PR.NCERTIF,
                   PR.NRECEIPT, 0, 0, NBRANCH_LED, '6', DDATE_END, PR.DEFFECDATE) AS NMONTIT_MO,
               GETBOOKPREMIUMS('2', PR.NBRANCH, PR.NPRODUCT, PR.NPOLICY, PR.NCERTIF,
                   PR.NRECEIPT, 0, 0, NBRANCH_LED, '7', DDATE_END, PR.DEFFECDATE) AS NMONTAPS_MO
          FROM (
              SELECT SCERTYPE, NBRANCH, NPRODUCT, NPOLICY, NCERTIF,
                     NRECEIPT, NDIGIT, NPAYNUMBE, DISSUEDAT, NWAY_PAY,
                     DEFFECDATE, NPERIOD, NCURRENCY
                FROM PREMIUM
               WHERE SCERTYPE  = '2'
                 AND NBRANCH   = INSTMP_CAL503_V3.NBRANCH
                 AND NPRODUCT  = INSTMP_CAL503_V3.NPRODUCT
                 AND NRECEIPT  = INSTMP_CAL503_V3.NRECEIPT
                 AND NDIGIT    = 0
                 AND NPAYNUMBE = 0
               GROUP BY SCERTYPE, NBRANCH, NPRODUCT, NPOLICY, NCERTIF,
                        NRECEIPT, NDIGIT, NPAYNUMBE, DISSUEDAT, NWAY_PAY,
                        DEFFECDATE, NPERIOD, NCURRENCY
          ) PR
          INNER JOIN CERTIFICAT CERT
                  ON CERT.SCERTYPE = PR.SCERTYPE AND CERT.NBRANCH = PR.NBRANCH
                 AND CERT.NPRODUCT = PR.NPRODUCT AND CERT.NPOLICY = PR.NPOLICY
                 AND CERT.NCERTIF = PR.NCERTIF
          INNER JOIN POLICY POL
                  ON POL.SCERTYPE = PR.SCERTYPE AND POL.NBRANCH = PR.NBRANCH
                 AND POL.NPRODUCT = PR.NPRODUCT AND POL.NPOLICY = PR.NPOLICY
    )
    SELECT
        /* === Fijos del SP === */
        INSTMP_CAL503_V3.NCOMPANY,
        INSTMP_CAL503_V3.NINSUR_AREA,
        INSTMP_CAL503_V3.DDATE_INI                                         AS DSTARTDATE_REP,
        INSTMP_CAL503_V3.DDATE_END                                         AS DEXPIRDATE_REP,
        REAGENERALPKG.REACODIGINTSH('TABLE75','NBRANCH_LED', INSTMP_CAL503_V3.NBRANCH_LED) AS SDESCBRANCH_FECU,
        REAGENERALPKG.REACODIGINTSH('TABLE10','NBRANCH', INSTMP_CAL503_V3.NBRANCH)         AS SDESC_BRANCH,
        INSTMP_CAL503_V3.NPRODUCT,
        REAGENERALPKG.REASPRODUCT(INSTMP_CAL503_V3.NBRANCH, INSTMP_CAL503_V3.NPRODUCT)     AS SDESCPRODUCT,
        INSTMP_CAL503_V3.NOFFICEAGEN                                      AS NOFFICE,
        REAGENERALPKG.REACODIGINTSH('TABLE5556','NOFFICEAGEN', INSTMP_CAL503_V3.NOFFICEAGEN) AS SDESCOFFICE,
        INSTMP_CAL503_V3.NPOLICY,
        INSTMP_CAL503_V3.NPROPONUM,
        INSTMP_CAL503_V3.DSTARTDATE,
        INSTMP_CAL503_V3.DEXPIRDAT,
        INSTMP_CAL503_V3.DEFFECDATE                                        AS DEFFECDATE_Q,
        INSTMP_CAL503_V3.DEXPIRDAT_PRE                                     AS DEXPIRDAT_Q,
        INSTMP_CAL503_V3.DLEDGERDAT                                        AS DDATE_ACCEPT,
        INSTMP_CAL503_V3.SCLIENT                                           AS SCLIENT_ASEG,
        SUBSTR(REAGENERALPKG.REANAMECLI(INSTMP_CAL503_V3.SCLIENT), 1, 30) AS SCLIENAME_ASEG,
        TO_CHAR(INTERM.NINTERMED)                                          AS SCLIENT_AGEN,
        INTERM.SNAME_AGE                                                   AS SCLIENAME_AGE,
        INSTMP_CAL503_V3.NCURRENCY,
        INITCAP(REAGENERALPKG.REACODIGINTSH('TABLE11','NCODIGINT', INSTMP_CAL503_V3.NCURRENCY)) AS SDESCCURRENCY,

        /* === Montos en MO === */
        INSTMP_CAL503_V3.NP_EXENTA_MO                                     AS NPREMIUME_MO,
        NVL(INSTMP_CAL503_V3.NP_NETA_MO, 0)                               AS NPREMIUMA_MO,
        NVL(INSTMP_CAL503_V3.NP_IVA_MO, 0)                                AS NPREMIUMIVA_MO,
        INSTMP_CAL503_V3.NP_TOTAL_MO                                      AS NPREMIUM_MO,
        NVL(DCOMIS.NAMOUNT, 0)                                             AS NCOMAMOU_MO,

        /* === Montos en ML === */
        ROUND(INSTMP_CAL503_V3.NP_EXENTA_MO * TC, 2)                      AS NPREMIUME,
        ROUND(NVL(INSTMP_CAL503_V3.NP_NETA_MO, 0) * TC, 2)               AS NPREMIUMA,
        ROUND(NVL(INSTMP_CAL503_V3.NP_IVA_MO, 0) * TC, 2)                AS NPREMIUMIVA,
        ROUND(INSTMP_CAL503_V3.NP_TOTAL_MO * TC, 2)                       AS NPREMIUM,
        ROUND(NVL(DCOMIS.NAMOUNT, 0) * TC, 2)                             AS NCOMAMOU_PES,

        INSTMP_CAL503_V3.NCERTIF,
        INSTMP_CAL503_V3.SKEY,
        INSTMP_CAL503_V3.DPOSTED,
        INSTMP_CAL503_V3.NBRANCH_LED,
        NVL(DR.SCLIENTSPONSOR, ' ')                                       AS SCLIENTSPONSOR,
        INSTMP_CAL503_V3.NRECEIPT,
        INSTMP_CAL503_V3.NTYPE                                             AS NTYPE_TRAN,
        NVL((SELECT NVL(MAX(ID_REGISTRO),0)+1 FROM TIMETMP.TMP_CAL503 T WHERE T.SKEY = INSTMP_CAL503_V3.SKEY), 1) AS ID_REGISTRO,

        /* === Historia de poliza === */
        NVL(PH.NTYPE_HIST, 0)                                             AS NTYPE_HIST,
        NVL(DR.NSELLCHANNEL, 0)                                           AS NCODLINEBUSI,
        NVL(DR.NSELLCHANNEL, 0)                                           AS NSELLCHANNEL,
        NVL(DR.SDESCSELLCHANNEL, ' ')                                     AS SDESCSELLCHANNEL,
        1                                                                  AS NCURRENCY_LOC,
        INITCAP(REAGENERALPKG.REACODIGINTSH('TABLE11','NCODIGINT', 1))    AS SDESCCURR_LOC,
        TC                                                                 AS NEXCHANGE,
        0                                                                  AS NNULLCODE,
        NVL(IT.NINTERTYP, 0)                                              AS NINTERTYP,
        TO_CHAR(IT.NSUPERVIS)                                             AS SCLIENT_SUPER,
        IT.SCLIENAME_SUPER                                                 AS SCLIENAME_SUPER,

        /* === Descripcion tipo historia (con regla de exclusion) === */
        CASE
            WHEN GETPRODUCTION('2',INSTMP_CAL503_V3.NBRANCH,INSTMP_CAL503_V3.NPRODUCT,
                    INSTMP_CAL503_V3.NRECEIPT, NVL(DR.DDATE_ORIGI,SYSDATE),
                    INSTMP_CAL503_V3.DSTARTDATE,INSTMP_CAL503_V3.DEFFECDATE,
                    INSTMP_CAL503_V3.NTRATYPEI,INSTMP_CAL503_V3.NTYPE,INSTMP_CAL503_V3.NTYPE_PREM) = 4
                 AND INSTMP_CAL503_V3.NCERTIF > 0 AND NVL(DR.SSTATUSVA,'0') = '6'
                 AND DR.NNULLCODE IS NULL AND NVL(DR.SSTATUS_POL,'0') = '6'
            THEN 'Exclusion'
            WHEN GETPRODUCTION('2',INSTMP_CAL503_V3.NBRANCH,INSTMP_CAL503_V3.NPRODUCT,
                    INSTMP_CAL503_V3.NRECEIPT, NVL(DR.DDATE_ORIGI,SYSDATE),
                    INSTMP_CAL503_V3.DSTARTDATE,INSTMP_CAL503_V3.DEFFECDATE,
                    INSTMP_CAL503_V3.NTRATYPEI,INSTMP_CAL503_V3.NTYPE,INSTMP_CAL503_V3.NTYPE_PREM) = 4
                 AND INSTMP_CAL503_V3.NCERTIF > 0
                 AND NVL((SELECT MAX(PH2.NTYPE_AMEND) FROM POLICY_HIS PH2
                           WHERE PH2.SCERTYPE='2' AND PH2.NBRANCH=INSTMP_CAL503_V3.NBRANCH
                             AND PH2.NPRODUCT=INSTMP_CAL503_V3.NPRODUCT AND PH2.NPOLICY=INSTMP_CAL503_V3.NPOLICY
                             AND PH2.NCERTIF=INSTMP_CAL503_V3.NCERTIF AND PH2.NRECEIPT=INSTMP_CAL503_V3.NRECEIPT
                             AND NVL(PH2.SNULL_MOVE,'2')='2'), 0) = 9303
                 AND DR.NNULLCODE IS NULL
            THEN 'Exclusion'
            ELSE REAGENERALPKG.REACODIGINT('TABLE9272','NACCCRITERION',
                    GETPRODUCTION('2',INSTMP_CAL503_V3.NBRANCH,INSTMP_CAL503_V3.NPRODUCT,
                        INSTMP_CAL503_V3.NRECEIPT, NVL(DR.DDATE_ORIGI,SYSDATE),
                        INSTMP_CAL503_V3.DSTARTDATE,INSTMP_CAL503_V3.DEFFECDATE,
                        INSTMP_CAL503_V3.NTRATYPEI,INSTMP_CAL503_V3.NTYPE,INSTMP_CAL503_V3.NTYPE_PREM))
        END                                                                AS SDESC_TYPE_HIST,

        NVL(DR.SDESC_LINEBUSI, ' ')                                       AS SDESC_LINEBUSI,
        NVL(DR.NPAYFREQ, 0)                                               AS NMONRENEW,
        NVL(DR.SNAMEHOLDER, ' ')                                           AS SNAMEHOLDER,
        NVL(DR.NPAYFREQ, 0)                                               AS NPAYFREQ,
        NVL(DR.SDESC_PAYFREQ, ' ')                                         AS SDESC_PAYFREQ,
        NVL((SELECT COUNT(*) FROM ROLES RO WHERE RO.SCERTYPE='2'
              AND RO.NBRANCH=INSTMP_CAL503_V3.NBRANCH AND RO.NPRODUCT=INSTMP_CAL503_V3.NPRODUCT
              AND RO.NPOLICY=INSTMP_CAL503_V3.NPOLICY AND RO.NCERTIF=INSTMP_CAL503_V3.NCERTIF
              AND RO.DEFFECDATE<=NVL(DSTATDATE,SYSDATE)
              AND (RO.DNULLDATE IS NULL OR RO.DNULLDATE>NVL(DSTATDATE,SYSDATE))
              AND RO.NROLE IN (2,7,20,21,22,23,24,27,28,29,30,32,33,60,67,68)), 0) AS NNUMINSUR,
        NVL(DR.SDESC_NULLCODE, ' ')                                        AS SDESC_NULLCODE,

        /* === Capital === */
        NVL(DR.NCAPITAL_MO, 0)                                            AS NCAPITAL_MO,
        ROUND(NVL(DR.NCAPITAL_MO, 0) * TC, 2)                             AS NCAPITAL_LO,

        /* === Usuario === */
        NVL((SELECT REAGENERALPKG.REANAMECLI_USERCODE(PH3.NUSERCODE)
               FROM POLICY_HIS PH3
              WHERE PH3.SCERTYPE='2' AND PH3.NBRANCH=INSTMP_CAL503_V3.NBRANCH
                AND PH3.NPRODUCT=INSTMP_CAL503_V3.NPRODUCT AND PH3.NPOLICY=INSTMP_CAL503_V3.NPOLICY
                AND PH3.NCERTIF=INSTMP_CAL503_V3.NCERTIF
                AND ((PH3.NTYPE_HIST=1 AND INSTMP_CAL503_V3.NCERTIF=0)
                  OR (PH3.NTYPE_HIST=2 AND INSTMP_CAL503_V3.NCERTIF>0))
              ORDER BY PH3.NMOVEMENT DESC FETCH FIRST 1 ROW ONLY), ' ')   AS SUSERNAME,
        DR.DISSUEDAT,

        /* === Prima adicional === */
        (NVL(NRECARAD_MO,0) + NVL(DR.NMONTAPS_MO,0) + NVL(DR.NMONTIT_MO,0)) AS NADDPREMIUM_MO,
        ROUND((NVL(NRECARAD_MO,0) + NVL(DR.NMONTAPS_MO,0) + NVL(DR.NMONTIT_MO,0)) * TC, 2) AS NADDPREMIUM_LO,
        0                                                                  AS NDEFERREDPREM_MO,
        0                                                                  AS NDEFERREDPREM_LO,
        0                                                                  AS NADDDEFERPREM_MO,
        0                                                                  AS NADDDEFERPREM_LO,
        IT.SDESC_INTERTYP,
        NVL(DCOMIS.NINTCOMMPERC, 0)                                        AS NINTCOMMPERC,
        NVL(SUP.NSUPCOMMPERC, 0)                                           AS NSUPCOMMPERC,
        NVL(DR.SDESC_WAY_PAY, ' ')                                         AS SDESC_WAY_PAY,
        NVL(DR.NWAY_PAY, 0)                                                AS NWAYPAY,

        /* === IT === */
        CASE WHEN INSTMP_CAL503_V3.NTYPE IN (7,8) THEN NVL(DR.NMONTIT_MO,0)*-1
             ELSE NVL(DR.NMONTIT_MO,0) END                                 AS NMONTIT_MO,
        CASE WHEN INSTMP_CAL503_V3.NTYPE IN (7,8) THEN ROUND(NVL(DR.NMONTIT_MO,0)*-1*TC,2)
             ELSE ROUND(NVL(DR.NMONTIT_MO,0)*TC,2) END                    AS NMONTIT_ML,

        /* === APS === */
        CASE WHEN INSTMP_CAL503_V3.NTYPE IN (7,8) THEN NVL(DR.NMONTAPS_MO,0)*-1
             ELSE NVL(DR.NMONTAPS_MO,0) END                                AS NMONTAPS_MO,
        CASE WHEN INSTMP_CAL503_V3.NTYPE IN (7,8) THEN ROUND(NVL(DR.NMONTAPS_MO,0)*-1*TC,2)
             ELSE ROUND(NVL(DR.NMONTAPS_MO,0)*TC,2) END                   AS NMONTAPS_ML,

        /* === Recargo adicional === */
        NVL(NRECARAD_MO, 0)                                                AS NRECARAD_MO,
        ROUND(NVL(NRECARAD_MO, 0) * TC, 2)                                 AS NRECARAD_ML,

        INSTMP_CAL503_V3.NBRANCH,

        /* === Comision supervisor === */
        CASE WHEN INTERM.SCLIENT_AGE IS NOT NULL AND IT.SCLIENT_SUPER IS NOT NULL
                  AND INTERM.SCLIENT_AGE = IT.SCLIENT_SUPER THEN 0
             ELSE NVL(SUP.NAMOUNT_SUP, 0) END                              AS NCOMAMOUSUP_MO,
        CASE WHEN INTERM.SCLIENT_AGE IS NOT NULL AND IT.SCLIENT_SUPER IS NOT NULL
                  AND INTERM.SCLIENT_AGE = IT.SCLIENT_SUPER THEN 0
             ELSE ROUND(NVL(SUP.NAMOUNT_SUP, 0) * TC, 2) END             AS NCOMAMOUSUP_ML,

        /* === Interes financiero === */
        0                                                                  AS NINTFINAN_MO,
        0                                                                  AS NINTFINAN_ML,

        /* === Criterio de produccion === */
        GETPRODUCTION('2',INSTMP_CAL503_V3.NBRANCH,INSTMP_CAL503_V3.NPRODUCT,
            INSTMP_CAL503_V3.NRECEIPT, NVL(DR.DDATE_ORIGI,SYSDATE),
            INSTMP_CAL503_V3.DSTARTDATE,INSTMP_CAL503_V3.DEFFECDATE,
            INSTMP_CAL503_V3.NTRATYPEI,INSTMP_CAL503_V3.NTYPE,INSTMP_CAL503_V3.NTYPE_PREM) AS NACCCRITERION

    FROM (
        /* === Tipo de cambio === */
        SELECT CASE
                   WHEN INSTMP_CAL503_V3.NCURRENCY = 1 THEN 1
                   WHEN INSTMP_CAL503_V3.NPRODCLAS IN (9,10) THEN INSTMP_CAL503_V3.NEXCHANGE
                   ELSE REAGENERALPKG.GETEXCHANGE(INSTMP_CAL503_V3.NCURRENCY, 1, INSTMP_CAL503_V3.DDATE_END)
               END AS TC
          FROM DUAL
    ) TC CROSS JOIN (
        /* === Datos del intermediario === */
        SELECT INSTMP_CAL503_V3.NINTERMED AS NINTERMED,
               REAGENERALPKG.REACLIENTINTERMED(INSTMP_CAL503_V3.NINTERMED) AS SCLIENT_AGE,
               SUBSTR(REAGENERALPKG.REANAMEINTERMED(INSTMP_CAL503_V3.NINTERMED), 1, 63) AS SNAME_AGE
          FROM DUAL
    ) INTERM
    LEFT JOIN (
        /* === Datos del supervisor (INTERMEDIA) === */
        SELECT IT.NINTERTYP,
               CASE WHEN INSTMP_CAL503_V3.NINSUR_AREA = 2 THEN REAGENERALPKG.REACLIENTINTERMED(IT.NSUPERVIS)
                    WHEN INSTMP_CAL503_V3.NINSUR_AREA = 1 THEN REAGENERALPKG.REACLIENTINTERMED(IT.NSUP_GEN)
                    ELSE NULL END AS SCLIENT_SUPER,
               CASE WHEN INSTMP_CAL503_V3.NINSUR_AREA = 2 THEN TRIM(REAGENERALPKG.REANAMEINTERMED(IT.NSUPERVIS))
                    WHEN INSTMP_CAL503_V3.NINSUR_AREA = 1 THEN TRIM(REAGENERALPKG.REANAMEINTERMED(IT.NSUP_GEN))
                    ELSE NULL END AS SCLIENAME_SUPER,
               REAGENERALPKG.REANAMEINTERTYP(IT.NINTERTYP) AS SDESC_INTERTYP,
               CASE WHEN INSTMP_CAL503_V3.NINSUR_AREA = 2 THEN IT.NSUPERVIS
                    WHEN INSTMP_CAL503_V3.NINSUR_AREA = 1 THEN IT.NSUP_GEN
                    ELSE NULL END AS NSUPERVIS
          FROM INTERMEDIA IT
         WHERE IT.NINTERMED = INSTMP_CAL503_V3.NINTERMED
    ) IT ON 1=1
    LEFT JOIN (
        /* === Tipo de historia === */
        SELECT PH.NTYPE_HIST
          FROM (
              SELECT NTYPE_HIST, ROW_NUMBER() OVER (ORDER BY NMOVEMENT ASC) AS RN
                FROM POLICY_HIS
               WHERE SCERTYPE='2' AND NBRANCH=INSTMP_CAL503_V3.NBRANCH
                 AND NPRODUCT=INSTMP_CAL503_V3.NPRODUCT AND NPOLICY=INSTMP_CAL503_V3.NPOLICY
                 AND NCERTIF=INSTMP_CAL503_V3.NCERTIF AND NVL(SNULL_MOVE,'2')='2'
                 AND NRECEIPT=INSTMP_CAL503_V3.NRECEIPT
          ) PH WHERE RN = 1
    ) PH ON 1=1
    LEFT JOIN DATOS_RECIBO DR ON 1=1
    LEFT JOIN (
        /* === Comision total del intermediario === */
        SELECT NVL(SUM(NVL(NCOMMISION,0)),0) AS NAMOUNT,
               MAX(NCOMMI_RATE) AS NINTCOMMPERC
          FROM DETAIL_PRE
         WHERE SCERTYPE='2' AND NBRANCH=INSTMP_CAL503_V3.NBRANCH
           AND NPRODUCT=INSTMP_CAL503_V3.NPRODUCT AND NRECEIPT=INSTMP_CAL503_V3.NRECEIPT
           AND NDIGIT=0 AND NPAYNUMBE=0
    ) DCOMIS ON 1=1
    LEFT JOIN (
        /* === Comision del supervisor === */
        SELECT NVL(CM.NPERCENT,0) AS NSUPCOMMPERC,
               NVL(CM.NAMOUNT,0)  AS NAMOUNT_SUP
          FROM COMMISS_PR CM
         WHERE CM.SCERTYPE='2' AND CM.NBRANCH=INSTMP_CAL503_V3.NBRANCH
           AND CM.NPRODUCT=INSTMP_CAL503_V3.NPRODUCT AND CM.NRECEIPT=INSTMP_CAL503_V3.NRECEIPT
           AND CM.NDIGIT=0 AND CM.NPAYNUMBE=0
           AND CM.NINTERMED = (
               SELECT CASE WHEN INSTMP_CAL503_V3.NINSUR_AREA = 2 THEN IT2.NSUPERVIS
                            WHEN INSTMP_CAL503_V3.NINSUR_AREA = 1 THEN IT2.NSUP_GEN
                            ELSE NULL END
                 FROM INTERMEDIA IT2 WHERE IT2.NINTERMED = INSTMP_CAL503_V3.NINTERMED
           )
           AND ROWNUM = 1
    ) SUP ON 1=1;

    /* =================================================================
       BOOK_PRODUCTION (si NEXECUTE = 2)
       ================================================================= */
    IF NEXECUTE = 2 THEN
        INSERT INTO INSUDB.BOOK_PRODUCTION (
            SCERTYPE, NBRANCH, NPRODUCT, NPOLICY, NRECEIPT, NTRANSAC,
            SKEY, SCLIENTSPONSOR, DSTARTDATE, DEXPIRDAT, NCERTIF, DDATE_ACCEPT,
            SCLIENT_ASEG, NCURRENCY, NPREMIUME_MO, NPREMIUMA_MO, NPREMIUM_MO,
            NPREMIUME, NPREMIUMA, SCLIENT_AGEN, NPREMIUM, NCOMAMOU_MO,
            NCOMAMOU_PES, DPOSTED, NBRANCH_LED, NUSERCODE, NCOMPANY,
            NINSUR_AREA, DSTARTDATE_REP, DEXPIRDATE_REP, DLEDGERDAT, DCOMPDATE,
            NTRATYPEI, NTYPE, NTYPE_TRAN, NACCCRITERION
        )
        SELECT
            '2', NBRANCH, NPRODUCT, NPOLICY, NRECEIPT, NTRANSAC,
            SKEY, SCLIENTSPONSOR, DSTARTDATE, DEXPIRDAT, NCERTIF, DDATE_ACCEPT,
            SCLIENT_ASEG, NCURRENCY, NPREMIUME_MO, NPREMIUMA_MO, NPREMIUM_MO,
            NPREMIUME, NPREMIUMA, SCLIENT_AGEN, NPREMIUM, NCOMAMOU_MO,
            NCOMAMOU_PES, NULL, NBRANCH_LED, NUSERCODE, NCOMPANY,
            NINSUR_AREA, DSTARTDATE_REP, DEXPIRDATE_REP, DLEDGERDAT, SYSDATE,
            NTRATYPEI, NTYPE_PREM, NTYPE_TRAN, NACCCRITERION
          FROM TIMETMP.TMP_CAL503
         WHERE SKEY = INSTMP_CAL503_V3.SKEY
           AND NPOLICY = INSTMP_CAL503_V3.NPOLICY
           AND NRECEIPT = INSTMP_CAL503_V3.NRECEIPT;
    END IF;

END INSTMP_CAL503_V3;
/
