create or replace PACKAGE REAGENERALPKG AUTHID CURRENT_USER AS
/*----------------------------------------------------------------------------*/
/* NOMBRE    : INSUDB.REAGENERALPKG                                           */
/* OBJETIVO  : CONTIENE FUNCIONES QUE RETORNAN DESCRIPCIONES DE TABLAS        */
/*             FRECUENTEMENTE USADAS                                          */
/*  SourceSafe Information:                                                   */
/*      $Author:: Mpalleres     $                                             */
/*      $Date:: 9-09-09 19:13   $                                             */
/*      $Revision:: 5           $                                             */
/*----------------------------------------------------------------------------*/

/* Tipos de intermediario */
K_AGENTE            INTERM_TYP.NINTERTYP%TYPE := 1;
K_SUP_AG            INTERM_TYP.NINTERTYP%TYPE := 5;
K_J_FFVV            INTERM_TYP.NINTERTYP%TYPE := 18;
K_BROKER            INTERM_TYP.NINTERTYP%TYPE := 3;
K_EJ_BRO            INTERM_TYP.NINTERTYP%TYPE := 20;
K_J_BRO             INTERM_TYP.NINTERTYP%TYPE := 19;
K_A_COM             INTERM_TYP.NINTERTYP%TYPE := 52;
K_DIRECTO           INTERM_TYP.NINTERTYP%TYPE := 21;

/*+RESCATA LA COMPA?IA PARTICIPANTE DE REASEGURO*/
FUNCTION REAPART_CONTR(NNUMBER     PART_CONTR.NNUMBER%TYPE,
                       NTYPE       PART_CONTR.NTYPE%TYPE,
                       NBRANCH_REI PART_CONTR.NBRANCH%TYPE,
                       DEFFECDATE  PART_CONTR.DEFFECDATE%TYPE)
                       RETURN      CLIENT.SCLIENAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REAPART_CONTR,  WNDS,   WNPS);


/*+RESCATA LA CADENA DE TRANSACCIONES DE SECTION_PO */
FUNCTION REASECTION_PO(NBRANCH      SECTION_PO.NBRANCH%TYPE,
                       NPRODUCT     SECTION_PO.NPRODUCT%TYPE,
                       SPOLITYPE    SECTION_PO.SPOLITYPE%TYPE,
                       NCERTIF      CERTIFICAT.NCERTIF%TYPE,
                       NTYPE_AMEND  SECTION_PO.NTYPE_AMEND%TYPE,
                       DEFFECDATE   SECTION_PO.DEFFECDATE%TYPE)
                       RETURN      VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REASECTION_PO,  WNDS,   WNPS);


/*+RESCATA EL SBRANCHT */
FUNCTION REABRANCHT(NBRANCH  PRODMASTER.NBRANCH%TYPE,
                    NPRODUCT PRODMASTER.NPRODUCT%TYPE)
                    RETURN PRODMASTER.SBRANCHT%TYPE;
PRAGMA RESTRICT_REFERENCES(REABRANCHT,  WNDS,   WNPS);

/*+ INDICA EL CODIGO DE CLIENTE PARA UN ROLE ESPECIFICO EN UNA POLIZA */
FUNCTION REACLIENTROLE(SCERTYPE    ROLES.SCERTYPE%TYPE,
                       NBRANCH     ROLES.NBRANCH%TYPE,
                       NPRODUCT    ROLES.NPRODUCT%TYPE,
                       NPOLICY     ROLES.NPOLICY%TYPE,
                       NCERTIF     ROLES.NCERTIF%TYPE,
                       DEFFECDATE  ROLES.DEFFECDATE%TYPE)
                       RETURN   ROLES.SCLIENT%TYPE;
PRAGMA RESTRICT_REFERENCES(REACLIENTROLE,     WNDS,   WNPS);

/*+ INDICA EL CODIGO DE CLIENTE PARA UN ROLE ESPECIFICO EN UNA POLIZA */
FUNCTION REACLIENTROLE2(SCERTYPE    ROLES.SCERTYPE%TYPE,
                       NBRANCH     ROLES.NBRANCH%TYPE,
                       NPRODUCT    ROLES.NPRODUCT%TYPE,
                       NPOLICY     ROLES.NPOLICY%TYPE,
                       NCERTIF     ROLES.NCERTIF%TYPE,
                       NROLE       ROLES.NROLE%TYPE,
                       DEFFECDATE  ROLES.DEFFECDATE%TYPE)
                       RETURN   ROLES.SCLIENT%TYPE;
PRAGMA RESTRICT_REFERENCES(REACLIENTROLE2,     WNDS,   WNPS);

/*+IINDICA EL NOMBRE DE EL CONTRATANTE DE UNA POLIZA*/
FUNCTION REACLIENTCONT(SCERTYPE    ROLES.SCERTYPE%TYPE,
                       NBRANCH     ROLES.NBRANCH%TYPE,
                       NPRODUCT    ROLES.NPRODUCT%TYPE,
                       NPOLICY     ROLES.NPOLICY%TYPE,
                       NCERTIF     ROLES.NCERTIF%TYPE,
                       DEFFECDATE  ROLES.DEFFECDATE%TYPE,
                       NROLE       ROLES.NROLE%TYPE)
                       RETURN      CLIENT.SCLIENAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REACLIENTCONT,     WNDS,   WNPS);

/*+RESCATA EL INDICADOR DE CRS DEL CLIENTE CON FORMATO "DE SI O NO" */
FUNCTION REACRSCLI(SCLIENT         CLIENT.SCLIENT%TYPE)
                        RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REACRSCLI,  WNDS,   WNPS);

/*+ INDICA LA FECHA DE CONTABILIZACION EN UNA POLIZA */
FUNCTION READLEDGERDATE(SCERTYPE   POLICY_HIS.SCERTYPE%TYPE,
                        NBRANCH    POLICY_HIS.NBRANCH%TYPE,
                        NPRODUCT   POLICY_HIS.NPRODUCT%TYPE,
                        NPOLICY    POLICY_HIS.NPOLICY%TYPE,
                        NCERTIF    POLICY_HIS.NCERTIF%TYPE)
                        RETURN     POLICY_HIS.DLEDGERDAT%TYPE ;
PRAGMA RESTRICT_REFERENCES(READLEDGERDATE,   WNDS,   WNPS);

/*+RESCATA DIRECCIoN POR LA LLAVE CON SUS CORRESPONDIENTES FILTRACIONES */
FUNCTION REAADDRESS_KEY(NRECOWNER       ADDRESS.NRECOWNER%TYPE,
                        SKEYADDRESS     ADDRESS.SKEYADDRESS%TYPE,
                        DEFFECDATE      ADDRESS.DEFFECDATE%TYPE)
                        RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REAADDRESS_KEY,  WNDS,   WNPS);

/*+RESCATA DIRECCIoN POR LA LLAVE CON SUS CORRESPONDIENTES FILTRACIONES */
FUNCTION REAADDRESS_KEY_2(NRECOWNER       ADDRESS.NRECOWNER%TYPE,
                          SKEYADDRESS     ADDRESS.SKEYADDRESS%TYPE,
                          DEFFECDATE      ADDRESS.DEFFECDATE%TYPE)
                          RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REAADDRESS_KEY_2,  WNDS,   WNPS);

/*+RESCATA DIRECCIoN POR LA LLAVE CON SUS CORRESPONDIENTES FILTRACIONES */
FUNCTION REAADDRESS_KEY_3(SKEYADDRESS     ADDRESS.SKEYADDRESS%TYPE)
                          RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REAADDRESS_KEY_3,  WNDS,   WNPS);

/*+RESCATA DIRECCIoN DEL CLIENTE */
FUNCTION REAADDRESS(NRECOWNER       ADDRESS.NRECOWNER%TYPE,
                    SCLIENT         ADDRESS.SCLIENT%TYPE,
                    DDATE           VARCHAR2)
                    RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REAADDRESS,  WNDS,   WNPS);

/*+RESCATA DIRECCION DEL CLIENTE  COBRO*/
FUNCTION REAADDBILLS(NRECOWNER       ADDRESS.NRECOWNER%TYPE,
                     SCLIENT         ADDRESS.SCLIENT%TYPE,
                     DEFFECDATE     ADDRESS.DEFFECDATE%TYPE)
                     RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REAADDBILLS,  WNDS,   WNPS);

/*+RESCATA DIRECCION DEL CLIENTE  COBRO*/
FUNCTION REAADDBILLS_2(NRECOWNER       ADDRESS.NRECOWNER%TYPE,
                       SCLIENT         ADDRESS.SCLIENT%TYPE,
                       DEFFECDATE      ADDRESS.DEFFECDATE%TYPE)
                       RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REAADDBILLS_2,  WNDS,   WNPS);


FUNCTION REAADDRESSLOC(NRECOWNER       ADDRESS.NRECOWNER%TYPE,
                       SCLIENT         ADDRESS.SCLIENT%TYPE,
                       DDATE           DATE)
                    RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REAADDRESSLOC,  WNDS,   WNPS);

/*+RESCATA NOMBRE DEL CLIENTE */
FUNCTION REANAMECLI(SCLIENT         CLIENT.SCLIENT%TYPE)
                    RETURN          CLIENT.SCLIENAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REANAMECLI,  WNDS,   WNPS);

/*+RESCATA SI ES BENEFICIARIO EL CLIENTE */
FUNCTION REACLIENTBENEF(SCERTYPE    ROLES.SCERTYPE%TYPE,
                         NBRANCH     ROLES.NBRANCH%TYPE,
                         NPRODUCT    ROLES.NPRODUCT%TYPE,
                         NPOLICY     ROLES.NPOLICY%TYPE,
                         NCERTIF     ROLES.NCERTIF%TYPE,
                         DEFFECDATE  ROLES.DEFFECDATE%TYPE,
                         SCLIENT     ROLES.NROLE%TYPE)
                         RETURN      ROLES.NROLE%TYPE;
PRAGMA RESTRICT_REFERENCES(REACLIENTBENEF,  WNDS,   WNPS);

/*+RESCATA LA FECHA DE NACIMIENTO DEL CLIENTE */
FUNCTION READBIRTHDAT(SCLIENT         CLIENT.SCLIENT%TYPE)
                    RETURN            CLIENT.DBIRTHDAT%TYPE;
PRAGMA RESTRICT_REFERENCES(READBIRTHDAT,  WNDS,   WNPS);


/*+RESCATA NOMBRE DEL CLIENTE CON FORMATO "CODIGO - DIGITO NOMBRE */
FUNCTION REANAMECLI_COD(SCLIENT         CLIENT.SCLIENT%TYPE)
                        RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REANAMECLI_COD,  WNDS,   WNPS);

/*+RESCATA NOMBRE DEL CLIENTE CON FORMATO "CODIGO - DIGITO NOMBRE PARA UN USUARIO */
FUNCTION REANAMECLI_USERS(NUSERCODE        USERS.NUSERCODE%TYPE)
                        RETURN          VARCHAR2;

PRAGMA RESTRICT_REFERENCES(REANAMECLI_USERS,  WNDS,   WNPS);

/*+RESCATA NOMBRE DEL CLIENTE CON FORMATO "CODIGO - DIGITO NOMBRE */
FUNCTION REANAMECLI_RUT(SCLIENT         CLIENT.SCLIENT%TYPE)
                        RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REANAMECLI_RUT,  WNDS,   WNPS);

/*+RESCATA DIGITO VERIFICADOR DEL CLIENTE */
FUNCTION REACALDIGIT(SCLIENT         CLIENT.SCLIENT%TYPE)
                     RETURN          CLIENT.SDIGIT%TYPE;
PRAGMA RESTRICT_REFERENCES(REACALDIGIT,  WNDS,   WNPS);

/*+RESCATA DESCRIPCIoN DEL RAMO */
FUNCTION REASBRANCH(NBRANCH         TABLE10.NBRANCH%TYPE)
                    RETURN          TABLE10.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASBRANCH,  WNDS,   WNPS);

/*+RESCATA DESCRIPCIoN DEL RAMO DESCRIPCION CORTA */
FUNCTION REASBRANCHSH(NBRANCH       TABLE10.NBRANCH%TYPE)
                      RETURN        TABLE10.SSHORT_DES%TYPE;
PRAGMA RESTRICT_REFERENCES(REASBRANCHSH,  WNDS,   WNPS);

/*+RESCATA DESCRIPCIoN DEL PRODUCTO */
FUNCTION REASPRODUCT(NBRANCH        PRODMASTER.NBRANCH%TYPE,
                     NPRODUCT       PRODMASTER.NPRODUCT%TYPE)
                     RETURN         PRODMASTER.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASPRODUCT, WNDS,   WNPS);

/*+RESCATA DESCRIPCIoN CORTA DEL PRODUCTO */
FUNCTION REASPRODUCTSH(NBRANCH        PRODMASTER.NBRANCH%TYPE,
                       NPRODUCT       PRODMASTER.NPRODUCT%TYPE)
                       RETURN         PRODMASTER.SSHORT_DES%TYPE;
PRAGMA RESTRICT_REFERENCES(REASPRODUCTSH, WNDS,   WNPS);

/*+RESCATA DESCRIPCIoN DEL BANCO */
FUNCTION REASBANK_CODE(NBANK_CODE   TABLE7.NBANK_CODE%TYPE)
                       RETURN       TABLE7.SDESCRIPT%TYPE;

/*+RESCATA DESCRIPCIoN CORTA DEL BANCO */
FUNCTION REASBANK_CODESH(NBANK_CODE   TABLE7.NBANK_CODE%TYPE)
                       RETURN       TABLE7.SDESCRIPT%TYPE;

/*+RESCATA EL CODIGO DEL BANCO  ASOCIADO A UNA POLIZA*/
FUNCTION REAPOLICYBANK_CODE(P_SCERTYPE   POLICY_HIS.SCERTYPE%TYPE,
                            P_NBRANCH    POLICY_HIS.NBRANCH%TYPE,
                            P_NPRODUCT   POLICY_HIS.NPRODUCT%TYPE,
                            P_NPOLICY    POLICY_HIS.NPOLICY%TYPE,
                            P_NCERTIF    POLICY_HIS.NCERTIF%TYPE,
                            P_DEFFECDATE POLICY_HIS.DEFFECDATE%TYPE DEFAULT NULL)
                            RETURN       TABLE7.NBANK_CODE%TYPE;

PRAGMA RESTRICT_REFERENCES(REASBANK_CODE, WNDS, WNPS);

/*+RESCATA DESCRIPCION LARGA DE LA MONEDA */
FUNCTION REASCURRENCY(NCURRENCY     TABLE11.NCODIGINT%TYPE)
                      RETURN        TABLE11.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASCURRENCY, WNDS, WNPS);

/*+RESCATA DESCRIPCIoN CORTA DE LA MONEDA */
FUNCTION REASCURRENCYSH(NCURRENCY   TABLE11.NCODIGINT%TYPE)
                        RETURN      TABLE11.SSHORT_DES%TYPE;
PRAGMA RESTRICT_REFERENCES(REASCURRENCYSH, WNDS, WNPS);

/*+RESCATA EL ESTADO DEL RECIBO O CUOTA */
FUNCTION REASTATE(NSTATUS           TABLE253.NSTAT_DRAFT%TYPE,
                  NCONTRAT          PREMIUM.NCONTRAT%TYPE)
                  RETURN            TABLE253.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASTATE,    WNDS,   WNPS);

/*+RESCATA EL PHONO1 DE UN CLIENTE  */
FUNCTION REAPHONES1(NRECOWNER       PHONES.NRECOWNER%TYPE,
                    SKEYADDRESS     PHONES.SKEYADDRESS%TYPE,
                    NKEYPHONES      PHONES.NKEYPHONES%TYPE,
                    DEFFECDATE      PHONES.DEFFECDATE%TYPE)
                    RETURN          PHONES.SPHONE%TYPE;
PRAGMA RESTRICT_REFERENCES(REAPHONES1,  WNDS,   WNPS);

/*+RESCATA EL LA DESCRIPCIoN DEL BANCO   */
PROCEDURE REABANK(NBANK             TABLE7.NBANK_CODE%TYPE,
                  SDESC_BANK        OUT TABLE7.SDESCRIPT%TYPE);
PRAGMA RESTRICT_REFERENCES(REABANK,     WNDS,   WNPS);

/*+RESCATA DESCRIPCION DEL MODULO*/
FUNCTION REASMODULEC(NBRANCH    TAB_MODUL.NBRANCH%TYPE,
                     NPRODUCT   TAB_MODUL.NPRODUCT%TYPE,
                     NMODULEC   TAB_MODUL.NMODULEC%TYPE,
                     DEFFECDATE TAB_MODUL.DEFFECDATE%TYPE)
                     RETURN TAB_MODUL.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASMODULEC,     WNDS,   WNPS);

FUNCTION REASGROUPS
    (SCERTYPE   GROUPS.SCERTYPE%TYPE,
     NBRANCH    GROUPS.NBRANCH%TYPE,
     NPRODUCT   GROUPS.NPRODUCT%TYPE,
     NGROUP     GROUPS.NGROUP%TYPE,
     DEFFECDATE GROUPS.DEFFECDATE%TYPE)
     RETURN GROUPS.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASGROUPS,     WNDS,   WNPS);

/*+RESCATA DESCRIPCION CORTA DEL MODULO*/
FUNCTION REASMODULECSH(NBRANCH    TAB_MODUL.NBRANCH%TYPE,
                       NPRODUCT   TAB_MODUL.NPRODUCT%TYPE,
                       NMODULEC   TAB_MODUL.NMODULEC%TYPE,
                       DEFFECDATE TAB_MODUL.DEFFECDATE%TYPE)
                       RETURN TAB_MODUL.SSHORT_DES%TYPE;
PRAGMA RESTRICT_REFERENCES(REASMODULECSH,     WNDS,   WNPS);

/*+RESCATA DESCRIPCION DE LA COBERTURA*/
FUNCTION REASCOVER(NLIFE      NUMBER,
                   NCOVERGEN  TAB_LIFCOV.NCOVERGEN%TYPE,
                   NBRANCH    LIFE_COVER.NBRANCH%TYPE DEFAULT NULL,
                   NPRODUCT   LIFE_COVER.NPRODUCT%TYPE DEFAULT NULL,
                   NMODULEC   LIFE_COVER.NMODULEC%TYPE DEFAULT NULL,
                   NCOVER     LIFE_COVER.NCOVER%TYPE DEFAULT NULL,
                   DEFFECDATE LIFE_COVER.DEFFECDATE%TYPE DEFAULT NULL)
                   RETURN TAB_LIFCOV.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASCOVER,     WNDS,   WNPS);

/*+RESCATA EL CÓDIGO DE LA COBERTURA*/
FUNCTION REASCOVERGEN( NBRANCH    LIFE_COVER.NBRANCH%TYPE,
                   NPRODUCT   LIFE_COVER.NPRODUCT%TYPE,
                   NMODULEC   LIFE_COVER.NMODULEC%TYPE DEFAULT NULL,
                   NCOVER     LIFE_COVER.NCOVER%TYPE DEFAULT NULL,
                   DEFFECDATE LIFE_COVER.DEFFECDATE%TYPE DEFAULT NULL)
                   RETURN TAB_GENCOV.NCOVERGEN%TYPE;
PRAGMA RESTRICT_REFERENCES(REASCOVERGEN,     WNDS,   WNPS);

/*+RESCATA DESCRIPCION CORTA DE LA COBERTURA*/
FUNCTION REASCOVERSH(NLIFE      NUMBER,
                     NCOVERGEN  TAB_LIFCOV.NCOVERGEN%TYPE,
                     NBRANCH    LIFE_COVER.NBRANCH%TYPE DEFAULT NULL,
                     NPRODUCT   LIFE_COVER.NPRODUCT%TYPE DEFAULT NULL,
                     NMODULEC   LIFE_COVER.NMODULEC%TYPE DEFAULT NULL,
                     NCOVER     LIFE_COVER.NCOVER%TYPE DEFAULT NULL,
                     DEFFECDATE LIFE_COVER.DEFFECDATE%TYPE DEFAULT NULL)
                     RETURN TAB_LIFCOV.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASCOVERSH,     WNDS,   WNPS);

/*+RETORNA DESCRIPCION DE LA FIGURA DE CLIENTE */
FUNCTION REASROLE(NROLES  TABLE12.NROLE%TYPE)
                  RETURN  TABLE12.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASROLE,     WNDS,   WNPS);

/*+RETORNA TASA DE CAMBIO DE MONEDA RESPECTO A MONEDA LOCAL  */
FUNCTION REAEXCHANGELOCAL(NCURRENCY  EXCHANGE.NCURRENCY%TYPE,
                          DEFFECDATE EXCHANGE.DEFFECDATE%TYPE)
                   RETURN EXCHANGE.NEXCHANGE%TYPE;
PRAGMA RESTRICT_REFERENCES(REAEXCHANGELOCAL,  WNDS,   WNPS);

/*+RETORNA MONTO CONVERTIDO A MONEDA ORIGEN     */
FUNCTION CONVERTEXCHANGE(NEXCHANGE  EXCHANGE.NEXCHANGE%TYPE,
                         NAMOUNTORI NUMBER,
                         NCURORI    EXCHANGE.NCURRENCY%TYPE,
                         NCURDES    EXCHANGE.NCURRENCY%TYPE,
                         DEFFECDATE EXCHANGE.DEFFECDATE%TYPE)
                         RETURN NUMBER;
PRAGMA RESTRICT_REFERENCES(CONVERTEXCHANGE,  WNDS,   WNPS);

/*+RETORNA DESCRIPCION DE LA SUCURSALES/ZONAS (OFICINA) */
FUNCTION REASOFFICE(NOFFICE  TABLE9.NOFFICE%TYPE)
                    RETURN   TABLE9.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASOFFICE,     WNDS,   WNPS);

/*+RETORNA DESCRIPCION DE LA AGENCIA (NAGENCY) */
FUNCTION REASAGENCY(NAGENCY  TABLE5555.NAGENCY%TYPE)
                    RETURN   TABLE5555.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASAGENCY,     WNDS,   WNPS);

/*+RETORNA DESCRIPCION DEL TIPOS DE MOVIMIENTOS DE CUENTAS CORRIENTE */
FUNCTION REASTYPE_MOVE(NTYPE_MOVE  TABLE401.NTYPE_MOVE%TYPE)
                       RETURN      TABLE401.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASTYPE_MOVE,     WNDS,   WNPS);

/*+RETORNA DESCRIPCION DEL TIPOS DE MOVIMIENTOS DE CUENTAS CORRIENTE VUL*/
FUNCTION REASTYPE_MOVEVUL(NTYPE_MOVE  TABLE5708.NTYPE_MOVE%TYPE)
                          RETURN      TABLE5708.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASTYPE_MOVEVUL,     WNDS,   WNPS);

/*+RETORNA DESCRIPCION CORTA DEL TIPOS DE MOVIMIENTOS DE CUENTAS CORRIENTE */
FUNCTION REASTYPE_MOVESH(NTYPE_MOVE  TABLE401.NTYPE_MOVE%TYPE)
                         RETURN      TABLE401.SSHORT_DES%TYPE;
PRAGMA RESTRICT_REFERENCES(REASTYPE_MOVESH,     WNDS,   WNPS);

/*+RETORNA DESCRIPCION DE LA INFORMACIoN SOBRE LAS CIUDADES DEL PAiS. */
FUNCTION REASLOCAL(NLOCAL  TAB_LOCAT.NLOCAL%TYPE)
                   RETURN  TAB_LOCAT.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASLOCAL,     WNDS,   WNPS);

/*+RESCATA DESCRIPCION DE LOS RECARGOS/DESCUENTOS/IMPUESTOS*/
FUNCTION REASDISCO_EXPR(NBRANCH    DISCO_EXPR.NBRANCH%TYPE,
                        NPRODUCT   DISCO_EXPR.NPRODUCT%TYPE,
                        NDISEXPRC  DISCO_EXPR.NDISEXPRC%TYPE,
                        DEFFECDATE LIFE_COVER.DEFFECDATE%TYPE)
                       RETURN DISCO_EXPR.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASDISCO_EXPR,     WNDS,   WNPS);

/*+RESCATA DESCRIPCION DE LOS TIPOS DE ENDOSO */
FUNCTION REASTYPE_AMEND(NBRANCH      TYPE_AMEND.NBRANCH%TYPE,
                        NPRODUCT     TYPE_AMEND.NPRODUCT%TYPE,
                        NTYPE_AMEND  TYPE_AMEND.NTYPE_AMEND%TYPE,
                        DEFFECDATE   TYPE_AMEND.DEFFECDATE%TYPE)
                       RETURN TABLE6059.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASTYPE_AMEND,     WNDS,   WNPS);

/*+ RESCATA DESCRIPCION DE UNA TABLA GENERICA */
FUNCTION REANCODIGINT(NTABLE    NUMBER,
                      SFIELD    VARCHAR2,
                      NCODIGINT NUMBER DEFAULT NULL,
                      SCODIGINT VARCHAR2 DEFAULT NULL)
                    RETURN TABLE11.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REANCODIGINT,     WNDS,   WNPS);

/*+ RESCATA DESCRIPCION LARGA DE UNA TABLA GENERICA */
FUNCTION REACODIGINT(STABLE    VARCHAR2,
                     SFIELD    VARCHAR2,
                     NCODIGINT NUMBER DEFAULT NULL,
                     SCODIGINT VARCHAR2 DEFAULT NULL)
                    RETURN VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REACODIGINT,     WNDS,   WNPS);

/*+ RESCATA DESCRIPCION CORTA DE UNA TABLA GENERICA */
FUNCTION REACODIGINTSH(STABLE    VARCHAR2,
                       SFIELD    VARCHAR2,
                       NCODIGINT NUMBER DEFAULT NULL,
                       SCODIGINT VARCHAR2 DEFAULT NULL)
                      RETURN TABLE10.SSHORT_DES%TYPE DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(REACODIGINTSH,     WNDS,   WNPS);

/*+ RETORNA "SI" O "NO" DEPENDIENDO DEL PARAMETRO DE ENTRADA  (1 O 2 RESPECTIVAMENTE) */
FUNCTION GETYESORNO(SIND CLIENT.SSMOKING%TYPE)
                    RETURN VARCHAR2;
PRAGMA RESTRICT_REFERENCES(GETYESORNO,     WNDS,   WNPS);

/*+ RECUPERA EL NOMBRE DE LA TABLA DE DATOS PARTICULARES DEL RAMO   */
FUNCTION REATAB_NAME_B(NBRANCH  TAB_NAME_B.NBRANCH%TYPE)
                       RETURN   TAB_NAME_B.STABNAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REATAB_NAME_B,     WNDS,   WNPS);

/*+ INDICA SI EL PRODUCTO ES MODULAR O NO (1: SI, 2: NO)            */
FUNCTION REAINDMODULPRODUCT(NBRANCH    TAB_MODUL.NBRANCH%TYPE,
                            NPRODUCT   TAB_MODUL.NPRODUCT%TYPE,
                            DEFFECDATE TAB_MODUL.DEFFECDATE%TYPE)
                            RETURN   VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REAINDMODULPRODUCT,     WNDS,   WNPS);

/*+RESCATA NOMBRE DEL INTERMEDIARIO */
FUNCTION REANAMEINTERMED(NINTERMED  INTERMEDIA.NINTERMED%TYPE)
                         RETURN        CLIENT.SCLIENAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REANAMEINTERMED,  WNDS,   WNPS);

/*+RESCATA NOMBRE DEL INTERMEDIARIO */
FUNCTION REANAMECOLLECTOR(NCOLLECTOR  COLLECTOR.NCOLLECTOR%TYPE)
                         RETURN       CLIENT.SCLIENAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REANAMECOLLECTOR,  WNDS,   WNPS);

/*+RESCATA EL TIPO DEL INTERMEDIARIO */
FUNCTION REATYPINTERMED(NINTERMED  INTERMEDIA.NINTERMED%TYPE)
                        RETURN     INTERMEDIA.NINTERTYP%TYPE;
PRAGMA RESTRICT_REFERENCES(REATYPINTERMED,  WNDS,   WNPS);


/*+RESCATA EL CLIENT DEL INTERMEDIARIO */
FUNCTION REACLIENTINTERMED(NINTERMED  INTERMEDIA.NINTERMED%TYPE)
                    RETURN        CLIENT.SCLIENT%TYPE;
PRAGMA RESTRICT_REFERENCES(REACLIENTINTERMED,  WNDS,   WNPS);

/*+RESCATA EL SUPERVISOR DEL INTERMEDIARIO */
FUNCTION REASUPERVINTERMED(NINTERMED  INTERMEDIA.NINTERMED%TYPE)
                           RETURN     INTERMEDIA.NSUPERVIS%TYPE;
PRAGMA RESTRICT_REFERENCES(REASUPERVINTERMED,  WNDS,   WNPS);

/*+RESCATA NOMBRE DEL TIPO DEL INTERMEDIARIO */
FUNCTION REANAMEINTERTYP(NINTERTYP  INTERM_TYP.NINTERTYP%TYPE)
                         RETURN     INTERM_TYP.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REANAMEINTERTYP,  WNDS,   WNPS);

/*+RESCATA NOMBRE DE LA COMPA?IA */
FUNCTION REANAMECOMPANY(NCOMPANY  COMPANY.NCOMPANY%TYPE,
                         SOPTION    CHAR DEFAULT '1')
                        RETURN    CLIENT.SCLIENAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REANAMECOMPANY,  WNDS,   WNPS);

/*+ RESCATA LA DESCRIPCION DE LAS SUCURSALES ASOCIADAS A COMPA?iAS.*/
FUNCTION OFFICEINSNAME(NCOMPANY FINANC_PRE.NCOMPANY%TYPE,
                       NOFFICE  FINANC_PRE.NOFFICE%TYPE)
                       RETURN   CLIENT.SCLIENAME%TYPE;
PRAGMA RESTRICT_REFERENCES(OFFICEINSNAME,  WNDS,   WNPS);

/*+ RESCATA LA SUMA DE LAS COMISIONES DE RECIBOS DE CONTRATOS */
FUNCTION COMMISFINANC_PRE(NCONTRAT FINANC_PRE.NCONTRAT%TYPE)
                          RETURN   FINANC_PRE.NCOMMISSION%TYPE;
PRAGMA RESTRICT_REFERENCES(COMMISFINANC_PRE,  WNDS,   WNPS);

/*+RESCATA EL CLIENTE DE LA COMPA?IA */
FUNCTION REACLIENTCOMPANY(NCOMPANY  COMPANY.NCOMPANY%TYPE)
                          RETURN    CLIENT.SCLIENT%TYPE;
PRAGMA RESTRICT_REFERENCES(REACLIENTCOMPANY,  WNDS,   WNPS);

/*+RESCATA EL CLIENTE DEL CONVENIO*/
FUNCTION REACLIENTAGREEMENT (NCOD_AGREE AGREEMENT.NCOD_AGREE%TYPE)
                             RETURN  CLIENT.SCLIENT%TYPE;
PRAGMA RESTRICT_REFERENCES(REACLIENTAGREEMENT,  WNDS,   WNPS);

/*+RESCATA EL SEXO DEL CLIENTE QUE SE ENCUENTRA EN ROLES */
FUNCTION REASEXCLIENT(NBRANCH     ROLES.NBRANCH%TYPE,
                      NPRODUCT    ROLES.NPRODUCT%TYPE,
                      NPOLICY     ROLES.NPOLICY%TYPE,
                      NCERTIF     ROLES.NCERTIF%TYPE,
                      SCLIENT     ROLES.SCLIENT%TYPE,
                      DEFFECDATE  ROLES.DEFFECDATE%TYPE)
                      RETURN  ROLES.SSEXCLIEN%TYPE;
PRAGMA RESTRICT_REFERENCES(REASEXCLIENT,  WNDS,   WNPS);

/*+RESCATA EL NUMERO DE BENEFICIARIOS QUE SE ENCUENTRA EN ROLES */
FUNCTION REANUMBENEF(NBRANCH     ROLES.NBRANCH%TYPE,
                      NPRODUCT    ROLES.NPRODUCT%TYPE,
                      NPOLICY     ROLES.NPOLICY%TYPE,
                      NCERTIF     ROLES.NCERTIF%TYPE,
                      SCLIENT     ROLES.SCLIENT%TYPE,
                      DEFFECDATE  ROLES.DEFFECDATE%TYPE)
                      RETURN  INTEGER;
PRAGMA RESTRICT_REFERENCES(REANUMBENEF,  WNDS,   WNPS);

/*+DEVUELVE EL APELLIDO PATERNO DEL CLIENTE*/
FUNCTION REASLASTNAME(SCLIENT CLIENT.SCLIENT%TYPE)
                      RETURN  CLIENT.SLASTNAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REASLASTNAME,  WNDS,   WNPS);

/*+DEVUELVE EL APELLIDO MATERNO DEL CLIENTE*/
FUNCTION REASLASTNAME2(SCLIENT CLIENT.SCLIENT%TYPE)
                       RETURN  CLIENT.SLASTNAME2%TYPE;
PRAGMA RESTRICT_REFERENCES(REASLASTNAME2,  WNDS,   WNPS);

/*+DEVUELVE EL 1 NOMBRE DEL CLIENTE*/
FUNCTION REASFIRSTNAME(SCLIENT CLIENT.SCLIENT%TYPE)
                       RETURN  CLIENT.SFIRSTNAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REASFIRSTNAME,  WNDS,   WNPS);


/*+SE BUSCA EL TIPO DE PRODUCTO*/
FUNCTION REAPRODUCTLI(NBRANCH     PRODUCT_LI.NBRANCH%TYPE,
                      NPRODUCT    PRODUCT_LI.NPRODUCT%TYPE,
                      DEFFECDATE  PRODUCT_LI.DEFFECDATE%TYPE)
                      RETURN      PRODUCT_LI.NPRODCLAS%TYPE;
PRAGMA RESTRICT_REFERENCES(REAPRODUCTLI,  WNDS,   WNPS);

/*+RESCATA LA DESCRIPCION DE UN MENSAJE */
FUNCTION REAMESSAGE(NERRORNUM MESSAGE.NERRORNUM%TYPE)
                    RETURN MESSAGE.SMESSAGED%TYPE;
PRAGMA RESTRICT_REFERENCES(REAMESSAGE,  WNDS,   WNPS);

/*+RETORNA DESCRIPCION DE UNA OFICINA */
FUNCTION REASOFFICEAGEN(NOFFICEAGEN  TABLE5556.NOFFICEAGEN%TYPE)
                        RETURN       TABLE5556.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASOFFICEAGEN,     WNDS,   WNPS);

/*+ RECUPERA EL TIPO DE PERDIDA ASOCIADA A UNA CAUSA EN UN SINIESTRO */
FUNCTION REASCLAIMTYP(NBRANCH   CLAIM_CAUS.NBRANCH%TYPE,
                      NPRODUCT  CLAIM_CAUS.NPRODUCT%TYPE,
                      NCAUSECOD CLAIM_CAUS.NCAUSECOD%TYPE)
                      RETURN CLAIM_CAUS.SCLAIMTYP%TYPE;
PRAGMA RESTRICT_REFERENCES(REASCLAIMTYP,  WNDS,   WNPS);

FUNCTION  REACLAIMBENEFDEM (NCLAIM       CLAIMBENEF.NCLAIM%TYPE,
                            NCASE_NUM    CLAIMBENEF.NCASE_NUM%TYPE,
                            NDEMAN_TYPE  CLAIMBENEF.NDEMAN_TYPE%TYPE)
                            RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(REACLAIMBENEFDEM,  WNDS,   WNPS);

FUNCTION  REACLAIMBENEFCLIENT (NCLAIM       CLAIMBENEF.NCLAIM%TYPE,
                               NCASE_NUM    CLAIMBENEF.NCASE_NUM%TYPE,
                               NDEMAN_TYPE  CLAIMBENEF.NDEMAN_TYPE%TYPE,
                               NBENE_TYPE    CLAIMBENEF.NBENE_TYPE%TYPE)
                               RETURN CLAIMBENEF.SCLIENT%TYPE;

PRAGMA RESTRICT_REFERENCES(REACLAIMBENEFCLIENT,  WNDS,   WNPS);


FUNCTION  REACLAIMBENEFCLIENAME (NCLAIM       CLAIMBENEF.NCLAIM%TYPE,
                                 NCASE_NUM    CLAIMBENEF.NCASE_NUM%TYPE,
                                 NDEMAN_TYPE  CLAIMBENEF.NDEMAN_TYPE%TYPE,
                                 NBENE_TYPE    CLAIMBENEF.NBENE_TYPE%TYPE)
                                 RETURN CLIENT.SCLIENAME%TYPE;

PRAGMA RESTRICT_REFERENCES(REACLAIMBENEFCLIENAME,  WNDS,   WNPS);


FUNCTION  REANAMEPROVIDER (NPROVIDER    TAB_PROVIDER.NPROVIDER%TYPE)
                           RETURN CLIENT.SCLIENAME%TYPE;

PRAGMA RESTRICT_REFERENCES(REANAMEPROVIDER,  WNDS,   WNPS);

/*+RESCATA LA DESCRIPCION DEL CONVENIO-DESCUENTO POR PLANILLA */
FUNCTION REASCOD_AGREE(NCOD_AGREE   AGREEMENT.NCOD_AGREE%TYPE)
                       RETURN       VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REASCOD_AGREE,  WNDS,   WNPS);

/*+RESCATA LA DESCRIPCION DEL CONVENIO-DESCUENTO POR PLANILLA */
FUNCTION REASACC_NUMBER(NBANK_CODE BANK_ACC.NBANK_CODE%TYPE,
                        NACC_BANK  BANK_ACC.NACC_BANK%TYPE)
                        RETURN     BANK_ACC.SACC_NUMBER%TYPE;
PRAGMA RESTRICT_REFERENCES(REASACC_NUMBER,  WNDS,   WNPS);

/*+RESCATA LA DESCRIPCION AGENCIA */
FUNCTION REASBK_AGENCY(NBANK_CODE TAB_BK_AGE.NBANK_CODE%TYPE,
                       NBK_AGENCY TAB_BK_AGE.NBK_AGENCY%TYPE)
                       RETURN     TAB_BK_AGE.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASBK_AGENCY,  WNDS,   WNPS);

/*+RESCATA LA DESCRIPCION AGENCIA Y CUENTA DE UNA CUENTA BANCARIA */
FUNCTION REASACC_BANK_AGCTA(NACC_BANK  BANK_ACC.NACC_BANK%TYPE)
                            RETURN     VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REASACC_BANK_AGCTA,  WNDS,   WNPS);

/*+RESCATA LA PRIMA ANUAL DE UNA POLIZA */
FUNCTION REANPREMANUAL( SCERTYPE    DETAIL_PRE.SCERTYPE   %TYPE ,
                        NPOLICY     PREMIUM.NPOLICY       %TYPE ,
                        NCERTIF     PREMIUM.NCERTIF       %TYPE ,
                        NBRANCH     DETAIL_PRE.NBRANCH    %TYPE ,
                        NPRODUCT    DETAIL_PRE.NPRODUCT   %TYPE )
                        RETURN DETAIL_PRE.NPREMANUAL%TYPE;

PRAGMA RESTRICT_REFERENCES(REANPREMANUAL,  WNDS,   WNPS);

/*+RESCATA LA PRIMA AFECTA,EXCENTA E IVA DE LA TABLA DETAIL_PRE*/
FUNCTION REANSUMDETAIL( SCERTYPE    DETAIL_PRE.SCERTYPE%TYPE ,
                        NBRANCH     DETAIL_PRE.NBRANCH%TYPE ,
                        NPRODUCT    DETAIL_PRE.NPRODUCT%TYPE,
                        NRECEIPT    DETAIL_PRE.NRECEIPT%TYPE ,
                        NPAYNUMBE   DETAIL_PRE.NPAYNUMBE%TYPE ,
                        NDIGIT      DETAIL_PRE.NDIGIT%TYPE ,
                        SADDTAX    DETAIL_PRE.SADDTAX%TYPE )
                        RETURN DETAIL_PRE.NPREMANUAL%TYPE;

PRAGMA RESTRICT_REFERENCES(REANSUMDETAIL,  WNDS,   WNPS);

/*+RESCATA EL MENOR CODIGO DEL MODULO ASOCIADO A LA POLIZA */
FUNCTION REAMINMODULEC( SCERTYPE    MODULES.SCERTYPE    %TYPE ,
                        NPOLICY     MODULES.NPOLICY     %TYPE ,
                        NCERTIF     MODULES.NCERTIF     %TYPE ,
                        NBRANCH     MODULES.NBRANCH     %TYPE ,
                        NPRODUCT    MODULES.NPRODUCT    %TYPE ,
                        DDATE       MODULES.DEFFECDATE  %TYPE )
                        RETURN MODULES.NMODULEC%TYPE;
PRAGMA RESTRICT_REFERENCES(REAMINMODULEC,  WNDS,   WNPS);

FUNCTION REAMINPROFORD( SCERTYPE    PROF_ORD.SCERTYPE    %TYPE ,
                        NPOLICY     PROF_ORD.NPOLICY     %TYPE ,
                        NCERTIF     PROF_ORD.NCERTIF     %TYPE ,
                        NBRANCH     PROF_ORD.NBRANCH     %TYPE ,
                        NPRODUCT    PROF_ORD.NPRODUCT    %TYPE )
                        RETURN PROF_ORD.DMADE_DATE%TYPE;
PRAGMA RESTRICT_REFERENCES(REAMINPROFORD,  WNDS,   WNPS);


/*+RESCATA DESCRIPCION DE LAS ENTIDADES FINANCIERAS */
FUNCTION REASINSTITUTION(NINSTITUTION  TAB_FN_INSTITUTION.NINSTITUTION%TYPE)
                         RETURN        TAB_FN_INSTITUTION.SNAME%TYPE;
PRAGMA RESTRICT_REFERENCES(REASINSTITUTION, WNDS, WNPS);

/*+RESCATA DESCRIPCION DE LOS PRESTAMOS/ANTICIPOS DE UN INTERMEDIARIO */
FUNCTION REASLOANSBPS(NINTERMED  LOANS_INT.NINTERMED%TYPE,
                      NLOAN      LOANS_INT.NLOAN%TYPE)
                      RETURN     VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REASLOANSBPS, WNDS, WNPS);

/*+RESCATA LA MONEDA DEL CONTRATO DE FINANCIAMIENTO */
FUNCTION REACURRFINANCE_CO(NCONTRAT FINANCE_CO.NCONTRAT%TYPE)
                      RETURN     FINANCE_CO.NCURRENCY%TYPE;
PRAGMA RESTRICT_REFERENCES(REACURRFINANCE_CO, WNDS, WNPS);

/*+RESCATA LA MONEDA DEL CONTRATO DE FINANCIAMIENTO */
FUNCTION REABILL_NOTECRED(NNOTECRED  BILLS.NBILLNUM%TYPE,
                          NINSURAREA BILLS.NINSUR_AREA%TYPE,
                          SBILLTYPE  BILLS.SBILLTYPE%TYPE)
                      RETURN  BILLS.NBILLNUM%TYPE;
PRAGMA RESTRICT_REFERENCES(REABILL_NOTECRED, WNDS, WNPS);

/*+ RESCATA LA MAYOR FECHA PAGADO HASTA DE UNA POLIZA EN PARTICULAR */
FUNCTION REAPAYLIMIT( SCERTYPE  PREMIUM.SCERTYPE%TYPE,
                      NPOLICY   PREMIUM.NPOLICY%TYPE,
                      NBRANCH   PREMIUM.NBRANCH%TYPE,
                      NPRODUCT  PREMIUM.NPRODUCT%TYPE,
                      NCERTIF   PREMIUM.NCERTIF%TYPE)
                      RETURN   DATE;
PRAGMA RESTRICT_REFERENCES(REAPAYLIMIT, WNDS, WNPS);

FUNCTION REANPREMDEV(SCERTYPE  PREMIUM.SCERTYPE%TYPE,
                     NPOLICY   PREMIUM.NPOLICY%TYPE,
                     NBRANCH   PREMIUM.NBRANCH%TYPE,
                     NPRODUCT  PREMIUM.NPRODUCT%TYPE,
                     DDATEFROM PREMIUM.DLIMITDATE%TYPE,
                     DDATETO   PREMIUM.DLIMITDATE%TYPE)
                      RETURN   PREMIUM.NPREMIUM%TYPE;
PRAGMA RESTRICT_REFERENCES(REANPREMDEV, WNDS, WNPS);

FUNCTION REACURRPOL( SCERTYPE  CURREN_POL.SCERTYPE%TYPE,
                     NBRANCH   CURREN_POL.NBRANCH%TYPE,
                     NPRODUCT  CURREN_POL.NPRODUCT%TYPE,
                     NPOLICY   CURREN_POL.NPOLICY%TYPE,
                     NCERTIF   CURREN_POL.NCERTIF%TYPE,
                     DDATEREP  DATE)
                      RETURN     CURREN_POL.NCURRENCY%TYPE;
PRAGMA RESTRICT_REFERENCES(REACURRPOL, WNDS, WNPS);

/*+RESCATA EL CLIENTE DEL CONVENIO*/
FUNCTION REATYPEAGREE (NCOD_AGREE AGREEMENT.NCOD_AGREE%TYPE)
                       RETURN  AGREEMENT.NTYPEAGREE%TYPE;
PRAGMA RESTRICT_REFERENCES(REATYPEAGREE,  WNDS,   WNPS);

/*+RESCATA EL NRO DE CUENTA DE LA POLIZA*/
FUNCTION REA_SACCOUNT (SCERTYPE    DIR_DEBIT.SCERTYPE%TYPE,
                       NBRANCH     DIR_DEBIT.NBRANCH%TYPE ,
                       NPRODUCT    DIR_DEBIT.NPRODUCT%TYPE,
                       NPOLICY     DIR_DEBIT.NPOLICY%TYPE ,
                       NCERTIF     DIR_DEBIT.NCERTIF%TYPE ,
                       SCLIENT     DIR_DEBIT.SCLIENT%TYPE ,
                       SDIRIND     CERTIFICAT.SDIRIND%TYPE,
                       DEFFECDATE  DIR_DEBIT.DEFFECDATE%TYPE)
                       RETURN      VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REA_SACCOUNT,  WNDS,   WNPS);

FUNCTION REALASTNCOLLECTOR( SCERTYPE    PREMIUM.SCERTYPE%TYPE,
                            NBRANCH     PREMIUM.NBRANCH%TYPE,
                            NPRODUCT    PREMIUM.NPRODUCT%TYPE,
                            NPOLICY     PREMIUM.NPOLICY%TYPE,
                            NCERTIF     PREMIUM.NCERTIF%TYPE,
                            DEFFECDATE  DATE)
                            RETURN    PREMIUM.NCOLLECTOR%TYPE;
PRAGMA RESTRICT_REFERENCES(REALASTNCOLLECTOR,  WNDS,   WNPS);

FUNCTION REANPERCENTCOMM( SCERTYPE    PREMIUM.SCERTYPE%TYPE,
                          NBRANCH     PREMIUM.NBRANCH%TYPE,
                          NPRODUCT    PREMIUM.NPRODUCT%TYPE,
                          NPOLICY     PREMIUM.NPOLICY%TYPE,
                          NCERTIF     PREMIUM.NCERTIF%TYPE,
                          NINTERMED   COMMISS_PR.NINTERMED%TYPE,
                          DEFFECDATE  DATE)
                          RETURN    COMMISS_PR.NPERCENT%TYPE;
PRAGMA RESTRICT_REFERENCES(REANPERCENTCOMM,  WNDS,   WNPS);

/*+RESCATA LA FECHA DEL ULTIMO ESTADO DE UNA CAJA */
FUNCTION REASSTATUSCASH(NCASHNUM  CASH_STAT.NCASHNUM%TYPE)
                        RETURN    TABLE5562.SDESCRIPT%TYPE;


/*+RESCATA EL AREA DE SEGURO SEGUN LA TABLA OPT_SYSTEM */
FUNCTION REAOPT_SYSTEM_INSUR_AREA RETURN  OPT_SYSTEM.NINSUR_AREA%TYPE;

PRAGMA RESTRICT_REFERENCES(REAOPT_SYSTEM_INSUR_AREA, WNDS, WNPS);

/*+RESCATA LA COMPA?IA SEGUN LA TABLA OPT_SYSTEM */
FUNCTION REAOPT_SYSTEM_COMPANY RETURN  OPT_SYSTEM.NCOMPANY%TYPE;

PRAGMA RESTRICT_REFERENCES(REAOPT_SYSTEM_COMPANY, WNDS, WNPS);

/*+RESCATA LA DESCRIPCION DEL CONCEPTO */
FUNCTION REA_NCONCEPT(NCONCEPT CHEQUES.NCONCEPT%TYPE) RETURN  TABLE293.SDESCRIPT%TYPE;

PRAGMA RESTRICT_REFERENCES(REA_NCONCEPT, WNDS, WNPS);

/*+RESCATA LA DESCRIPCION DEL ESTADO */
FUNCTION REA_NSTA_CHEQUE(NSTA_CHEQUE CHEQUES.NSTA_CHEQUE%TYPE)
  RETURN TABLE187.SDESCRIPT%TYPE;

PRAGMA RESTRICT_REFERENCES(REA_NSTA_CHEQUE, WNDS, WNPS);

/*+RESCATA LA DIRECCION */
FUNCTION REA_ADDRESS_STREET ( NSENDADDR     CERTIFICAT.NSENDADDR%TYPE,
                              SKEYADDRESS   ADDRESS.SKEYADDRESS%TYPE,
                              SCLIENT       CLIENT.SCLIENT%TYPE,
                              DEFFECDATE    ADDRESS.DEFFECDATE%TYPE )
                       RETURN ADDRESS.SSTREET%TYPE;

PRAGMA RESTRICT_REFERENCES(REA_ADDRESS_STREET,  WNDS,   WNPS);

/*+RESCATA LA COMUNA */
FUNCTION REA_ADDRESS_SZONE (  NSENDADDR     CERTIFICAT.NSENDADDR%TYPE,
                              SKEYADDRESS   ADDRESS.SKEYADDRESS%TYPE,
                              SCLIENT       CLIENT.SCLIENT%TYPE,
                              DEFFECDATE    ADDRESS.DEFFECDATE%TYPE )
                        RETURN ADDRESS.SZONE%TYPE ;
PRAGMA RESTRICT_REFERENCES(REA_ADDRESS_SZONE,  WNDS,   WNPS);
/*+ RESCATA EL PORCENTAJE DE INPUESTO */
FUNCTION REA_TAX_FIXVAL (NCODE       TAX_FIXVAL.NCODE%TYPE,
                         STYPETAX    TAX_FIXVAL.STYPETAX%TYPE,
                         DEFFECDATE  TAX_FIXVAL.DEFFECDATE%TYPE)
                        RETURN TAX_FIXVAL.NPERCENT%TYPE ;
PRAGMA RESTRICT_REFERENCES(REA_TAX_FIXVAL,  WNDS,   WNPS);


/*+VERIFICA LA EXISTENCIA DE CONCEPTOS OPERACIONALES EN LA TABLA T_CONCEPTS */
FUNCTION EXISTSOPERATIONAL_CONCEPTS (NBORDEREAUX T_CONCEPTS.NBORDEREAUX%TYPE,
                                     SRELORIGI   COLFORMREF.SRELORIGI%TYPE) RETURN INTEGER;
PRAGMA RESTRICT_REFERENCES(EXISTSOPERATIONAL_CONCEPTS, WNDS, WNPS);

FUNCTION REANORIGINREQUEST (SCERTYPE    ROLES.SCERTYPE%TYPE,
                            NBRANCH     ROLES.NBRANCH%TYPE,
                            NPRODUCT    ROLES.NPRODUCT%TYPE,
                            NPOLICY     ROLES.NPOLICY%TYPE,
                            NCERTIF     ROLES.NCERTIF%TYPE,
                            DEFFECDATE  ROLES.DEFFECDATE%TYPE)
                     RETURN REQUEST.NORIGIN%TYPE;
PRAGMA RESTRICT_REFERENCES(REANORIGINREQUEST, WNDS, WNPS);

FUNCTION REABATCH_DESC(NBATCH       BATCH_PROCESS.NBATCH%TYPE,
                       NTYPEDESC    INTEGER)
                RETURN VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REABATCH_DESC, WNDS, WNPS);

FUNCTION REARUTCLIFORMAT(SCLIENT    CLIENT.SCLIENT%TYPE)
                RETURN VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REARUTCLIFORMAT, WNDS, WNPS);

FUNCTION REATAB_BILL_I(NBRANCH      TAB_BILL_I.NBRANCH%TYPE,
                       NPRODUCT     TAB_BILL_I.NPRODUCT%TYPE,
                       NBILL_ITEM   TAB_BILL_I.NBILL_ITEM%TYPE,
                       DEFFECDATE   TAB_BILL_I.DEFFECDATE%TYPE)
                RETURN TAB_BILL_I.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REATAB_BILL_I, WNDS, WNPS);

FUNCTION REASINITIALS(NUSERCODE     USERS.NUSERCODE%TYPE)
               RETURN USERS.SINITIALS%TYPE;
PRAGMA RESTRICT_REFERENCES(REASINITIALS, WNDS, WNPS);

/*+RESCATA NOMBRE DEL ESTADOS DE UNA COTIZACIoN/PROPUESTA*/
FUNCTION REANSTATQUOTA(NSTATQUOTA      TABLE5526.NSTATQUOTA%TYPE)
                       RETURN          TABLE5526.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REANSTATQUOTA,  WNDS,   WNPS);

/*+RESCATA EL MONTO COBRADO EN UNA RELACION */
FUNCTION REAPAY_RELATION(NBORDEREAUX    COLFORMREF.NBORDEREAUX%TYPE)
                       RETURN          COLFORMREF.NREL_AMOUN%TYPE;
PRAGMA RESTRICT_REFERENCES(REAPAY_RELATION,  WNDS,   WNPS);

/*+RESCATA LA FECHA DE LA ULTIMA VEZ QUE SE REALIZO UN MOVIMIENTO EN POLICY_HIS*/
FUNCTION REAPOLICY_HISDATE(SCERTYPE   POLICY_HIS.SCERTYPE%TYPE,
                           NBRANCH    POLICY_HIS.NBRANCH%TYPE,
                           NPRODUCT   POLICY_HIS.NPRODUCT%TYPE,
                           NPOLICY    POLICY_HIS.NPOLICY%TYPE,
                           NCERTIF    POLICY_HIS.NCERTIF%TYPE,
                           NTYPE_HIST POLICY_HIS.NTYPE_HIST%TYPE)
                           RETURN     POLICY_HIS.DEFFECDATE%TYPE;
PRAGMA RESTRICT_REFERENCES(REANSTATQUOTA,  WNDS,   WNPS);

/*+DADAS DOS MONEDAS RETORNA EL FACTOR DE CAMBIO PARA CONVERTIR LA 1RA EN LA 2DA */
FUNCTION GETEXCHANGE(NCURORI        EXCHANGE.NCURRENCY%TYPE,
                     NCURDES        EXCHANGE.NCURRENCY%TYPE,
                     DEFFECDATE     EXCHANGE.DEFFECDATE%TYPE)
                     RETURN         EXCHANGE.NEXCHANGE%TYPE;
PRAGMA RESTRICT_REFERENCES(GETEXCHANGE,  WNDS,   WNPS);

/* RESCATA EL NOMBRE DEL CLIENTE ASOCIADO AL CASO */

FUNCTION REACLAIMCLIENT(NCLAIM      CLAIM.NCLAIM%TYPE,
       NCASE_NUM   CLAIMBENEF.NCASE_NUM%TYPE)
               RETURN VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REACLAIMCLIENT, WNDS, WNPS);

/*+CALCULA EDAD REAL DEL ASEGURADO*/
FUNCTION GET_AGE_REAL(DEFFECDATE   CLIENT.DBIRTHDAT%TYPE,
                      DBIRTHDAT    CLIENT.DBIRTHDAT%TYPE,
                      NOPTION      INTEGER DEFAULT 0)
                      RETURN       NUMBER;
PRAGMA RESTRICT_REFERENCES(REASECTION_PO,  WNDS,   WNPS);

/*+CALCULA EDAD REAL DEL ASEGURADO CON DECIMALES*/
FUNCTION GET_AGE_REAL2(DEFFECDATE   CLIENT.DBIRTHDAT%TYPE,
                       DBIRTHDAT    CLIENT.DBIRTHDAT%TYPE)
                       RETURN       NUMBER;
PRAGMA RESTRICT_REFERENCES(REASECTION_PO,  WNDS,   WNPS);


/*+ RESCATA LOS COSTOS COBERTURA */
FUNCTION REACOST_COVER (SCERTYPE   ROLES.SCERTYPE%TYPE,
                        NBRANCH    ROLES.NBRANCH%TYPE,
                        NPRODUCT   ROLES.NPRODUCT%TYPE,
                        NPOLICY    ROLES.NPOLICY%TYPE,
                        NCERTIF    ROLES.NCERTIF%TYPE,
                        SCLIENT    ROLES.SCLIENT%TYPE,
                        NROLE      ROLES.NROLE%TYPE,
                        NMODULEC   TAR_TRALIFE.NMODULEC%TYPE,
                        NGROUP     COVER.NGROUP_INSU%TYPE,
                        NCOVER     TAR_TRALIFE.NCOVER%TYPE,
                        DEFFECDATE TAR_TRALIFE.DEFFECDATE%TYPE,
                        NDURPAY    COVER.NDURPAY%TYPE DEFAULT NULL,
                        NDURINSUR  COVER.NDURINSUR%TYPE DEFAULT NULL)
                        RETURN      NUMBER;
PRAGMA RESTRICT_REFERENCES(REACOST_COVER,  WNDS,   WNPS);

/*+ RETORNA EL OWNER    */
FUNCTION GET_SOWNER_BASE RETURN TABLE5638.SOWNER_BASE%TYPE;
PRAGMA RESTRICT_REFERENCES(GET_SOWNER_BASE,  WNDS,   WNPS);

/*+BUSCA LA TABLA DE UNA FK ASOCIADA A UNA COLUMNA DE OTRA TABLA*/
FUNCTION GET_TABLE_FK(STABLE       TARIF_COLUMN.STABLE%TYPE,
                      SCOLUMN      TARIF_COLUMN.SCOLUMN%TYPE)
                      RETURN       VARCHAR2;
PRAGMA RESTRICT_REFERENCES(GET_TABLE_FK,  WNDS,   WNPS);

/*+SE BUSCA LA CUENTA BASICA*/
FUNCTION REAORIGIN_PRIMARY(NBRANCH     PRODUCT_LI.NBRANCH%TYPE,
                           NPRODUCT    PRODUCT_LI.NPRODUCT%TYPE)
                           RETURN      TAB_ORD_ORIGIN.NORIGIN%TYPE;
PRAGMA RESTRICT_REFERENCES(REAORIGIN_PRIMARY,  WNDS,   WNPS);

/*+SE CALCULA LA EDAD ACTUARIAL DEL CLIENTE. */
FUNCTION INSCALINSUAGE_ASEG(NBRANCH         PRODUCT_LI.NBRANCH%TYPE,
                            NPRODUCT        PRODUCT_LI.NPRODUCT%TYPE,
                            DEFFECDATE      PRODUCT_LI.DEFFECDATE%TYPE,
                            DBIRTHDATE      ROLES.DBIRTHDATE%TYPE,
                            SSEXCLIEN       ROLES.SSEXCLIEN%TYPE,
                            SSMOKING        ROLES.SSMOKING%TYPE,
                            NROLE           ROLES.NROLE%TYPE DEFAULT NULL,
                            SOPTION         CHAR DEFAULT '1',
                            BACTUARIAL_PROD  BOOLEAN  DEFAULT TRUE)
                            RETURN          NUMBER;
PRAGMA RESTRICT_REFERENCES(INSCALINSUAGE_ASEG,  WNDS,   WNPS);

/*+ OBTIENE LA PRIMERA RELACIÓN DEL CLIENTE CON OTRO CLIENTE.*/
FUNCTION GETRELATIONS_CLI(SCLIENT         RELATIONS.SCLIENT%TYPE,
                          SCLIENTR        RELATIONS.SCLIENTR%TYPE) RETURN TABLE15.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(GETRELATIONS_CLI,  WNDS,   WNPS);

/*+ OBTIENE EL PRIMER DEPORTE REGISTRADO DEL CLIENTE.*/
FUNCTION GETSPORT_CLI(SCLIENT         SPORT.SCLIENT%TYPE) RETURN TABLE512.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(GETSPORT_CLI,  WNDS,   WNPS);

/*+ OBTIENE EL PRIMER HOBBY REGISTRADO DEL CLIENTE.*/
FUNCTION GETHOBBY_CLI(SCLIENT         HOBBY.SCLIENT%TYPE) RETURN TABLE5506.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(GETHOBBY_CLI,  WNDS,   WNPS);


/*+ OBTIENE LA DESCRIPCION DEL CARGO O ABONO  */
FUNCTION REALIFE_LOAD    (NBRANCH     LIFE_LOAD.NBRANCH%TYPE,
                          NPRODUCT    LIFE_LOAD.NPRODUCT%TYPE,
                          NLOAD_COD   LIFE_LOAD.NLOAD_COD%TYPE,
                          DEFFECDATE  LIFE_LOAD.DEFFECDATE%TYPE)
                          RETURN      LIFE_LOAD.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REALIFE_LOAD,  WNDS,   WNPS);

/*+ RESCATA LA DURACION DE LA COBERTURA */
FUNCTION READUR_COVER (SCERTYPE   ROLES.SCERTYPE%TYPE,
                       NBRANCH    ROLES.NBRANCH%TYPE,
                       NPRODUCT   ROLES.NPRODUCT%TYPE,
                       NPOLICY    ROLES.NPOLICY%TYPE,
                       NCERTIF    ROLES.NCERTIF%TYPE,
                       SCLIENT    ROLES.SCLIENT%TYPE,
                       NROLE      ROLES.NROLE%TYPE,
                       NMODULEC   TAR_TRALIFE.NMODULEC%TYPE,
                       NCOVER     TAR_TRALIFE.NCOVER%TYPE,
                       DEFFECDATE TAR_TRALIFE.DEFFECDATE%TYPE)
                    RETURN      DATE;
PRAGMA RESTRICT_REFERENCES(READUR_COVER,  WNDS,   WNPS);

/*+ RESCATA EDAD DE UN ASEGURADO DE LA POLIZA */
FUNCTION INSCALINSUAGE_ASEG_POL (SCERTYPE   ROLES.SCERTYPE%TYPE,
                                 NBRANCH    ROLES.NBRANCH%TYPE,
                                 NPRODUCT   ROLES.NPRODUCT%TYPE,
                                 NPOLICY    ROLES.NPOLICY%TYPE,
                                 NCERTIF    ROLES.NCERTIF%TYPE,
                                 NROLE      ROLES.NROLE%TYPE DEFAULT NULL,
                                 SCLIENT    ROLES.SCLIENT%TYPE DEFAULT NULL,
                                 DEFFECDATE TAR_TRALIFE.DEFFECDATE%TYPE DEFAULT NULL,
                                 SOPTION         CHAR DEFAULT '1')
                    RETURN      NUMBER;
PRAGMA RESTRICT_REFERENCES(READUR_COVER,  WNDS,   WNPS);


FUNCTION REABATCHSHEET_DESC (NBATCH       BATCH_PROCESS.NBATCH%TYPE,
                             NSHEET       BATCH_PROCESS.NBATCH%TYPE,
                             NTYPEDESC    INTEGER)
                             RETURN VARCHAR2 ;
PRAGMA RESTRICT_REFERENCES(REABATCHSHEET_DESC,  WNDS,   WNPS);

/*+ OBTIENE LA DESCRIPCION DEL CARGO (LIFE_LOAD)*/
FUNCTION REASDESCLOAD(NBRANCH   LIFE_LOAD.NBRANCH%TYPE,
                      NPRODUCT  LIFE_LOAD.NPRODUCT%TYPE,
                      NLOAD_COD LIFE_LOAD.NLOAD_COD%TYPE)
              RETURN  VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REASECTION_PO,  WNDS,   WNPS);

/*+RESCATA UNA GLOSA QUE CONTIENE TODOS LOS DOCUMENTOS PENDIENTES DE UNA POLIZA/CERTIFICADO*/
FUNCTION REALIFE_DOCUDESCRIPT(SCERTYPE   LIFE_DOCU.SCERTYPE%TYPE,
                              NBRANCH    LIFE_DOCU.NBRANCH%TYPE,
                              NPRODUCT   LIFE_DOCU.NPRODUCT%TYPE,
                              NPOLICY    LIFE_DOCU.NPOLICY%TYPE,
                              NCERTIF    LIFE_DOCU.NCERTIF%TYPE,
                              DEFFECDATE LIFE_DOCU.DEFFECDATE%TYPE)
                              RETURN     VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REALIFE_DOCUDESCRIPT,  WNDS,   WNPS);



FUNCTION INSCOLLECT_POL (SCERTYPE   ROLES.SCERTYPE%TYPE,
                         NBRANCH    ROLES.NBRANCH%TYPE,
                         NPRODUCT   ROLES.NPRODUCT%TYPE,
                         NPOLICY    ROLES.NPOLICY%TYPE,
                         NCERTIF    ROLES.NCERTIF%TYPE,
                         DEFFECDATE COVER.DEFFECDATE%TYPE)  
                         RETURN NUMBER;
PRAGMA RESTRICT_REFERENCES(INSCOLLECT_POL,  WNDS,   WNPS);


FUNCTION INSVP_POL (SCERTYPE   ROLES.SCERTYPE%TYPE,
                    NBRANCH    ROLES.NBRANCH%TYPE,
                    NPRODUCT   ROLES.NPRODUCT%TYPE,
                    NPOLICY    ROLES.NPOLICY%TYPE,
                    NCERTIF    ROLES.NCERTIF%TYPE,
                    DEFFECDATE COVER.DEFFECDATE%TYPE,
                    NORIGIN    CERTIFICAT.NORIGIN%TYPE DEFAULT 0)
                    RETURN NUMBER;
PRAGMA RESTRICT_REFERENCES(INSVP_POL,  WNDS,   WNPS); 

/*+RESCATA UNA GLOSA QUE CONTIENE TODOS LOS DOCUMENTOS PENDIENTES DE UNA POLIZA/CERTIFICADO*/
FUNCTION REALIFE_DOCU_NOTES(SCERTYPE   LIFE_DOCU.SCERTYPE%TYPE,
                            NBRANCH    LIFE_DOCU.NBRANCH%TYPE,
                            NPRODUCT   LIFE_DOCU.NPRODUCT%TYPE,
                            NPOLICY    LIFE_DOCU.NPOLICY%TYPE,
                            NCERTIF    LIFE_DOCU.NCERTIF%TYPE,
                            DEFFECDATE LIFE_DOCU.DEFFECDATE%TYPE,
                            NCRTHECNI  LIFE_DOCU.NCRTHECNI%TYPE DEFAULT NULL)
                            RETURN     VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REALIFE_DOCU_NOTES,  WNDS,   WNPS);
/*+RESCATA LA RENTABILIDAD EN UF DIARIA*/
FUNCTION REARENT_DAY_UF(NFUNDS               FUND_VALUE.NFUNDS%TYPE,
                                            DEFFECDATE        FUND_VALUE.DEFFECDATE%TYPE)
                                            RETURN               FUND_VALUE.NAMOUNT%TYPE;
PRAGMA RESTRICT_REFERENCES(REARENT_DAY_UF,  WNDS,   WNPS);

/*+RESCATA LA TASA DE RENTABILIDAD DIARIA*/
FUNCTION REARENT_DAY_PERCENT(NFUNDS               FUND_VALUE.NFUNDS%TYPE,
                                                     DEFFECDATE        FUND_VALUE.DEFFECDATE%TYPE)
                                                     RETURN               FUND_VALUE.NAMOUNT%TYPE;
PRAGMA RESTRICT_REFERENCES(REARENT_DAY_PERCENT,  WNDS,   WNPS);


/*+OBTIENE EL BALANCE SEGUN CUENTA ORIGEN Y REGIMEN TRIBUTARIO*/
FUNCTION REAUL_DAILY_BALANCES(NBRANCH                  UL_DAILY_BALANCES.NBRANCH%TYPE,
                                                     NPRODUCT                UL_DAILY_BALANCES.NPRODUCT%TYPE,
                                                     NPOLICY                    UL_DAILY_BALANCES.NPOLICY%TYPE,
                                                     NCERTIF                    UL_DAILY_BALANCES.NCERTIF%TYPE,
                                                     NFUNDS                     UL_DAILY_BALANCES.NFUNDS%TYPE,
                                                     NORIGIN                     UL_DAILY_BALANCES.NORIGIN%TYPE,
                                                     NTYP_PROFITWORKER UL_DAILY_BALANCES.NTYP_PROFITWORKER%TYPE,
                                                     DEFFECDATE               UL_DAILY_BALANCES.DBAL_DATE%TYPE)
                                                     RETURN  UL_DAILY_BALANCES.NBALANCE%TYPE;
PRAGMA RESTRICT_REFERENCES(REAUL_DAILY_BALANCES,  WNDS,   WNPS);

/*+ RETORNA LA COBERTURA PRINCIPAL DE LA POLIZA  */
FUNCTION REACOVER_PPAL(SCERTYPE    COVER.SCERTYPE%TYPE,
                       NBRANCH     COVER.NBRANCH%TYPE,
                       NPRODUCT    COVER.NPRODUCT%TYPE,
                       NPOLICY     COVER.NPOLICY%TYPE,
                       DEFFECDATE  COVER.DEFFECDATE%TYPE,
                       STYP_MODULE POLICY.STYP_MODULE%TYPE)
                       RETURN      COVER.NCOVER%TYPE;

PRAGMA RESTRICT_REFERENCES(REACOVER_PPAL,  WNDS,   WNPS);

/*+RESCATE EL CLIENTE DE UN CONVENIO*/
FUNCTION REASCLIENT_AGREEMENT(NCOD_AGREE          AGREEMENT.NCOD_AGREE%TYPE)
                             RETURN               AGREEMENT.SCLIENT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASCLIENT_AGREEMENT,  WNDS,   WNPS);

/*+RESCATA NOMBRE DEL CLIENTE PARA UN USUARIO */
FUNCTION REANAMECLI_USERCODE(NUSERCODE      USERS.NUSERCODE%TYPE)
                            RETURN          VARCHAR2;

PRAGMA RESTRICT_REFERENCES(REANAMECLI_USERCODE,  WNDS,   WNPS);  

/*+RESCATA NOMBRE DEL CLIENTE EN EL FORMATO PARA LOS CONDICIONADOS +*/
FUNCTION REANAMECLI_FORMAT(SCLIENT      CLIENT.SCLIENT%TYPE)
                            RETURN      VARCHAR2;

PRAGMA RESTRICT_REFERENCES(REANAMECLI_FORMAT,  WNDS,   WNPS);

/*+RESCATA LA DIRECCION DEL CLIENTE EN EL FORMATO PARA LOS CONDICIONADOS +*/
FUNCTION REAADDRESSCLI_FORMAT(SCLIENT     CLIENT.SCLIENT%TYPE,
                              STYPE       ADDRESS.SRECTYPE%TYPE)
                              RETURN      VARCHAR2;

PRAGMA RESTRICT_REFERENCES(REAADDRESSCLI_FORMAT,  WNDS,   WNPS);
/*+ INDICA EL ESTADO DE UNA PÓLIZA PARA UNA FECHA ESPECIFICA*/
FUNCTION GETSTATUSINDATE(SCERTYPE    ROLES.SCERTYPE%TYPE,
                        NBRANCH     ROLES.NBRANCH%TYPE,
                        NPRODUCT    ROLES.NPRODUCT%TYPE,
                        NPOLICY     ROLES.NPOLICY%TYPE,
                        NCERTIF     ROLES.NCERTIF%TYPE,
                        DEFFECDATE  ROLES.DEFFECDATE%TYPE)
                        RETURN   TABLE181.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REACLIENTROLE,     WNDS,   WNPS);
/*+RESCATA NOMBRE DEL CLIENTE CON FORMATO "CODIGO - DIGITO */
FUNCTION REACLI_RUT(SCLIENT         CLIENT.SCLIENT%TYPE)
                        RETURN          VARCHAR2;
PRAGMA RESTRICT_REFERENCES(REACLI_RUT,  WNDS,   WNPS);

FUNCTION RESOLVE_CLIENT_PERSON_TYP(SRUT CLIENT.SCLIENT%TYPE) RETURN CLIENT.NPERSON_TYP%TYPE;

FUNCTION GETKEYADDRESS(NRECOWNER  ADDRESS.NRECOWNER%TYPE,
                       SRECTYPE   ADDRESS.SRECTYPE%TYPE,
                       SCERTYPE   POLICY.SCERTYPE%TYPE DEFAULT '',
                       NBRANCH    POLICY.NBRANCH%TYPE DEFAULT 0,
                       NPRODUCT   POLICY.NPRODUCT%TYPE DEFAULT 0,
                       NPOLICY    POLICY.NPOLICY%TYPE DEFAULT 0,
                       NCERTIF    CERTIFICAT.NCERTIF%TYPE DEFAULT 0,
                       NCLAIM     CLAIM.NCLAIM%TYPE DEFAULT 0,
                       SCLIENT    CLIENT.SCLIENT%TYPE DEFAULT '',
                       NBANK      TABLE7.NBANK_CODE%TYPE DEFAULT 0,
                       NAGENCY    POLICY.NAGENCY%TYPE DEFAULT 0,
                       NOFFICE    POLICY.NOFFICE%TYPE DEFAULT 0,
                       NCONTRAT   ADDRESS.NPOLICY%TYPE DEFAULT 0,
                       NCOD_AGREE ADDRESS.NCOD_AGREE %TYPE  DEFAULT 0) RETURN ADDRESS.SKEYADDRESS%TYPE;

/*+OBTENER INFORMACIÓN DE UNA COTIZACION, PROPUESTA O PÓLIZA +*/
FUNCTION GETDATAQUOTATIONPROPOSALPOLICY(SCERTYPEORIGINAL  CERTIFICAT.SCERTYPE%TYPE,
                                       NBRANCH              CERTIFICAT.NBRANCH%TYPE,
                                       NPRODUCT              CERTIFICAT.NPRODUCT%TYPE,
                                       NPOLICY              CERTIFICAT.NPOLICY%TYPE,
                                       NCERTIF              CERTIFICAT.NCERTIF%TYPE,
                                       SCERTYPESEARCHED   CERTIFICAT.SCERTYPE%TYPE,
                                       NTYPE              NUMBER)
                                       RETURN    VARCHAR2;
PRAGMA RESTRICT_REFERENCES(GETDATAQUOTATIONPROPOSALPOLICY, WNDS, WNPS);     

/*+VERIFICAR SI UNA COTIZACIÓN/PROPUESTA TIENE ESTADO VIGENTE O VENCIDO +*/
FUNCTION GETSTATUSRECORD(SCERTYPE    CERTIFICAT.SCERTYPE%TYPE,
                         NBRANCH     CERTIFICAT.NBRANCH%TYPE,
                         NPRODUCT    CERTIFICAT.NPRODUCT%TYPE,
                         NPOLICY     CERTIFICAT.NPOLICY%TYPE,
                         NCERTIF     CERTIFICAT.NCERTIF%TYPE,
                         DDATE_ORIGI CERTIFICAT.DDATE_ORIGI%TYPE)
                         RETURN      NUMBER;
PRAGMA RESTRICT_REFERENCES(GETSTATUSRECORD,     WNDS,   WNPS);

/*+OBTENER SALDO CAPITAL DE UNA PÓLIZA +*/
FUNCTION GETCAPITALBALANCE(SCERTYPE    CERTIFICAT.SCERTYPE%TYPE,
                           NBRANCH     CERTIFICAT.NBRANCH%TYPE,
                           NPRODUCT    CERTIFICAT.NPRODUCT%TYPE,
                           NPOLICY     CERTIFICAT.NPOLICY%TYPE,
                           NCERTIF     CERTIFICAT.NCERTIF%TYPE,
                           SCLIENT     CLIENT.SCLIENT%TYPE,
                           NCURRENCY   COVER.NCURRENCY%TYPE,
                           DEFFECDATE  CERTIFICAT.DDATE_ORIGI%TYPE)
                           RETURN      CERTIFICAT.NCAPITAL%TYPE;
PRAGMA RESTRICT_REFERENCES(GETCAPITALBALANCE,     WNDS,   WNPS);

/*+VERIFICAR SI UN ASEGURADO SE ENCUENTRA EXCLUIDO +*/
FUNCTION GETSTATUSINSURED(SCERTYPE    CERTIFICAT.SCERTYPE%TYPE,
                          NBRANCH     CERTIFICAT.NBRANCH%TYPE,
                          NPRODUCT    CERTIFICAT.NPRODUCT%TYPE,
                          NPOLICY     CERTIFICAT.NPOLICY%TYPE,
                          NCERTIF     CERTIFICAT.NCERTIF%TYPE,
                          NROLE       ROLES.NROLE%TYPE,
                          SCLIENT     CLIENT.SCLIENT%TYPE,
                          DEFFECDATE  CERTIFICAT.DDATE_ORIGI%TYPE,
                          NOUTPUT     NUMBER)
                          RETURN      VARCHAR2;
PRAGMA RESTRICT_REFERENCES(GETSTATUSINSURED,     WNDS,   WNPS);

FUNCTION CALC_ACCOUNT (SCERTYPE    POLICY_HIS.SCERTYPE%TYPE,
                       NBRANCH     POLICY_HIS.NBRANCH%TYPE, 
                       NPRODUCT    POLICY_HIS.NPRODUCT%TYPE,
                       NPOLICY     POLICY_HIS.NPOLICY%TYPE,
                       NCERTIF     POLICY_HIS.NCERTIF%TYPE, 
                       DOCURRDATE  PRECLAIM.DOCCURDATE%TYPE,
                       SCLIENT     INSURED_EXPDIS.SCLIENT%TYPE)
                       RETURN      VARCHAR2;
PRAGMA RESTRICT_REFERENCES(CALC_ACCOUNT,     WNDS,   WNPS);

FUNCTION CALC_EXTEMPORANEA (NBRANCH     PRODUCT.NBRANCH%TYPE,
                            NPRODUCT    PRODUCT.NPRODUCT%TYPE,      
                            DREPDATE    PRECLAIM.DREPDATE%TYPE,
                            DOCCURDATE  PRECLAIM.DOCCURDATE%TYPE)
                            RETURN      VARCHAR2;
PRAGMA RESTRICT_REFERENCES(CALC_EXTEMPORANEA,     WNDS,   WNPS);

FUNCTION CALC_PENALTY (SCERTYPE    POLICY_HIS.SCERTYPE%TYPE,
                       NBRANCH     POLICY_HIS.NBRANCH%TYPE, 
                       NPRODUCT    POLICY_HIS.NPRODUCT%TYPE,
                       NPOLICY     POLICY_HIS.NPOLICY%TYPE,
                       NCERTIF     POLICY_HIS.NCERTIF%TYPE, 
                       DOCURRDATE  PRECLAIM.DOCCURDATE%TYPE)
                       RETURN      VARCHAR2;
PRAGMA RESTRICT_REFERENCES(CALC_PENALTY,     WNDS,   WNPS);
FUNCTION REANAME_USERS
/*----------------------------------------------------------------------------*/
/* NOMBRE    : REANAMECLI_USERS                                               */
/* OBJETIVO  : FUNCION QUE DEVUELVE: CODIGO | DIGITO | NOMBRE DE UN CLIENTE   */
/* PARAMETROS: 1 - SCLIENT  : CODIGO DEL CLIENTE                              */
/*                                                                            */
/*----------------------------------------------------------------------------*/
    (NUSERCODE    USERS.NUSERCODE%TYPE)
     RETURN     VARCHAR2;

/*+RETORNA DESCRIPCION DEL AMBITO GEOGRAFICO*/
FUNCTION REASGEOGRAPHAREA(NBRANCH    TAB_MODUL.NBRANCH%TYPE,
                          NPRODUCT   TAB_MODUL.NPRODUCT%TYPE,
                          NMODULEC   TAB_MODUL.NMODULEC%TYPE,
                          DEFFECDATE TAB_MODUL.DEFFECDATE%TYPE)
                          RETURN     TABLE9214.SDESCRIPT%TYPE;
PRAGMA RESTRICT_REFERENCES(REASGEOGRAPHAREA,     WNDS,   WNPS);

/*+OBTENER CAPITAL ORIGINAL DE LA COBERTURA BÁSICA+*/
FUNCTION GETCAPITALCOVER(SCERTYPE    CERTIFICAT.SCERTYPE%TYPE,
                         NBRANCH     CERTIFICAT.NBRANCH%TYPE,
                         NPRODUCT    CERTIFICAT.NPRODUCT%TYPE,
                         NPOLICY     CERTIFICAT.NPOLICY%TYPE,
                         NCERTIF     CERTIFICAT.NCERTIF%TYPE,
                         SCLIENT     CLIENT.SCLIENT%TYPE,
                         DEFFECDATE  CERTIFICAT.DDATE_ORIGI%TYPE)
                         RETURN      CERTIFICAT.NCAPITAL%TYPE;
PRAGMA RESTRICT_REFERENCES(GETCAPITALCOVER,     WNDS,   WNPS);

/*+RETORNA SISTEMA DE ATENCIÓN DE SALUD DE LA PÓLIZA+*/
FUNCTION GETATTENTIONSYSTEM(SCERTYPE   CERTIFICAT.SCERTYPE%TYPE,
                            NBRANCH    CERTIFICAT.NBRANCH%TYPE, 
                            NPRODUCT   CERTIFICAT.NPRODUCT%TYPE,
                            NPOLICY    CERTIFICAT.NPOLICY%TYPE,
                            NCERTIF    CERTIFICAT.NCERTIF%TYPE,
                            SCLIENT    CLAIM.SCLIENT2%TYPE,
                            NCURRENCY  CURREN_POL.NCURRENCY%TYPE,
                            DEFFECDATE CLAIM.DOCCURDAT%TYPE)
                            RETURN     MODULES.NATTENSYSTEM%TYPE;
PRAGMA RESTRICT_REFERENCES(GETATTENTIONSYSTEM,     WNDS,   WNPS);

/*+OBTENER SALDO CAPITAL DE LA COBERTURA DE MATERNIDAD+*/
FUNCTION GETBALANCEMATERNITY(SCERTYPE   CERTIFICAT.SCERTYPE%TYPE,
                             NBRANCH    CERTIFICAT.NBRANCH%TYPE,
                             NPRODUCT   CERTIFICAT.NPRODUCT%TYPE,
                             NPOLICY    CERTIFICAT.NPOLICY%TYPE,
                             NCERTIF    CERTIFICAT.NCERTIF%TYPE,
                             SCLIENT    CLIENT.SCLIENT%TYPE,
                             NCURRENCY  COVER.NCURRENCY%TYPE,
                             DEFFECDATE CERTIFICAT.DDATE_ORIGI%TYPE)
                             RETURN     CERTIFICAT.NCAPITAL%TYPE;
PRAGMA RESTRICT_REFERENCES(GETBALANCEMATERNITY,     WNDS,   WNPS);

/*+OBTENER LAS REDES MÉDICAS DE UNA PÓLIZA+*/
FUNCTION GETMEDICALNETWORK(SCERTYPE   CERTIFICAT.SCERTYPE%TYPE,
                           NBRANCH    CERTIFICAT.NBRANCH%TYPE,
                           NPRODUCT   CERTIFICAT.NPRODUCT%TYPE,
                           NPOLICY    CERTIFICAT.NPOLICY%TYPE,
                           NCERTIF    CERTIFICAT.NCERTIF%TYPE,
                           DEFFECDATE CERTIFICAT.DDATE_ORIGI%TYPE)
                           RETURN     VARCHAR2;
PRAGMA RESTRICT_REFERENCES(GETMEDICALNETWORK,     WNDS,   WNPS);

END REAGENERALPKG;