CREATE OR REPLACE PROCEDURE INSUDB.NS_INSREDESMEDICAS515
/*-------------------------------------------------------------------------------*/
/* NOMBRE    : NS_INSREDESMEDICAS515                                                      */
/* OBJETIVO  : OBTENER LISTADO DE REDES MEDICAS CONFIGURADAS EN EL SISTEMA                           */
/* PARAMETROS: 1 -                                                                      */
/*             2 -                                                                      */
/*             3 -                                                                      */
/*             4 -                                                                      */
/*             5 -                                                                      */
/*             6 -                                                                      */
/* SOURCESAFE INFORMATION                                                                                       */
/*     $Author: NSB- GEORGE NOTO $                                                                              */
/*     $Date: 31/03/26  $                                                                                       */
/*     $Revision:  $                                                                                            */

/*-------------------------------------------------------------------------------*/
   (SKEY                	            T_INTERFACE.SKEY%TYPE,
	NSHEET              	            MASTERSHEET.NSHEET%TYPE,
	NUSERCODE           	            MASTERSHEET.NUSERCODE%TYPE,
    NCOD_REGIONAL            			TABLE9.NOFFICE%TYPE,
	NERROR                              OUT T_ERR_INTERFACE.NERROR%TYPE,
    SERRORDESC                          OUT VARCHAR2 
	) AUTHID CURRENT_USER AS

BEGIN

   -- Borrar solo la ejecuci�n sobre la misma llave; si no existe, limpiar tabla de reporte
   DELETE FROM TIMETMP.TMP_INT515 WHERE SKEY = NS_INSREDESMEDICAS515.SKEY;
   IF SQL%ROWCOUNT = 0 THEN
      DELETE FROM TIMETMP.TMP_INT515;
   END IF;
   --DELETE TRACE WHERE NUSERCODE = 15;
   COMMIT;


INSERT INTO TIMETMP.TMP_INT515 (
  SKEY,
  SCOD_TIPO_PROVEEDOR,
  STIPO_PROVEEDOR,
  NCOD_PROVEEDOR,
  SNOMBRE_PROVEEDOR,
  SESPECIALIDAD_CATEGORIA,
  SCLIENT,
  SNIT,
  SREGIONAL,
  SCIUDAD,
  SESTADO,
  SGRUPO,
  NTARIFA,
  NFACTOR_DESCUENTO,
  NFACTOR_INCREMENTO,
  NVALOR_UMA_LO,
  NPLAN_HABILITADO,
  SSUSCRIPTOR,
  SMODALIDAD_PAGO,
  SEXCEPCIONES
)
WITH TBLDOCUMENTO AS (
    SELECT  CDOC.SCLIENT AS SCLIENT,
        T6023.sdescript AS TIPO_DOCUMENTO,
        FVAL.sdescript AS SUBTIPO_DOCUMENTO,
        CDOC.SCLINUMDOCU AS NRO_DOCUMENTO,
        ROW_NUMBER() OVER(PARTITION BY CDOC.SCLIENT ORDER BY CDOC.DCOMPDATE DESC)  as rn   
    FROM CLIDOCUMENTS CDOC 
    INNER JOIN TABLE6023 T6023 ON CDOC.NCLASSTYPDOC = T6023.NCLASSTYPDOC
    INNER JOIN FORMATVALUES FVAL ON CDOC.NTYPCLIENTDOC = FVAL.NTYPCLIENTDOC 
    WHERE CDOC.NCLASSTYPDOC IN (2) AND CDOC.NTYPCLIENTDOC IN (3) 
),
TBLPRESTACIONES AS (
    SELECT TMED.NPROVIDER,
         LISTAGG(DISTINCT  TRIM(GAMV.STYPEBENEFIT) || ' ' || TRIM(GAMV.SDESCRIPT), ', ') 
            WITHIN GROUP (ORDER BY GAMV.STYPEBENEFIT ) 
            AS GRUPOS_ASIGNADOS
    FROM MEDICALFEES MF
    INNER JOIN MEDICALBENEFITS MB ON MF.SBENEFITCODE = MB.SBENEFIT
    INNER JOIN TAB_MEDICALFEES TMED ON MF.NIDMEDICALFEE = TMED.NIDMEDICALFEE 
    INNER JOIN TABLE8600 GAMV ON MB.STYPEBENEFIT = GAMV.STYPEBENEFIT 
    --WHERE TMED.SDESCRIPT LIKE '%AMV%'  
    GROUP BY TMED.NPROVIDER
),
TBLDOCUMENTO AS (
    SELECT  CDOC.SCLIENT AS SCLIENT,
        T6023.sdescript AS TIPO_DOCUMENTO,
        FVAL.sdescript AS SUBTIPO_DOCUMENTO,
        CDOC.SCLINUMDOCU AS NRO_DOCUMENTO,
        ROW_NUMBER() OVER(PARTITION BY CDOC.SCLIENT ORDER BY CDOC.DCOMPDATE DESC)  as rn   
    FROM CLIDOCUMENTS CDOC 
    INNER JOIN TABLE6023 T6023 ON CDOC.NCLASSTYPDOC = T6023.NCLASSTYPDOC
    INNER JOIN FORMATVALUES FVAL ON CDOC.NTYPCLIENTDOC = FVAL.NTYPCLIENTDOC 
    WHERE CDOC.NCLASSTYPDOC IN (2) AND CDOC.NTYPCLIENTDOC IN (3) 
),
TBLPRESTACIONES AS (
    SELECT TMED.NPROVIDER,
         LISTAGG(DISTINCT  TRIM(GAMV.STYPEBENEFIT) || ' ' || TRIM(GAMV.SDESCRIPT), ', ') 
            WITHIN GROUP (ORDER BY GAMV.STYPEBENEFIT ) 
            AS GRUPOS_ASIGNADOS
    FROM MEDICALFEES MF
    INNER JOIN MEDICALBENEFITS MB ON MF.SBENEFITCODE = MB.SBENEFIT
    INNER JOIN TAB_MEDICALFEES TMED ON MF.NIDMEDICALFEE = TMED.NIDMEDICALFEE 
    INNER JOIN TABLE8600 GAMV ON MB.STYPEBENEFIT = GAMV.STYPEBENEFIT 
    --WHERE TMED.SDESCRIPT LIKE '%AMV%'  
    GROUP BY TMED.NPROVIDER
),
TBLPLANES AS (
  SELECT TP1.NPROVIDER, LISTAGG( DISTINCT TRIM(T_T642.SDESCRIPT), ', ' ) WITHIN GROUP(ORDER BY T_T642.NPROV_GROUP) AS PLANES
  FROM TAB_PROVIDER TP1
  INNER JOIN TAB_PROV_GROUP TPG1 ON TP1.NPROVIDER= TPG1.NPROVIDER
  INNER JOIN TABLE642 T_T642 ON TPG1.NPROV_GROUP=  T_T642.NPROV_GROUP
  GROUP BY TP1.NPROVIDER
)
SELECT
  NS_INSREDESMEDICAS515.SKEY AS SKEY,
  TP.NTYPEPROV AS SCOR_TIPO_PROVEEDOR,
  TRIM(T7027.SDESCRIPT) AS STIPO_PROVEEDOR,
  TP.NPROVIDER,
  TRIM(C.SCLIENAME) AS SNOMBRE_PROVEEDOR ,
  CASE TP.NTYPEPROV
          WHEN 1 THEN TRIM(TPS.SDESCRIPT)
          ELSE TRIM(T8603.SDESCRIPT)     
  END AS SESPECIALIDAD_CATEGORIA,  
  TP.SCLIENT AS SCLIENT,                                              
  TBLD.NRO_DOCUMENTO AS SNIT,
  TRIM(T9.SDESCRIPT) AS SREGIONAL,
  TRIM(T9.SDESCRIPT) AS SCIUDAD,
  CASE WHEN (TP.SSTATREGT = 1) THEN
            CASE WHEN (TP.DOUTDATE IS NULL) THEN 'ACTIVO' ELSE 'INACTIVO' END  
  ELSE TRIM(REAGENERALPKG.REACODIGINT('TABLE26', 'SSTATREGT', TP.SSTATREGT)) END
  AS SESTADO,
  TBP.GRUPOS_ASIGNADOS AS SGRUPO,
  0 AS NTARIFA,
  0 AS NFACTOR_DESCUENTO,
  0 AS NFACTOR_INCREMENTO,
  0 AS NVALOR_UMA_LO,
  TPL.PLANES AS NPLAN_HABILITADO,  
  USCLI.USCLI.SCLIENAME AS SSUSCRIPTOR,
  TRIM(T9252.SDESCRIPT) AS SMODALIDAD_PAGO,
  'NO' AS SEXCEPCIONES
FROM TAB_PROVIDER TP
INNER JOIN TAB_PROV_ZONE TZ ON TP.NPROVIDER = TZ.NPROVIDER
INNER JOIN CLIENT C ON TP.SCLIENT = C.SCLIENT
LEFT JOIN TBLDOCUMENTO TBLD ON C.SCLIENT = TBLD.SCLIENT AND TBLD.rn = 1
LEFT JOIN TBLPRESTACIONES TBP ON TP.NPROVIDER = TBP.NPROVIDER
LEFT JOIN TBLPLANES TPL ON TP.NPROVIDER= TPL.NPROVIDER

LEFT JOIN TAB_PROV_MEDSPEC TPM ON TP.NPROVIDER = TPM.NPROVIDER AND TPM.NMAIN_MEDSPECIALIALTY=1
LEFT JOIN TABLE8603 T8603 ON TPM.SMEDSPECIALIALTY = T8603.SMEDSPECIALIALTY

LEFT JOIN TAB_PROV_SUBTYPES TPS ON TP.NTYPEPROV = TPS.NTYPEPROV AND TP.NSUBTYPEPROV = TPS.NSUBTYPEPROV
LEFT JOIN TABLE9 T9 ON TZ.NZONE = T9.NOFFICE
LEFT JOIN TABLE7027 T7027 ON TP.NTYPEPROV = T7027.NTYPEPROV
LEFT JOIN TABLE9252 T9252 ON TP.NPAYMENT_METHOD = T9252.NPAYMENT_METHOD 
LEFT JOIN USERS US ON TP.NUSERCODE = US.NUSERCODE
LEFT JOIN CLIENT USCLI ON US.SCLIENT = USCLI.SCLIENT 
WHERE TP.NTYPEPROV NOT IN (10) 
AND T9.NOFFICE = CASE WHEN NVL(NS_INSREDESMEDICAS515.NCOD_REGIONAL,0)=0 THEN T9.NOFFICE ELSE NS_INSREDESMEDICAS515.NCOD_REGIONAL END ;


  COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        NERROR := SQLCODE;
        SERRORDESC := SQLERRM;
        CRETRACE2('ERR TMP_INT515', 593, SERRORDESC);          
        RAISE;    
END NS_INSREDESMEDICAS515;